/* AUTO-GENERATED by tools/airtime_r3_oracle.py — do not hand-edit */
#ifndef NINLIL_AIRTIME_R3_VECTORS_GEN_H
#define NINLIL_AIRTIME_R3_VECTORS_GEN_H
#include <stdint.h>
#define NINLIL_AIRTIME_R3_VECTOR_COUNT (79u)
#define NINLIL_AIRTIME_R3_ORACLE_FORMULA_VERSION (1u)
typedef struct ninlil_airtime_r3_vector {
  const char *id;
  uint8_t sf, cr, header_implicit, crc_on, ldro, payload_len_bytes;
  uint16_t preamble_len_symbols;
  uint32_t bw_hz;
  uint32_t reserved_zero;
  uint32_t expect_status;
  uint32_t expect_airtime_us;
  uint32_t expect_n_payload_symbols;
  uint32_t expect_tsym_us_ceil;
  uint32_t expect_toa_numerator_lo;
  uint32_t expect_toa_numerator_hi;
  uint8_t expect_ldro_effective;
} ninlil_airtime_r3_vector_t;
static const ninlil_airtime_r3_vector_t
ninlil_airtime_r3_vectors[NINLIL_AIRTIME_R3_VECTOR_COUNT] = {
  { "ok_0_sf5_bw125000_pl16", 5u, 1u, 0u, 1u, 0u, 16u, 8u, 125000u, 0u, 0u, 15936u, 48u, 256u, 1992u, 0u, 0u },
  { "ok_1_sf6_bw125000_pl16", 6u, 1u, 0u, 1u, 0u, 16u, 8u, 125000u, 0u, 0u, 26752u, 38u, 512u, 3344u, 0u, 0u },
  { "ok_2_sf12_bw125000_pl16", 12u, 1u, 0u, 1u, 2u, 16u, 8u, 125000u, 0u, 0u, 1318912u, 28u, 32768u, 164864u, 0u, 1u },
  { "ok_3_sf7_bw7812_pl16", 7u, 1u, 0u, 1u, 0u, 16u, 8u, 7812u, 0u, 0u, 823349u, 38u, 16386u, 6432u, 0u, 0u },
  { "ok_4_sf5_bw7812_pl8", 5u, 1u, 0u, 1u, 0u, 8u, 8u, 7812u, 0u, 0u, 173068u, 28u, 4097u, 1352u, 0u, 0u },
  { "ok_5_sf7_bw10417_pl16", 7u, 1u, 0u, 1u, 0u, 16u, 8u, 10417u, 0u, 0u, 617453u, 38u, 12288u, 6432u, 0u, 0u },
  { "ok_6_sf5_bw10417_pl8", 5u, 1u, 0u, 1u, 0u, 8u, 8u, 10417u, 0u, 0u, 129788u, 28u, 3072u, 1352u, 0u, 0u },
  { "ok_7_sf7_bw15625_pl16", 7u, 1u, 0u, 1u, 0u, 16u, 8u, 15625u, 0u, 0u, 411648u, 38u, 8192u, 6432u, 0u, 0u },
  { "ok_8_sf5_bw15625_pl8", 5u, 1u, 0u, 1u, 0u, 8u, 8u, 15625u, 0u, 0u, 86528u, 28u, 2048u, 1352u, 0u, 0u },
  { "ok_9_sf7_bw20833_pl16", 7u, 1u, 0u, 1u, 0u, 16u, 8u, 20833u, 0u, 0u, 308741u, 38u, 6145u, 6432u, 0u, 0u },
  { "ok_10_sf5_bw20833_pl8", 5u, 1u, 0u, 1u, 0u, 8u, 8u, 20833u, 0u, 0u, 64898u, 28u, 1537u, 1352u, 0u, 0u },
  { "ok_11_sf7_bw31250_pl16", 7u, 1u, 0u, 1u, 0u, 16u, 8u, 31250u, 0u, 0u, 205824u, 38u, 4096u, 6432u, 0u, 0u },
  { "ok_12_sf5_bw31250_pl8", 5u, 1u, 0u, 1u, 0u, 8u, 8u, 31250u, 0u, 0u, 43264u, 28u, 1024u, 1352u, 0u, 0u },
  { "ok_13_sf7_bw41667_pl16", 7u, 1u, 0u, 1u, 0u, 16u, 8u, 41667u, 0u, 0u, 154367u, 38u, 3072u, 6432u, 0u, 0u },
  { "ok_14_sf5_bw41667_pl8", 5u, 1u, 0u, 1u, 0u, 8u, 8u, 41667u, 0u, 0u, 32448u, 28u, 768u, 1352u, 0u, 0u },
  { "ok_15_sf7_bw62500_pl16", 7u, 1u, 0u, 1u, 0u, 16u, 8u, 62500u, 0u, 0u, 102912u, 38u, 2048u, 6432u, 0u, 0u },
  { "ok_16_sf5_bw62500_pl8", 5u, 1u, 0u, 1u, 0u, 8u, 8u, 62500u, 0u, 0u, 21632u, 28u, 512u, 1352u, 0u, 0u },
  { "ok_17_sf7_bw125000_pl16", 7u, 1u, 0u, 1u, 0u, 16u, 8u, 125000u, 0u, 0u, 51456u, 38u, 1024u, 6432u, 0u, 0u },
  { "ok_18_sf5_bw125000_pl8", 5u, 1u, 0u, 1u, 0u, 8u, 8u, 125000u, 0u, 0u, 10816u, 28u, 256u, 1352u, 0u, 0u },
  { "ok_19_sf7_bw250000_pl16", 7u, 1u, 0u, 1u, 0u, 16u, 8u, 250000u, 0u, 0u, 25728u, 38u, 512u, 6432u, 0u, 0u },
  { "ok_20_sf5_bw250000_pl8", 5u, 1u, 0u, 1u, 0u, 8u, 8u, 250000u, 0u, 0u, 5408u, 28u, 128u, 1352u, 0u, 0u },
  { "ok_21_sf7_bw500000_pl16", 7u, 1u, 0u, 1u, 0u, 16u, 8u, 500000u, 0u, 0u, 12864u, 38u, 256u, 6432u, 0u, 0u },
  { "ok_22_sf5_bw500000_pl8", 5u, 1u, 0u, 1u, 0u, 8u, 8u, 500000u, 0u, 0u, 2704u, 28u, 64u, 1352u, 0u, 0u },
  { "ok_23_sf7_bw125000_pl16", 7u, 1u, 0u, 1u, 0u, 16u, 8u, 125000u, 0u, 0u, 51456u, 38u, 1024u, 6432u, 0u, 0u },
  { "ok_24_sf7_bw125000_pl16", 7u, 4u, 0u, 1u, 0u, 16u, 8u, 125000u, 0u, 0u, 69888u, 56u, 1024u, 8736u, 0u, 0u },
  { "ok_25_sf5_bw125000_pl0", 5u, 1u, 0u, 0u, 0u, 0u, 8u, 125000u, 0u, 0u, 5696u, 8u, 256u, 712u, 0u, 0u },
  { "ok_26_sf5_bw125000_pl255", 5u, 1u, 0u, 0u, 0u, 255u, 8u, 125000u, 0u, 0u, 136256u, 518u, 256u, 17032u, 0u, 0u },
  { "ok_27_sf5_bw125000_pl0", 5u, 1u, 0u, 1u, 0u, 0u, 8u, 125000u, 0u, 0u, 6976u, 13u, 256u, 872u, 0u, 0u },
  { "ok_28_sf5_bw125000_pl255", 5u, 1u, 0u, 1u, 0u, 255u, 8u, 125000u, 0u, 0u, 137536u, 523u, 256u, 17192u, 0u, 0u },
  { "ok_29_sf5_bw125000_pl0", 5u, 1u, 1u, 0u, 0u, 0u, 8u, 125000u, 0u, 0u, 5696u, 8u, 256u, 712u, 0u, 0u },
  { "ok_30_sf5_bw125000_pl255", 5u, 1u, 1u, 0u, 0u, 255u, 8u, 125000u, 0u, 0u, 134976u, 513u, 256u, 16872u, 0u, 0u },
  { "ok_31_sf5_bw125000_pl0", 5u, 1u, 1u, 1u, 0u, 0u, 8u, 125000u, 0u, 0u, 5696u, 8u, 256u, 712u, 0u, 0u },
  { "ok_32_sf5_bw125000_pl255", 5u, 1u, 1u, 1u, 0u, 255u, 8u, 125000u, 0u, 0u, 136256u, 518u, 256u, 17032u, 0u, 0u },
  { "ok_33_sf7_bw125000_pl0", 7u, 1u, 0u, 0u, 0u, 0u, 8u, 125000u, 0u, 0u, 20736u, 8u, 1024u, 2592u, 0u, 0u },
  { "ok_34_sf7_bw125000_pl255", 7u, 1u, 0u, 0u, 0u, 255u, 8u, 125000u, 0u, 0u, 394496u, 373u, 1024u, 49312u, 0u, 0u },
  { "ok_35_sf7_bw125000_pl0", 7u, 1u, 0u, 1u, 0u, 0u, 8u, 125000u, 0u, 0u, 25856u, 13u, 1024u, 3232u, 0u, 0u },
  { "ok_36_sf7_bw125000_pl255", 7u, 1u, 0u, 1u, 0u, 255u, 8u, 125000u, 0u, 0u, 399616u, 378u, 1024u, 49952u, 0u, 0u },
  { "ok_37_sf7_bw125000_pl0", 7u, 1u, 1u, 0u, 0u, 0u, 8u, 125000u, 0u, 0u, 20736u, 8u, 1024u, 2592u, 0u, 0u },
  { "ok_38_sf7_bw125000_pl255", 7u, 1u, 1u, 0u, 0u, 255u, 8u, 125000u, 0u, 0u, 394496u, 373u, 1024u, 49312u, 0u, 0u },
  { "ok_39_sf7_bw125000_pl0", 7u, 1u, 1u, 1u, 0u, 0u, 8u, 125000u, 0u, 0u, 20736u, 8u, 1024u, 2592u, 0u, 0u },
  { "ok_40_sf7_bw125000_pl255", 7u, 1u, 1u, 1u, 0u, 255u, 8u, 125000u, 0u, 0u, 394496u, 373u, 1024u, 49312u, 0u, 0u },
  { "ok_41_sf7_bw125000_pl16", 7u, 1u, 0u, 1u, 0u, 16u, 6u, 125000u, 0u, 0u, 49408u, 38u, 1024u, 6176u, 0u, 0u },
  { "ok_42_sf7_bw125000_pl16", 7u, 1u, 0u, 1u, 0u, 16u, 12u, 125000u, 0u, 0u, 55552u, 38u, 1024u, 6944u, 0u, 0u },
  { "ok_43_sf7_bw125000_pl16", 7u, 1u, 0u, 1u, 0u, 16u, 64u, 125000u, 0u, 0u, 108800u, 38u, 1024u, 13600u, 0u, 0u },
  { "ok_44_sf7_bw500000_pl1", 7u, 1u, 0u, 1u, 0u, 1u, 65535u, 500000u, 0u, 0u, 16781376u, 13u, 256u, 8390688u, 0u, 0u },
  { "ok_45_sf10_bw125000_pl16", 10u, 1u, 0u, 1u, 2u, 16u, 8u, 125000u, 0u, 0u, 329728u, 28u, 8192u, 41216u, 0u, 0u },
  { "ok_46_sf11_bw125000_pl16", 11u, 1u, 0u, 1u, 2u, 16u, 8u, 125000u, 0u, 0u, 659456u, 28u, 16384u, 82432u, 0u, 1u },
  { "ok_47_sf12_bw125000_pl16", 12u, 1u, 0u, 1u, 0u, 16u, 8u, 125000u, 0u, 0u, 1155072u, 23u, 32768u, 144384u, 0u, 0u },
  { "ok_48_sf12_bw125000_pl16", 12u, 1u, 0u, 1u, 1u, 16u, 8u, 125000u, 0u, 0u, 1318912u, 28u, 32768u, 164864u, 0u, 1u },
  { "ok_49_sf12_bw250000_pl16", 12u, 1u, 0u, 1u, 2u, 16u, 8u, 250000u, 0u, 0u, 659456u, 28u, 16384u, 164864u, 0u, 1u },
  { "ok_50_sf11_bw250000_pl16", 11u, 1u, 0u, 1u, 2u, 16u, 8u, 250000u, 0u, 0u, 288768u, 23u, 8192u, 72192u, 0u, 0u },
  { "ok_51_sf5_bw125000_pl16", 5u, 1u, 0u, 1u, 2u, 16u, 8u, 125000u, 0u, 0u, 15936u, 48u, 256u, 1992u, 0u, 0u },
  { "ok_52_sf12_bw7812_pl255", 12u, 4u, 0u, 1u, 1u, 255u, 65535u, 7812u, 0u, 3u, 0u, 0u, 0u, 270152704u, 0u, 1u },
  { "ok_53_sf12_bw500000_pl255", 12u, 4u, 0u, 1u, 1u, 255u, 65535u, 500000u, 0u, 0u, 540305408u, 416u, 8192u, 270152704u, 0u, 1u },
  { "neg_sf_low", 4u, 1u, 0u, 1u, 0u, 16u, 8u, 125000u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u },
  { "neg_sf_high", 13u, 1u, 0u, 1u, 0u, 16u, 8u, 125000u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u },
  { "neg_cr_0", 7u, 0u, 0u, 1u, 0u, 16u, 8u, 125000u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u },
  { "neg_cr_5_long_il", 7u, 5u, 0u, 1u, 0u, 16u, 8u, 125000u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u },
  { "neg_cr_6_long_il", 7u, 6u, 0u, 1u, 0u, 16u, 8u, 125000u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u },
  { "neg_cr_7_long_il", 7u, 7u, 0u, 1u, 0u, 16u, 8u, 125000u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u },
  { "neg_preamble_low", 7u, 1u, 0u, 1u, 0u, 16u, 5u, 125000u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u },
  { "neg_bw_old_7810", 7u, 1u, 0u, 1u, 0u, 16u, 8u, 7810u, 0u, 2u, 0u, 0u, 0u, 0u, 0u, 0u },
  { "neg_bw_old_10420", 7u, 1u, 0u, 1u, 0u, 16u, 8u, 10420u, 0u, 2u, 0u, 0u, 0u, 0u, 0u, 0u },
  { "neg_reserved", 7u, 1u, 0u, 1u, 0u, 16u, 8u, 125000u, 1u, 4u, 0u, 0u, 0u, 0u, 0u, 0u },
  { "neg_header_bad", 7u, 1u, 2u, 1u, 0u, 16u, 8u, 125000u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u },
  { "neg_crc_bad", 7u, 1u, 0u, 2u, 0u, 16u, 8u, 125000u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u },
  { "neg_ldro_bad", 7u, 1u, 0u, 1u, 9u, 16u, 8u, 125000u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u },
  { "hv_sf7_p0", 7u, 1u, 0u, 0u, 0u, 0u, 8u, 125000u, 0u, 0u, 20736u, 8u, 1024u, 2592u, 0u, 0u },
  { "hv_sf7_p3", 7u, 1u, 0u, 0u, 0u, 3u, 8u, 125000u, 0u, 0u, 25856u, 13u, 1024u, 3232u, 0u, 0u },
  { "hv_sf7_p4", 7u, 1u, 0u, 0u, 0u, 4u, 8u, 125000u, 0u, 0u, 30976u, 18u, 1024u, 3872u, 0u, 0u },
  { "hv_sf7_p5_explicit", 7u, 1u, 0u, 0u, 0u, 5u, 8u, 125000u, 0u, 0u, 30976u, 18u, 1024u, 3872u, 0u, 0u },
  { "hv_sf7_p5_implicit", 7u, 1u, 1u, 0u, 0u, 5u, 8u, 125000u, 0u, 0u, 25856u, 13u, 1024u, 3232u, 0u, 0u },
  { "hv_sf5_p16_pre12_de0", 5u, 1u, 0u, 1u, 0u, 16u, 12u, 125000u, 0u, 0u, 16960u, 48u, 256u, 2120u, 0u, 0u },
  { "hv_sf5_p16_pre12_de1_on", 5u, 1u, 0u, 1u, 1u, 16u, 12u, 125000u, 0u, 0u, 16960u, 48u, 256u, 2120u, 0u, 1u },
  { "hv_sf6_p16_pre12_cr4_impl", 6u, 4u, 1u, 0u, 0u, 16u, 12u, 125000u, 0u, 0u, 33920u, 48u, 512u, 4240u, 0u, 0u },
  { "hv_sf11_de0", 11u, 1u, 0u, 1u, 0u, 16u, 8u, 125000u, 0u, 0u, 577536u, 23u, 16384u, 72192u, 0u, 0u },
  { "hv_sf11_de1", 11u, 1u, 0u, 1u, 1u, 16u, 8u, 125000u, 0u, 0u, 659456u, 28u, 16384u, 82432u, 0u, 1u },
  { "hv_sf12_bw250_de1", 12u, 1u, 0u, 1u, 1u, 16u, 8u, 250000u, 0u, 0u, 659456u, 28u, 16384u, 164864u, 0u, 1u },
  { "max_sf12_bw7812_overflow_us", 12u, 4u, 0u, 1u, 1u, 255u, 65535u, 7812u, 0u, 3u, 0u, 0u, 0u, 270152704u, 0u, 1u },
};
#endif
