/* SPDX-License-Identifier: Apache-2.0 */
/*
 * Private route-relay / multi-parent types (ADR-0019 / ADR-0020).
 * Default-OFF, not installed, not public ABI. Symbol prefix: ninlil_rrmp_
 */
#ifndef NINLIL_RUNTIME_ROUTE_RELAY_V1_RRMP_TYPES_H
#define NINLIL_RUNTIME_ROUTE_RELAY_V1_RRMP_TYPES_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* --- Normative constants (vector normative_constants) --- */
#define NINLIL_RRMP_API_VERSION 1u
#define NINLIL_RRMP_SCHEMA_VERSION 1u
#define NINLIL_RRMP_WIRE_PROFILE_ID 17u

#define NINLIL_RRMP_DIR_BYTES 256u
#define NINLIL_RRMP_NRM1_BYTES 256u
#define NINLIL_RRMP_NRP1_BYTES 4096u
#define NINLIL_RRMP_NRP1_HEADER_BYTES 20u
#define NINLIL_RRMP_NRP1_PAD_BYTES 12u
#define NINLIL_RRMP_SLOT_BYTES 508u
#define NINLIL_RRMP_SLOTS_PER_PAGE 8u
#define NINLIL_RRMP_PAGE_COUNT 16u
#define NINLIL_RRMP_ROUTE_MAX 128u
#define NINLIL_RRMP_EXACT_BODY_BYTES 96u
/*
 * Application carrier on hop TX (NCL1 / bearer body). Separate from NRM1 E2E
 * rewrap (96). Production outbound may carry this to Fabric/WiFi providers.
 */
#define NINLIL_RRMP_OUTBOUND_CARRIER_MAX 1024u
#define NINLIL_RRMP_INSTALL_BATCH_HEADER_BYTES 56u
#define NINLIL_RRMP_INSTALL_BATCH_MAX 8u
#define NINLIL_RRMP_LOGICAL_MUTATIONS_MAX 9u

#define NINLIL_RRMP_NEV1_BYTES 128u
#define NINLIL_RRMP_NEP1_BYTES 4096u
#define NINLIL_RRMP_NEP1_HEADER_BYTES 24u
#define NINLIL_RRMP_NEP1_PAD_BYTES 104u
#define NINLIL_RRMP_NEP1_SLOTS 31u
#define NINLIL_RRMP_NEP1_PAGE_COUNT 4u
#define NINLIL_RRMP_EVIDENCE_CAPACITY 124u
#define NINLIL_RRMP_EVIDENCE_LIFECYCLE_EMPTY 0u
#define NINLIL_RRMP_EVIDENCE_LIFECYCLE_LIVE 1u
#define NINLIL_RRMP_EVIDENCE_LIFECYCLE_COMPLETED 2u

#define NINLIL_RRMP_NOA1_BYTES 400u
#define NINLIL_RRMP_NPS1_BYTES 256u
#define NINLIL_RRMP_NPH1_BYTES 256u
#define NINLIL_RRMP_NPP1_BYTES 4096u
#define NINLIL_RRMP_NPP1_HEADER_BYTES 16u
#define NINLIL_RRMP_NPP1_PAD_BYTES 240u
#define NINLIL_RRMP_NPP1_SLOTS 15u
#define NINLIL_RRMP_NPP1_PAGE_COUNT 5u
/* Exact live scope capacity (≥64 via NPP1 5×15; ADR-0020 §12.1). */
#define NINLIL_RRMP_SCOPE_PARENT_SET_CAPACITY 64u
#define NINLIL_RRMP_NPA1_BYTES 4096u
#define NINLIL_RRMP_NPA1_HEADER_BYTES 16u
#define NINLIL_RRMP_NPA1_PAD_BYTES 304u
#define NINLIL_RRMP_ASSIGNMENT_SLOT_BYTES 472u
#define NINLIL_RRMP_ASSIGNMENT_SLOTS_PER_PAGE 8u
#define NINLIL_RRMP_NPA1_PAGE_COUNT 8u
#define NINLIL_RRMP_NPT1_BYTES 4096u
#define NINLIL_RRMP_NPT1_HEADER_BYTES 24u
#define NINLIL_RRMP_NPT1_PAD_BYTES 40u
#define NINLIL_RRMP_NPT1_SLOT_BYTES 48u
#define NINLIL_RRMP_NPT1_SLOTS_PER_PAGE 84u
#define NINLIL_RRMP_NPT1_PAGE_COUNT 8u
#define NINLIL_RRMP_TOKEN_REPLAY_LEDGER_CAPACITY 256u
#define NINLIL_RRMP_PARENT_MAX 8u

#define NINLIL_RRMP_PHYSICAL_KEY_COUNT 21u
#define NINLIL_RRMP_LOOP_WINDOW 256u
#define NINLIL_RRMP_DEDUP_WINDOW 256u
#define NINLIL_RRMP_MAX_HOPS_ABSOLUTE 8u
#define NINLIL_RRMP_MAX_HOPS_PROFILE_ESP_V1 3u
#define NINLIL_RRMP_MAX_ATTEMPTS 3u
#define NINLIL_RRMP_MAX_LINK_GROUPS 13u
#define NINLIL_RRMP_MAX_AIRTIME_BUDGET_MS 60000u
#define NINLIL_RRMP_QUEUE_GLOBAL_ENTRIES 64u
#define NINLIL_RRMP_QUEUE_GLOBAL_BYTES 16320u
#define NINLIL_RRMP_RESERVED_CONTROL_ENTRIES 8u
#define NINLIL_RRMP_RESERVED_CONTROL_BYTES 2048u
#define NINLIL_RRMP_ACK_TIMEOUT_DEFAULT_MS 5000u
#define NINLIL_RRMP_RETRY_BACKOFF_MIN_MS 100u
#define NINLIL_RRMP_WORKER_MAX_STEPS 8u
#define NINLIL_RRMP_RESULT_BYTES 128u
#define NINLIL_RRMP_PREAMBLE_BYTES 16u
#define NINLIL_RRMP_ID16_BYTES 16u
#define NINLIL_RRMP_DIGEST32_BYTES 32u

/* RRP-1 bounded Platform Storage bundle (private, source-only). */
#define NINLIL_RRMP_RRM1_BYTES 256u
#define NINLIL_RRMP_RRM1_CHUNK_BYTES_MAX 61440u
#define NINLIL_RRMP_RRM1_CHUNK_COUNT_MAX 5u
#define NINLIL_RRMP_RRM1_LOGICAL_BYTES_MAX 307200u
#define NINLIL_RRMP_RRM1_LOGICAL_REQUIRED_MAX 290720u
#define NINLIL_RRMP_PLATFORM_VALUE_BYTES_MAX 65536u

/* RRP-2 QST4 global used-attempt ledger. */
#define NINLIL_RRMP_QST4_HEADER_BYTES 56u
#define NINLIL_RRMP_QST4_ATTEMPT_BYTES 80u
#define NINLIL_RRMP_QST4_ATTEMPT_CAPACITY 256u
#define NINLIL_RRMP_QST4_HANDOFF_TUPLE_BYTES 224u
#define NINLIL_RRMP_QST4_HANDOFF_TUPLE_CAPACITY 64u
#define NINLIL_RRMP_QST4_MAX_BYTES 84696u
#define NINLIL_RRMP_ATTEMPT_RETENTION_MS 60000u
#define NINLIL_RRMP_ATTEMPT_EMPTY 0u
#define NINLIL_RRMP_ATTEMPT_LIVE 1u
#define NINLIL_RRMP_ATTEMPT_TERMINAL_RETAINED 2u
#define NINLIL_RRMP_ATTEMPT_FLAG_NEV1 1u
#define NINLIL_RRMP_ATTEMPT_FLAG_HANDOFF_TOMBSTONE 2u

/* RRP-4 durable authority-global fence reason (no clear API in v2). */
#define NINLIL_RRMP_AUTHORITY_FENCE_NONE 0u
#define NINLIL_RRMP_AUTHORITY_FENCE_WRITER_CONFLICT 1u
#define NINLIL_RRMP_AUTHORITY_FENCE_LEGACY_ATTEMPT_STATE 2u

/*
 * Workspace budget (ESP PSRAM allocation authority): owner state plus its
 * durable export/piece scratch fit one caller-owned allocation. Required 22
 * parent keys + 21 route keys are retained; raw page caches are not mirrored
 * per live scope (re-encode / durable reload).
 * Caller-owned workspace must be at least 8-byte aligned (uint64 fields).
 */
#define NINLIL_RRMP_OWNER_WORKSPACE_BUDGET_BYTES (768u * 1024u)
#define NINLIL_RRMP_OWNER_WORKSPACE_ALIGN 8u

/* Route state in slot[0] (durable page encoding; distinct from LIFE_*) */
#define NINLIL_RRMP_ROUTE_STATE_EMPTY 0u
#define NINLIL_RRMP_ROUTE_STATE_INSTALLED 1u
#define NINLIL_RRMP_ROUTE_STATE_ACTIVE 2u
#define NINLIL_RRMP_ROUTE_STATE_DRAINING 3u
#define NINLIL_RRMP_ROUTE_STATE_EXPIRED 4u
#define NINLIL_RRMP_ROUTE_STATE_RETIRED 5u

/* Handoff machine states S1..S6 */
#define NINLIL_RRMP_HANDOFF_NONE 0u
#define NINLIL_RRMP_HANDOFF_PREPARED_NEW 1u
#define NINLIL_RRMP_HANDOFF_OLD_FENCED_PROOF 2u
#define NINLIL_RRMP_HANDOFF_AUTHORITY_COMMITTED 3u
#define NINLIL_RRMP_HANDOFF_NEW_OWNER_ACTIVATED 4u
#define NINLIL_RRMP_HANDOFF_ENDPOINT_OBSERVED 5u
#define NINLIL_RRMP_HANDOFF_OLD_RETIRED 6u

/* Queue class for CONTROL/SAFETY reservation */
#define NINLIL_RRMP_QCLASS_APPLICATION 0u
#define NINLIL_RRMP_QCLASS_CONTROL 1u
#define NINLIL_RRMP_QCLASS_SAFETY 2u

/* CU classes */
#define NINLIL_RRMP_CU_NONE 0u
#define NINLIL_RRMP_CU_OLD 1u
#define NINLIL_RRMP_CU_NEW 2u
#define NINLIL_RRMP_CU_ABSENT 3u
#define NINLIL_RRMP_CU_PARTIAL 4u
#define NINLIL_RRMP_CU_EXTRA 5u
#define NINLIL_RRMP_CU_THIRD 6u

/* NPT1 token kinds */
#define NINLIL_RRMP_NPT1_KIND_EMPTY 0u
#define NINLIL_RRMP_NPT1_KIND_TOKEN_LIVE 1u
#define NINLIL_RRMP_NPT1_KIND_TOMBSTONE_USED 2u

/* Route status codes (vector status_codes_route) */
#define NINLIL_ROUTE_OK 1u
#define NINLIL_ROUTE_INVALID_ARGUMENT 2u
#define NINLIL_ROUTE_CORRUPT 3u
#define NINLIL_ROUTE_UNSUPPORTED_API 4u
#define NINLIL_ROUTE_UNSUPPORTED_SCHEMA 5u
#define NINLIL_ROUTE_UNSUPPORTED_CAPABILITY 6u
#define NINLIL_ROUTE_AUTHORITY_CONFLICT 7u
#define NINLIL_ROUTE_STALE_GENERATION 8u
#define NINLIL_ROUTE_LEASE_EXPIRED 9u
#define NINLIL_ROUTE_CLOCK_EPOCH_MISMATCH 10u
#define NINLIL_ROUTE_LOOP 11u
#define NINLIL_ROUTE_TERMINAL_MISMATCH 12u
#define NINLIL_ROUTE_HOP_EXHAUSTED 13u
#define NINLIL_ROUTE_REPLAY 14u
#define NINLIL_ROUTE_DRAIN_FENCED 15u
#define NINLIL_ROUTE_NOT_ACTIVE 16u
#define NINLIL_ROUTE_RESOURCE 17u
#define NINLIL_ROUTE_BACKPRESSURE 18u
#define NINLIL_ROUTE_COMMIT_UNKNOWN 19u
#define NINLIL_ROUTE_REENTRANT 20u
#define NINLIL_ROUTE_FEATURE_OFF 21u

/* Outbound packet ownership (bearer/radio submit; not simulated ACK). */
#define NINLIL_RRMP_OUTBOUND_ACCEPTED 1u
#define NINLIL_RRMP_OUTBOUND_WOULD_BLOCK 2u
#define NINLIL_RRMP_OUTBOUND_RETAINED 3u
#define NINLIL_RRMP_OUTBOUND_LOST 4u
#define NINLIL_RRMP_OUTBOUND_DENIED 5u
#define NINLIL_RRMP_OUTBOUND_NO_PROVIDER 6u

/* In-process private caller authorization capabilities. */
#define NINLIL_RRMP_AUTH_ROUTE_ADMIN (1u << 0)
#define NINLIL_RRMP_AUTH_FORWARD     (1u << 1)
#define NINLIL_RRMP_AUTH_PARENT_ADMIN (1u << 2)
#define NINLIL_RRMP_AUTH_DIAGNOSTICS (1u << 3)
#define NINLIL_RRMP_AUTH_BEARER      (1u << 4)
#define NINLIL_RRMP_AUTH_WORKER      (1u << 5)
#define NINLIL_RRMP_AUTH_ALL         ((1u << 6) - 1u)

/* Parent status codes (vector status_codes_parent) */
#define NINLIL_PARENT_OK 1u
#define NINLIL_PARENT_INVALID_ARGUMENT 2u
#define NINLIL_PARENT_CORRUPT 3u
#define NINLIL_PARENT_UNSUPPORTED_API 4u
#define NINLIL_PARENT_UNSUPPORTED_SCHEMA 5u
#define NINLIL_PARENT_UNSUPPORTED_CAPABILITY 6u
#define NINLIL_PARENT_AUTHORITY_CONFLICT 7u
#define NINLIL_PARENT_SPLIT_BRAIN 8u
#define NINLIL_PARENT_STALE_TERM 9u
#define NINLIL_PARENT_STALE_REVISION 10u
#define NINLIL_PARENT_LEASE_EXPIRED 11u
#define NINLIL_PARENT_CLOCK_EPOCH_MISMATCH 12u
#define NINLIL_PARENT_TOKEN_REPLAY 13u
#define NINLIL_PARENT_SCOPE_MISMATCH 14u
#define NINLIL_PARENT_NOT_OWNER 15u
#define NINLIL_PARENT_NOT_ACTIVE 16u
#define NINLIL_PARENT_SAME_ATTEMPT_RESELECT 17u
#define NINLIL_PARENT_RESOURCE 18u
#define NINLIL_PARENT_COMMIT_UNKNOWN 19u
#define NINLIL_PARENT_REENTRANT 20u
#define NINLIL_PARENT_FEATURE_OFF 21u

typedef uint32_t ninlil_route_status_u32;
typedef uint32_t ninlil_parent_status_u32;

typedef struct ninlil_rrmp_id16 {
    uint8_t bytes[NINLIL_RRMP_ID16_BYTES];
} ninlil_rrmp_id16_t;

typedef struct ninlil_rrmp_digest32 {
    uint8_t bytes[NINLIL_RRMP_DIGEST32_BYTES];
} ninlil_rrmp_digest32_t;

/* Preamble / request / result layouts live in rrmp_abi.h (exact ADR packing). */

#ifdef __cplusplus
}
#endif

#endif /* NINLIL_RUNTIME_ROUTE_RELAY_V1_RRMP_TYPES_H */
