/*
 * D2-S3 production profiled-begin structural bridge: executes each
 * domain-scan-structural-v1 vector through ninlil_domain_scan_begin_profiled
 * + scripted spy and compares status/adopted/counts/profile diagnostics/
 * port-trace against the independent oracle. Fixture is generated by
 * tools/domain_scan_structural_vector_gen.py (no production C translation).
 * Does not claim D2/DSR1/DSR2/Stage5 complete.
 */

#include "domain_store_scanner.h"
#include "scripted_storage_spy.h"

#include "domain_scan_structural_vector_fixture.h"

#include <stdio.h>
#include <string.h>

#define REQUIRE(condition)                                                     \
    do {                                                                       \
        if (!(condition)) {                                                    \
            (void)fprintf(stderr, "%s:%d: %s failed: %s\n", __FILE__,          \
                __LINE__, current_id, #condition);                             \
            return 1;                                                          \
        }                                                                      \
    } while (0)

static const char *current_id = "";

static ninlil_status_t status_from_name(const char *name)
{
    if (strcmp(name, "OK") == 0) {
        return NINLIL_OK;
    }
    if (strcmp(name, "INVALID_ARGUMENT") == 0) {
        return NINLIL_E_INVALID_ARGUMENT;
    }
    if (strcmp(name, "UNSUPPORTED") == 0) {
        return NINLIL_E_UNSUPPORTED;
    }
    if (strcmp(name, "STORAGE") == 0) {
        return NINLIL_E_STORAGE;
    }
    if (strcmp(name, "STORAGE_CORRUPT") == 0) {
        return NINLIL_E_STORAGE_CORRUPT;
    }
    if (strcmp(name, "STORAGE_COMMIT_UNKNOWN") == 0) {
        return NINLIL_E_STORAGE_COMMIT_UNKNOWN;
    }
    if (strcmp(name, "INVALID_STATE") == 0) {
        return NINLIL_E_INVALID_STATE;
    }
    if (strcmp(name, "WOULD_BLOCK") == 0) {
        return NINLIL_E_WOULD_BLOCK;
    }
    if (strcmp(name, "CAPACITY_EXHAUSTED") == 0) {
        return NINLIL_E_CAPACITY_EXHAUSTED;
    }
    return (ninlil_status_t)0xFFFFu;
}

static ninlil_domain_scan_state_t state_from_name(const char *name)
{
    if (strcmp(name, "IDLE") == 0) {
        return NINLIL_DOMAIN_SCAN_STATE_IDLE;
    }
    if (strcmp(name, "OPEN") == 0) {
        return NINLIL_DOMAIN_SCAN_STATE_OPEN;
    }
    if (strcmp(name, "EXHAUSTED") == 0) {
        return NINLIL_DOMAIN_SCAN_STATE_EXHAUSTED;
    }
    if (strcmp(name, "FAILED") == 0) {
        return NINLIL_DOMAIN_SCAN_STATE_FAILED;
    }
    if (strcmp(name, "DONE") == 0) {
        return NINLIL_DOMAIN_SCAN_STATE_DONE;
    }
    return (ninlil_domain_scan_state_t)0xFFu;
}

static ninlil_spy_op_t spy_op_from_name(const char *name)
{
    if (strcmp(name, "begin") == 0) {
        return NINLIL_SPY_OP_BEGIN;
    }
    if (strcmp(name, "get") == 0) {
        return NINLIL_SPY_OP_GET;
    }
    if (strcmp(name, "iter_open") == 0) {
        return NINLIL_SPY_OP_ITER_OPEN;
    }
    if (strcmp(name, "iter_next") == 0) {
        return NINLIL_SPY_OP_ITER_NEXT;
    }
    if (strcmp(name, "rollback") == 0) {
        return NINLIL_SPY_OP_ROLLBACK;
    }
    return NINLIL_SPY_OP_COUNT;
}

static ninlil_spy_shape_t shape_from_name(const char *name)
{
    if (strcmp(name, "bts") == 0) {
        return NINLIL_SPY_SHAPE_BTS_LENGTHS;
    }
    if (strcmp(name, "not_found_poison") == 0) {
        return NINLIL_SPY_SHAPE_NOT_FOUND_POISON;
    }
    if (strcmp(name, "io_error") == 0) {
        return NINLIL_SPY_SHAPE_NATURAL;
    }
    if (strcmp(name, "unknown") == 0) {
        return NINLIL_SPY_SHAPE_NATURAL;
    }
    if (strcmp(name, "commit_unknown") == 0) {
        return NINLIL_SPY_SHAPE_NATURAL;
    }
    if (strcmp(name, "value_mismatch") == 0) {
        return NINLIL_SPY_SHAPE_VALUE_MISMATCH;
    }
    if (strcmp(name, "early_end") == 0) {
        return NINLIL_SPY_SHAPE_EARLY_END;
    }
    if (strcmp(name, "rewrite_data_ptr") == 0) {
        return NINLIL_SPY_SHAPE_REWRITE_DATA_PTR;
    }
    if (strcmp(name, "rewrite_capacity") == 0) {
        return NINLIL_SPY_SHAPE_REWRITE_CAPACITY;
    }
    return NINLIL_SPY_SHAPE_NATURAL;
}

static ninlil_storage_status_t status_for_fault(const ninlil_dss_fault_t *f)
{
    if (strcmp(f->shape, "bts") == 0) {
        return NINLIL_STORAGE_BUFFER_TOO_SMALL;
    }
    if (strcmp(f->shape, "not_found_poison") == 0) {
        return NINLIL_STORAGE_NOT_FOUND;
    }
    if (strcmp(f->shape, "early_end") == 0) {
        return NINLIL_STORAGE_NOT_FOUND;
    }
    if (strcmp(f->shape, "io_error") == 0) {
        return NINLIL_STORAGE_IO_ERROR;
    }
    if (strcmp(f->shape, "unknown") == 0) {
        return (ninlil_storage_status_t)99u;
    }
    if (strcmp(f->shape, "commit_unknown") == 0) {
        return NINLIL_STORAGE_COMMIT_UNKNOWN;
    }
    if (strcmp(f->shape, "value_mismatch") == 0
        || strcmp(f->shape, "rewrite_data_ptr") == 0
        || strcmp(f->shape, "rewrite_capacity") == 0) {
        return NINLIL_STORAGE_OK;
    }
    return NINLIL_STORAGE_OK;
}

/*
 * Independent catalog key bytes for get order proof (literal root/family/
 * suffix; does not call production build_key).
 */
static const uint8_t DSP_ROOT_V1[8] = {
    0x4eu, 0x49u, 0x4eu, 0x4cu, 0x49u, 0x4cu, 0x00u, 0x01u
};

static void dsp_literal_catalog_key(
    uint32_t key_id,
    uint8_t *out,
    uint32_t *out_length)
{
    (void)memcpy(out, DSP_ROOT_V1, sizeof(DSP_ROOT_V1));
    if (key_id == 1u) {
        out[8] = 0x01u;
        *out_length = 9u;
        return;
    }
    if (key_id == 2u) {
        out[8] = 0x02u;
        *out_length = 9u;
        return;
    }
    if (key_id >= 3u && key_id <= 6u) {
        out[8] = 0x03u;
        out[9] = (uint8_t)(key_id - 2u);
        *out_length = 10u;
        return;
    }
    /* capacity key_id 7..17 → suffix 1..11 */
    out[8] = 0x04u;
    out[9] = (uint8_t)(key_id - 6u);
    *out_length = 10u;
}

static int assert_get_catalog_key_order(const ninlil_scripted_storage_spy_t *spy)
{
    uint32_t expected_id = 1u;
    size_t i;

    for (i = 0u; i < spy->trace_count; ++i) {
        uint8_t want[16];
        uint32_t want_len = 0u;

        if (spy->trace[i].op != NINLIL_SPY_OP_GET) {
            continue;
        }
        if (expected_id > 17u) {
            return 0;
        }
        dsp_literal_catalog_key(expected_id, want, &want_len);
        if (spy->trace[i].key_bytes_length != want_len) {
            return 0;
        }
        if (memcmp(spy->trace[i].key_bytes, want, want_len) != 0) {
            return 0;
        }
        expected_id += 1u;
    }
    /* Partial get sequences (terminal mid-loop) are allowed; full success has 17. */
    return 1;
}

static const char *spy_op_name(ninlil_spy_op_t op)
{
    switch (op) {
    case NINLIL_SPY_OP_BEGIN:
        return "begin:READ_ONLY";
    case NINLIL_SPY_OP_GET:
        return "get";
    case NINLIL_SPY_OP_ITER_OPEN:
        return "iter_open:prefix0";
    case NINLIL_SPY_OP_ITER_NEXT:
        return "iter_next";
    case NINLIL_SPY_OP_ITER_CLOSE:
        return "iter_close";
    case NINLIL_SPY_OP_ROLLBACK:
        return "rollback";
    case NINLIL_SPY_OP_CLOSE:
        return "close";
    default:
        return "other";
    }
}

static void fill_candidate(
    ninlil_model_runtime_store_binding_t *out,
    const ninlil_dss_binding_t *in)
{
    (void)memset(out, 0, sizeof(*out));
    out->storage_schema = in->storage_schema;
    out->role = (ninlil_role_t)in->role;
    out->environment = (ninlil_environment_t)in->environment;
    (void)memcpy(out->runtime_id.bytes, in->runtime_id, 16u);
    out->limits.max_services = in->max_services;
    out->limits.max_nonterminal_transactions =
        in->max_nonterminal_transactions;
    out->limits.max_targets_per_transaction =
        in->max_targets_per_transaction;
    out->limits.max_logical_payload_bytes = in->max_logical_payload_bytes;
    out->limits.max_durable_outbox_payload_bytes =
        in->max_durable_outbox_payload_bytes;
    out->limits.max_attempts_per_target_per_cycle =
        in->max_attempts_per_target_per_cycle;
    out->limits.max_cancel_attempts_per_transaction =
        in->max_cancel_attempts_per_transaction;
    out->limits.max_evidence_per_target = in->max_evidence_per_target;
    out->limits.max_retained_terminal_transactions =
        in->max_retained_terminal_transactions;
    out->limits.max_nonterminal_deliveries = in->max_nonterminal_deliveries;
    out->limits.max_event_spool_count = in->max_event_spool_count;
    out->limits.max_event_spool_bytes = in->max_event_spool_bytes;
    out->limits.max_result_cache_entries = in->max_result_cache_entries;
    out->limits.max_retained_dispositions = in->max_retained_dispositions;
    out->limits.max_ingress_per_step = in->max_ingress_per_step;
    out->limits.max_callbacks_per_step = in->max_callbacks_per_step;
    out->limits.max_state_transitions_per_step =
        in->max_state_transitions_per_step;
    out->limits.max_bearer_sends_per_step = in->max_bearer_sends_per_step;
    out->limits.max_deferred_tokens = in->max_deferred_tokens;
    out->terminal_retention_ms = in->terminal_retention_ms;
    out->result_cache_retention_ms = in->result_cache_retention_ms;
    out->observation_retention_ms = in->observation_retention_ms;
}

static int run_vector(const ninlil_dss_vector_t *vec)
{
    ninlil_scripted_storage_spy_t spy;
    ninlil_domain_scan_session_t session;
    ninlil_domain_scan_workspace_t workspace;
    ninlil_domain_scan_result_t result;
    ninlil_model_runtime_store_binding_t candidate;
    ninlil_storage_handle_t handle;
    ninlil_storage_handle_t original_handle;
    const ninlil_storage_ops_t *ops;
    ninlil_status_t status = NINLIL_OK;
    size_t i;
    size_t mapped_trace = 0u;
    const char *mapped[NINLIL_DSS_MAX_TRACE];
    const char *last_op;

    current_id = vec->id;
    ninlil_spy_init(&spy);
    ops = ninlil_spy_ops(&spy);
    handle = ninlil_spy_open_handle(&spy);
    original_handle = handle;
    fill_candidate(&candidate, &vec->candidate);

    for (i = 0u; i < vec->row_count; ++i) {
        REQUIRE(ninlil_spy_add_row(&spy, vec->rows[i].key,
            vec->rows[i].key_length,
            vec->rows[i].value_length == 0u ? NULL : vec->rows[i].value,
            vec->rows[i].value_length));
    }
    for (i = 0u; i < vec->fault_count; ++i) {
        const ninlil_dss_fault_t *f = &vec->faults[i];
        ninlil_spy_op_t op = spy_op_from_name(f->op);
        REQUIRE(op < NINLIL_SPY_OP_COUNT);
        REQUIRE(ninlil_spy_add_fault(&spy, op, f->on_call, status_for_fault(f),
            shape_from_name(f->shape), f->key_length, f->value_length));
    }

    ninlil_domain_scan_session_init(&session);
    (void)memset(&workspace, 0, sizeof(workspace));
    (void)memset(&result, 0, sizeof(result));

    for (i = 0u; i < vec->call_count; ++i) {
        const ninlil_dss_call_t *call = &vec->calls[i];
        if (strcmp(call->op, "begin_profiled") == 0) {
            status = ninlil_domain_scan_begin_profiled(
                &session, ops, &handle, &workspace, &candidate);
        } else if (strcmp(call->op, "advance") == 0) {
            status = ninlil_domain_scan_advance(&session, call->row_budget);
        } else if (strcmp(call->op, "finalize") == 0) {
            status = ninlil_domain_scan_finalize(&session, &result);
        } else if (strcmp(call->op, "abort") == 0) {
            status = ninlil_domain_scan_abort(&session, &result);
        } else {
            REQUIRE(0);
        }
    }

    REQUIRE(status == status_from_name(vec->expected.final_status));
    REQUIRE(session.state == state_from_name(vec->expected.state_after));

    last_op = vec->calls[vec->call_count - 1u].op;
    if (strcmp(last_op, "finalize") == 0 || strcmp(last_op, "abort") == 0) {
        REQUIRE(result.status == status);
        REQUIRE(result.adopted == vec->expected.adopted);
        REQUIRE(result.recognizable_future_seen
            == vec->expected.recognizable_future_seen);
        REQUIRE(result.family14_row_count == vec->expected.family14_row_count);
        REQUIRE(result.current_domain_key_count
            == vec->expected.current_domain_key_count);
        REQUIRE(result.ok_row_count == vec->expected.ok_row_count);
        REQUIRE(result.profile_exact_active
            == vec->expected.profile_exact_active);
        REQUIRE(result.profile_mismatch == vec->expected.profile_mismatch);
        REQUIRE(result.future_profile_candidate
            == vec->expected.future_profile_candidate);
        REQUIRE(result.profile_get_present_mask
            == vec->expected.profile_get_present_mask);
        REQUIRE(result.family14_iter_seen_mask
            == vec->expected.family14_iter_seen_mask);
        REQUIRE(result.reopen_required == vec->expected.reopen_required);
    } else if (strcmp(last_op, "begin_profiled") == 0) {
        /*
         * Begin-only path: every oracle-visible session diagnostic must match
         * exactly. No status-based OR escape for masks/flags.
         */
        REQUIRE(session.reopen_required == vec->expected.reopen_required);
        REQUIRE(session.profile_get_present_mask
            == vec->expected.profile_get_present_mask);
        REQUIRE(session.family14_iter_seen_mask
            == vec->expected.family14_iter_seen_mask);
        REQUIRE(session.profile_exact_active
            == vec->expected.profile_exact_active);
        REQUIRE(session.profile_mismatch == vec->expected.profile_mismatch);
        REQUIRE(session.future_profile_candidate
            == vec->expected.future_profile_candidate);
        REQUIRE(session.recognizable_future_seen
            == vec->expected.recognizable_future_seen);
        REQUIRE(session.family14_row_count == vec->expected.family14_row_count);
        REQUIRE(session.current_domain_key_count
            == vec->expected.current_domain_key_count);
        REQUIRE(session.ok_row_count == vec->expected.ok_row_count);
        if (status != NINLIL_OK) {
            REQUIRE(spy.iter_open_calls == 0u);
        }
    }

    REQUIRE(spy.close_calls == vec->expected.close_count);
    if (vec->expected.close_count != 0u) {
        REQUIRE(ninlil_spy_close_count_for_handle(&spy, original_handle)
            == vec->expected.close_count);
        REQUIRE(handle == NULL);
    } else if (strcmp(last_op, "finalize") == 0
        && vec->expected.adopted == 1u) {
        REQUIRE(handle == original_handle);
        REQUIRE(ninlil_spy_close_count_for_handle(&spy, original_handle) == 0u);
    }

    REQUIRE(spy.mutation_calls == 0u);
    REQUIRE(ninlil_spy_assert_no_mutations(&spy));
    REQUIRE(vec->expected.mutation_calls == 0u);

    for (i = 0u; i < spy.trace_count && mapped_trace < NINLIL_DSS_MAX_TRACE;
         ++i) {
        const char *name = spy_op_name(spy.trace[i].op);
        if (strcmp(name, "other") == 0) {
            continue;
        }
        mapped[mapped_trace++] = name;
    }
    REQUIRE(mapped_trace == vec->expected.port_trace_count);
    for (i = 0u; i < mapped_trace; ++i) {
        REQUIRE(strcmp(mapped[i], vec->expected.port_trace[i]) == 0);
    }

    /* Exact get key-ID order: literal catalog bytes, not count alone. */
    REQUIRE(assert_get_catalog_key_order(&spy));

    /* Causal: success-gate paths must show 17 gets then exactly one iter_open. */
    if (vec->expected.final_status[0] != '\0'
        && (vec->expected.profile_exact_active != 0u
            || vec->expected.profile_mismatch != 0u
            || vec->expected.future_profile_candidate != 0u)
        && strcmp(vec->expected.final_status, "STORAGE_CORRUPT") != 0) {
        size_t gets = 0u;
        size_t opens = 0u;
        int saw_open = 0;
        for (i = 0u; i < mapped_trace; ++i) {
            if (strcmp(mapped[i], "get") == 0) {
                REQUIRE(saw_open == 0);
                gets += 1u;
            } else if (strcmp(mapped[i], "iter_open:prefix0") == 0) {
                saw_open = 1;
                opens += 1u;
            }
        }
        if (opens != 0u) {
            REQUIRE(gets == 17u);
            REQUIRE(opens == 1u);
        }
    }

    /*
     * dsr2_ceiling: material bound check from top-level workspace schema +
     * live sizeof, not a decorative success clone.
     */
    if (strcmp(vec->kind, "dsr2_ceiling") == 0) {
        REQUIRE(NINLIL_DSS_WORKSPACE_CEILING_BYTES == 8192u);
        REQUIRE(sizeof(ninlil_domain_scan_workspace_t)
            <= NINLIL_DSS_WORKSPACE_CEILING_BYTES);
        REQUIRE(NINLIL_DOMAIN_SCANNER_WORKSPACE_CEILING_BYTES
            == NINLIL_DSS_WORKSPACE_CEILING_BYTES);
    }
    return 0;
}

int main(void)
{
    size_t i;
    int saw_structural_positive = 0;
    int saw_dsr2 = 0;

    REQUIRE(NINLIL_DSS_VECTOR_COUNT >= 30u);
    REQUIRE(NINLIL_DSS_WORKSPACE_CEILING_BYTES == 8192u);
    for (i = 0u; i < NINLIL_DSS_VECTOR_COUNT; ++i) {
        if (strcmp(ninlil_dss_vectors[i].kind, "structural_positive") == 0) {
            saw_structural_positive = 1;
        }
        if (strcmp(ninlil_dss_vectors[i].kind, "dsr2_ceiling") == 0) {
            saw_dsr2 = 1;
        }
        if (run_vector(&ninlil_dss_vectors[i]) != 0) {
            (void)fprintf(stderr, "structural bridge failed on %s\n",
                ninlil_dss_vectors[i].id);
            return 1;
        }
    }
    REQUIRE(saw_structural_positive != 0);
    REQUIRE(saw_dsr2 != 0);
    return 0;
}
