/*
 * Production scanner bridge: executes each domain-scan-v1 vector through the
 * production C scanner + scripted spy and compares status/adopted/counts/
 * state_after/reopen/close/mutation/port-trace against independent oracle
 * expectations. Fixture header is generated by tools/domain_scan_vector_gen.py
 * (no production C translation in the oracle).
 *
 * Mutation-zero gate: the production scripted spy (spy.mutation_calls and
 * ninlil_spy_assert_no_mutations) is authoritative. Oracle expected
 * mutation_calls is kept for schema symmetry but is always 0 in the independent
 * model and is not independent evidence of production mutation absence.
 */

#include "domain_store_scanner.h"
#include "scripted_storage_spy.h"

#include "domain_scan_vector_fixture.h"

#include <stdio.h>
#include <string.h>

#define REQUIRE(condition)                                                     \
    do {                                                                       \
        if (!(condition)) {                                                    \
            (void)fprintf(stderr, "%s:%d: %s failed: %s\n", __FILE__,          \
                __LINE__, current_id, #condition);                             \
            return 1;                                                          \
        }                                                                      \
    } while (0)

static const char *current_id = "";

static ninlil_status_t status_from_name(const char *name)
{
    if (strcmp(name, "OK") == 0) {
        return NINLIL_OK;
    }
    if (strcmp(name, "INVALID_ARGUMENT") == 0) {
        return NINLIL_E_INVALID_ARGUMENT;
    }
    if (strcmp(name, "UNSUPPORTED") == 0) {
        return NINLIL_E_UNSUPPORTED;
    }
    if (strcmp(name, "STORAGE") == 0) {
        return NINLIL_E_STORAGE;
    }
    if (strcmp(name, "STORAGE_CORRUPT") == 0) {
        return NINLIL_E_STORAGE_CORRUPT;
    }
    if (strcmp(name, "INVALID_STATE") == 0) {
        return NINLIL_E_INVALID_STATE;
    }
    if (strcmp(name, "WOULD_BLOCK") == 0) {
        return NINLIL_E_WOULD_BLOCK;
    }
    if (strcmp(name, "CAPACITY_EXHAUSTED") == 0) {
        return NINLIL_E_CAPACITY_EXHAUSTED;
    }
    return (ninlil_status_t)0xFFFFu;
}

static ninlil_domain_scan_state_t state_from_name(const char *name)
{
    if (strcmp(name, "IDLE") == 0) {
        return NINLIL_DOMAIN_SCAN_STATE_IDLE;
    }
    if (strcmp(name, "OPEN") == 0) {
        return NINLIL_DOMAIN_SCAN_STATE_OPEN;
    }
    if (strcmp(name, "EXHAUSTED") == 0) {
        return NINLIL_DOMAIN_SCAN_STATE_EXHAUSTED;
    }
    if (strcmp(name, "FAILED") == 0) {
        return NINLIL_DOMAIN_SCAN_STATE_FAILED;
    }
    if (strcmp(name, "DONE") == 0) {
        return NINLIL_DOMAIN_SCAN_STATE_DONE;
    }
    return (ninlil_domain_scan_state_t)0xFFu;
}

static ninlil_spy_op_t spy_op_from_name(const char *name)
{
    if (strcmp(name, "begin") == 0) {
        return NINLIL_SPY_OP_BEGIN;
    }
    if (strcmp(name, "iter_open") == 0) {
        return NINLIL_SPY_OP_ITER_OPEN;
    }
    if (strcmp(name, "iter_next") == 0) {
        return NINLIL_SPY_OP_ITER_NEXT;
    }
    if (strcmp(name, "rollback") == 0) {
        return NINLIL_SPY_OP_ROLLBACK;
    }
    return NINLIL_SPY_OP_COUNT;
}

static ninlil_spy_shape_t shape_from_name(const char *name)
{
    if (strcmp(name, "ok_null") == 0) {
        return NINLIL_SPY_SHAPE_OK_NULL;
    }
    if (strcmp(name, "error_with_handle") == 0) {
        return NINLIL_SPY_SHAPE_ERROR_WITH_HANDLE;
    }
    if (strcmp(name, "bts") == 0) {
        return NINLIL_SPY_SHAPE_BTS_LENGTHS;
    }
    if (strcmp(name, "not_found_poison") == 0) {
        return NINLIL_SPY_SHAPE_NOT_FOUND_POISON;
    }
    if (strcmp(name, "io_error") == 0) {
        return NINLIL_SPY_SHAPE_NATURAL;
    }
    if (strcmp(name, "unknown") == 0) {
        return NINLIL_SPY_SHAPE_NATURAL;
    }
    return NINLIL_SPY_SHAPE_NATURAL;
}

static ninlil_storage_status_t status_for_fault(const ninlil_dsf_fault_t *f)
{
    if (strcmp(f->shape, "bts") == 0) {
        return NINLIL_STORAGE_BUFFER_TOO_SMALL;
    }
    if (strcmp(f->shape, "not_found_poison") == 0) {
        return NINLIL_STORAGE_NOT_FOUND;
    }
    if (strcmp(f->shape, "io_error") == 0) {
        return NINLIL_STORAGE_IO_ERROR;
    }
    if (strcmp(f->shape, "unknown") == 0) {
        return (ninlil_storage_status_t)99u;
    }
    if (strcmp(f->shape, "ok_null") == 0) {
        return NINLIL_STORAGE_OK;
    }
    if (strcmp(f->shape, "error_with_handle") == 0) {
        return NINLIL_STORAGE_IO_ERROR;
    }
    return NINLIL_STORAGE_OK;
}

static const char *spy_op_name(ninlil_spy_op_t op)
{
    switch (op) {
    case NINLIL_SPY_OP_BEGIN:
        return "begin:READ_ONLY";
    case NINLIL_SPY_OP_ITER_OPEN:
        return "iter_open:prefix0";
    case NINLIL_SPY_OP_ITER_NEXT:
        return "iter_next";
    case NINLIL_SPY_OP_ITER_CLOSE:
        return "iter_close";
    case NINLIL_SPY_OP_ROLLBACK:
        return "rollback";
    case NINLIL_SPY_OP_CLOSE:
        return "close";
    default:
        return "other";
    }
}

static int run_vector(const ninlil_dsf_vector_t *vec)
{
    ninlil_scripted_storage_spy_t spy;
    ninlil_domain_scan_session_t session;
    ninlil_domain_scan_workspace_t workspace;
    ninlil_domain_scan_result_t result;
    ninlil_storage_handle_t handle;
    ninlil_storage_handle_t original_handle;
    const ninlil_storage_ops_t *ops;
    ninlil_status_t status = NINLIL_OK;
    size_t i;
    size_t mapped_trace = 0u;
    const char *mapped[NINLIL_DSF_MAX_TRACE];
    const char *last_op;

    current_id = vec->id;
    ninlil_spy_init(&spy);
    ops = ninlil_spy_ops(&spy);
    handle = ninlil_spy_open_handle(&spy);
    original_handle = handle;

    for (i = 0u; i < vec->row_count; ++i) {
        REQUIRE(ninlil_spy_add_row(&spy, vec->rows[i].key, vec->rows[i].key_length,
            vec->rows[i].value_length == 0u ? NULL : vec->rows[i].value,
            vec->rows[i].value_length));
    }
    for (i = 0u; i < vec->fault_count; ++i) {
        const ninlil_dsf_fault_t *f = &vec->faults[i];
        ninlil_spy_op_t op = spy_op_from_name(f->op);
        REQUIRE(op < NINLIL_SPY_OP_COUNT);
        REQUIRE(ninlil_spy_add_fault(&spy, op, f->on_call, status_for_fault(f),
            shape_from_name(f->shape), f->key_length, f->value_length));
    }

    ninlil_domain_scan_session_init(&session);
    (void)memset(&workspace, 0, sizeof(workspace));
    (void)memset(&result, 0, sizeof(result));

    for (i = 0u; i < vec->call_count; ++i) {
        const ninlil_dsf_call_t *call = &vec->calls[i];
        if (strcmp(call->op, "begin") == 0) {
            status = ninlil_domain_scan_begin(
                &session, ops, &handle, &workspace);
        } else if (strcmp(call->op, "advance") == 0) {
            status = ninlil_domain_scan_advance(&session, call->row_budget);
        } else if (strcmp(call->op, "finalize") == 0) {
            status = ninlil_domain_scan_finalize(&session, &result);
        } else if (strcmp(call->op, "abort") == 0) {
            status = ninlil_domain_scan_abort(&session, &result);
        } else {
            REQUIRE(0);
        }
    }

    REQUIRE(status == status_from_name(vec->expected.final_status));

    /* Normative state_after for every call sequence (including begin-only). */
    REQUIRE(session.state == state_from_name(vec->expected.state_after));

    last_op = vec->calls[vec->call_count - 1u].op;
    if (strcmp(last_op, "finalize") == 0 || strcmp(last_op, "abort") == 0) {
        REQUIRE(result.status == status);
        REQUIRE(result.adopted == vec->expected.adopted);
        REQUIRE(result.recognizable_future_seen
            == vec->expected.recognizable_future_seen);
        REQUIRE(result.family14_row_count == vec->expected.family14_row_count);
        REQUIRE(result.current_domain_key_count
            == vec->expected.current_domain_key_count);
        REQUIRE(result.ok_row_count == vec->expected.ok_row_count);
        REQUIRE(result.reopen_required == vec->expected.reopen_required);
        REQUIRE(session.reopen_required == vec->expected.reopen_required);
    } else if (strcmp(last_op, "begin") == 0 && status != NINLIL_OK) {
        REQUIRE(session.reopen_required == vec->expected.reopen_required);
    }

    REQUIRE(spy.close_calls == vec->expected.close_count);
    if (vec->expected.close_count != 0u) {
        /* Fence closed the original begin-time handle exactly once. */
        REQUIRE(ninlil_spy_close_count_for_handle(&spy, original_handle)
            == vec->expected.close_count);
        REQUIRE(handle == NULL);
        REQUIRE(session.original_handle_authority == 0u);
    } else if (strcmp(last_op, "finalize") == 0
        && vec->expected.adopted == 1u) {
        /* Successful adopt must not close the caller's original handle. */
        REQUIRE(handle == original_handle);
        REQUIRE(ninlil_spy_close_count_for_handle(&spy, original_handle) == 0u);
    }

    if (vec->expected.reopen_required != 0u) {
        REQUIRE(session.reopen_required == 1u);
        /*
         * Current shape-fence oracle vectors always leave the bound slot NULL
         * after fence (original still in slot at fence time). Foreign-slot
         * drift (slot rewritten mid-session; original closed, foreign left
         * untouched) is owned by direct C unit tests, not JSON vectors.
         */
        REQUIRE(handle == NULL);
    }

    /*
     * Mutation-zero: production spy is authoritative. Oracle expected
     * mutation_calls is schema symmetry (always 0); do not treat it as
     * independent production evidence.
     */
    REQUIRE(spy.mutation_calls == 0u);
    REQUIRE(ninlil_spy_assert_no_mutations(&spy));
    REQUIRE(vec->expected.mutation_calls == 0u);

    /* Map spy trace to oracle port_trace names (subset of ops). */
    for (i = 0u; i < spy.trace_count && mapped_trace < NINLIL_DSF_MAX_TRACE;
         ++i) {
        const char *name = spy_op_name(spy.trace[i].op);
        if (strcmp(name, "other") == 0) {
            continue;
        }
        mapped[mapped_trace++] = name;
    }
    REQUIRE(mapped_trace == vec->expected.port_trace_count);
    for (i = 0u; i < mapped_trace; ++i) {
        REQUIRE(strcmp(mapped[i], vec->expected.port_trace[i]) == 0);
    }
    return 0;
}

int main(void)
{
    size_t i;

    REQUIRE(NINLIL_DSF_VECTOR_COUNT == 18u);
    for (i = 0u; i < NINLIL_DSF_VECTOR_COUNT; ++i) {
        if (run_vector(&ninlil_dsf_vectors[i]) != 0) {
            (void)fprintf(stderr, "bridge failed on %s\n",
                ninlil_dsf_vectors[i].id);
            return 1;
        }
    }
    return 0;
}
