/*
 * D2-S5 production profiled-begin composition bridge: executes each
 * domain-scan-composition-v1 vector through ninlil_domain_scan_begin_profiled
 * + note_terminal_corrupt / exact_get / advance / finalize / abort and
 * compares per-call status, final status/adopted/counts/diagnostics/port-trace
 * against the independent oracle. Fixture is generated by
 * tools/domain_scan_composition_vector_gen.py (no production C translation).
 * Claims D2 / DSR1_SCAN / DSR2_ESP_BOUND complete only; not Stage 5/D3/D4/S6.
 */

#include "domain_store_scanner.h"
#include "scripted_storage_spy.h"

#include "domain_scan_composition_vector_fixture.h"

#include <stdio.h>
#include <string.h>

#define REQUIRE(condition)                                                     \
    do {                                                                       \
        if (!(condition)) {                                                    \
            (void)fprintf(stderr, "%s:%d: %s failed: %s\n", __FILE__,          \
                __LINE__, current_id, #condition);                             \
            return 1;                                                          \
        }                                                                      \
    } while (0)

static const char *current_id = "";

/* Bitmask for required kinds — bridge must observe the exact closed set. */
enum {
    KIND_BIT_BUDGET_1 = 1u << 0,
    KIND_BIT_BUDGET_64 = 1u << 1,
    KIND_BIT_SAME_SNAPSHOT_EXACT_GET = 1u << 2,
    KIND_BIT_RESTART_AFTER_ABORT = 1u << 3,
    KIND_BIT_RESTART_AFTER_FINALIZE = 1u << 4,
    KIND_BIT_RESTART_CHANGED_SNAPSHOT = 1u << 5,
    KIND_BIT_RESTART_AFTER_FAILED = 1u << 6,
    KIND_BIT_ROLLBACK_FAILURE_STICKY = 1u << 7,
    KIND_BIT_UNKNOWN_ROLLBACK_FENCE = 1u << 8,
    KIND_BIT_HANDLE_DRIFT_ORIGINAL = 1u << 9,
    KIND_BIT_FUTURE_THEN_NOTE = 1u << 10,
    KIND_BIT_EXHAUSTED_FUTURE_THEN_NOTE = 1u << 11,
    KIND_BIT_MISMATCH_THEN_NOTE = 1u << 12,
    KIND_BIT_STRUCTURAL_FUTURE_COMPOSITION = 1u << 13,
    KIND_BIT_STATE_GATE = 1u << 14,
    KIND_BIT_NOTE_THEN_REJECT = 1u << 15,
    KIND_BIT_NOTE_EXHAUSTED = 1u << 16,
    KIND_BIT_CLOSE_FENCE_ONCE = 1u << 17,
    KIND_BIT_MUTATION_ZERO = 1u << 18,
    KIND_BIT_DSR2_CEILING = 1u << 19,
    KIND_BIT_DSR2_SOURCE = 1u << 20,
    KIND_BIT_ALL_REQUIRED = (1u << 21) - 1u
};

static uint32_t kind_bit(const char *kind)
{
    if (strcmp(kind, "budget_1") == 0) {
        return KIND_BIT_BUDGET_1;
    }
    if (strcmp(kind, "budget_64") == 0) {
        return KIND_BIT_BUDGET_64;
    }
    if (strcmp(kind, "same_snapshot_exact_get") == 0) {
        return KIND_BIT_SAME_SNAPSHOT_EXACT_GET;
    }
    if (strcmp(kind, "restart_after_abort") == 0) {
        return KIND_BIT_RESTART_AFTER_ABORT;
    }
    if (strcmp(kind, "restart_after_finalize") == 0) {
        return KIND_BIT_RESTART_AFTER_FINALIZE;
    }
    if (strcmp(kind, "restart_changed_snapshot") == 0) {
        return KIND_BIT_RESTART_CHANGED_SNAPSHOT;
    }
    if (strcmp(kind, "restart_after_failed") == 0) {
        return KIND_BIT_RESTART_AFTER_FAILED;
    }
    if (strcmp(kind, "rollback_failure_sticky") == 0) {
        return KIND_BIT_ROLLBACK_FAILURE_STICKY;
    }
    if (strcmp(kind, "unknown_rollback_fence") == 0) {
        return KIND_BIT_UNKNOWN_ROLLBACK_FENCE;
    }
    if (strcmp(kind, "handle_drift_original") == 0) {
        return KIND_BIT_HANDLE_DRIFT_ORIGINAL;
    }
    if (strcmp(kind, "future_then_note") == 0) {
        return KIND_BIT_FUTURE_THEN_NOTE;
    }
    if (strcmp(kind, "exhausted_future_then_note") == 0) {
        return KIND_BIT_EXHAUSTED_FUTURE_THEN_NOTE;
    }
    if (strcmp(kind, "mismatch_then_note") == 0) {
        return KIND_BIT_MISMATCH_THEN_NOTE;
    }
    if (strcmp(kind, "structural_future_composition") == 0) {
        return KIND_BIT_STRUCTURAL_FUTURE_COMPOSITION;
    }
    if (strcmp(kind, "state_gate") == 0) {
        return KIND_BIT_STATE_GATE;
    }
    if (strcmp(kind, "note_then_reject") == 0) {
        return KIND_BIT_NOTE_THEN_REJECT;
    }
    if (strcmp(kind, "note_exhausted") == 0) {
        return KIND_BIT_NOTE_EXHAUSTED;
    }
    if (strcmp(kind, "close_fence_once") == 0) {
        return KIND_BIT_CLOSE_FENCE_ONCE;
    }
    if (strcmp(kind, "mutation_zero") == 0) {
        return KIND_BIT_MUTATION_ZERO;
    }
    if (strcmp(kind, "dsr2_ceiling") == 0) {
        return KIND_BIT_DSR2_CEILING;
    }
    if (strcmp(kind, "dsr2_source") == 0) {
        return KIND_BIT_DSR2_SOURCE;
    }
    return 0u;
}

static ninlil_status_t status_from_name(const char *name)
{
    if (strcmp(name, "OK") == 0) {
        return NINLIL_OK;
    }
    if (strcmp(name, "INVALID_ARGUMENT") == 0) {
        return NINLIL_E_INVALID_ARGUMENT;
    }
    if (strcmp(name, "UNSUPPORTED") == 0) {
        return NINLIL_E_UNSUPPORTED;
    }
    if (strcmp(name, "STORAGE") == 0) {
        return NINLIL_E_STORAGE;
    }
    if (strcmp(name, "STORAGE_CORRUPT") == 0) {
        return NINLIL_E_STORAGE_CORRUPT;
    }
    if (strcmp(name, "STORAGE_COMMIT_UNKNOWN") == 0) {
        return NINLIL_E_STORAGE_COMMIT_UNKNOWN;
    }
    if (strcmp(name, "INVALID_STATE") == 0) {
        return NINLIL_E_INVALID_STATE;
    }
    if (strcmp(name, "WOULD_BLOCK") == 0) {
        return NINLIL_E_WOULD_BLOCK;
    }
    if (strcmp(name, "CAPACITY_EXHAUSTED") == 0) {
        return NINLIL_E_CAPACITY_EXHAUSTED;
    }
    return (ninlil_status_t)0xFFFFu;
}

static ninlil_domain_scan_state_t state_from_name(const char *name)
{
    if (strcmp(name, "IDLE") == 0) {
        return NINLIL_DOMAIN_SCAN_STATE_IDLE;
    }
    if (strcmp(name, "OPEN") == 0) {
        return NINLIL_DOMAIN_SCAN_STATE_OPEN;
    }
    if (strcmp(name, "EXHAUSTED") == 0) {
        return NINLIL_DOMAIN_SCAN_STATE_EXHAUSTED;
    }
    if (strcmp(name, "FAILED") == 0) {
        return NINLIL_DOMAIN_SCAN_STATE_FAILED;
    }
    if (strcmp(name, "DONE") == 0) {
        return NINLIL_DOMAIN_SCAN_STATE_DONE;
    }
    return (ninlil_domain_scan_state_t)0xFFu;
}

static ninlil_spy_op_t spy_op_from_name(const char *name)
{
    if (strcmp(name, "begin") == 0) {
        return NINLIL_SPY_OP_BEGIN;
    }
    if (strcmp(name, "get") == 0) {
        return NINLIL_SPY_OP_GET;
    }
    if (strcmp(name, "iter_open") == 0) {
        return NINLIL_SPY_OP_ITER_OPEN;
    }
    if (strcmp(name, "iter_next") == 0) {
        return NINLIL_SPY_OP_ITER_NEXT;
    }
    if (strcmp(name, "rollback") == 0) {
        return NINLIL_SPY_OP_ROLLBACK;
    }
    return NINLIL_SPY_OP_COUNT;
}

static ninlil_spy_shape_t shape_from_name(const char *name)
{
    if (strcmp(name, "bts") == 0) {
        return NINLIL_SPY_SHAPE_BTS_LENGTHS;
    }
    if (strcmp(name, "unknown") == 0) {
        return NINLIL_SPY_SHAPE_NATURAL;
    }
    if (strcmp(name, "natural") == 0) {
        return NINLIL_SPY_SHAPE_NATURAL;
    }
    return NINLIL_SPY_SHAPE_NATURAL;
}

static ninlil_storage_status_t status_for_fault(const ninlil_dsc_fault_t *f)
{
    if (strcmp(f->shape, "unknown") == 0
        || strcmp(f->status, "UNKNOWN_RAW") == 0) {
        return (ninlil_storage_status_t)99u;
    }
    if (strcmp(f->status, "IO_ERROR") == 0) {
        return NINLIL_STORAGE_IO_ERROR;
    }
    if (strcmp(f->status, "BUSY") == 0) {
        return NINLIL_STORAGE_BUSY;
    }
    if (strcmp(f->status, "CORRUPT") == 0) {
        return NINLIL_STORAGE_CORRUPT;
    }
    if (strcmp(f->status, "UNSUPPORTED_SCHEMA") == 0) {
        return NINLIL_STORAGE_UNSUPPORTED_SCHEMA;
    }
    if (strcmp(f->status, "COMMIT_UNKNOWN") == 0) {
        return NINLIL_STORAGE_COMMIT_UNKNOWN;
    }
    if (strcmp(f->status, "NO_SPACE") == 0) {
        return NINLIL_STORAGE_NO_SPACE;
    }
    return NINLIL_STORAGE_OK;
}

/*
 * Map every Port trace operation. No "other" drop category: unexpected
 * put/erase/commit/open/capacity/unknown enum fails equality.
 */
static int map_spy_op_to_oracle_name(ninlil_spy_op_t op, const char **out_name)
{
    switch (op) {
    case NINLIL_SPY_OP_BEGIN:
        *out_name = "begin:READ_ONLY";
        return 1;
    case NINLIL_SPY_OP_GET:
        *out_name = "get";
        return 1;
    case NINLIL_SPY_OP_ITER_OPEN:
        *out_name = "iter_open:prefix0";
        return 1;
    case NINLIL_SPY_OP_ITER_NEXT:
        *out_name = "iter_next";
        return 1;
    case NINLIL_SPY_OP_ITER_CLOSE:
        *out_name = "iter_close";
        return 1;
    case NINLIL_SPY_OP_ROLLBACK:
        *out_name = "rollback";
        return 1;
    case NINLIL_SPY_OP_CLOSE:
        *out_name = "close";
        return 1;
    case NINLIL_SPY_OP_OPEN:
        *out_name = "open";
        return 1;
    case NINLIL_SPY_OP_PUT:
        *out_name = "put";
        return 1;
    case NINLIL_SPY_OP_ERASE:
        *out_name = "erase";
        return 1;
    case NINLIL_SPY_OP_CAPACITY:
        *out_name = "capacity";
        return 1;
    case NINLIL_SPY_OP_COMMIT:
        *out_name = "commit";
        return 1;
    default:
        *out_name = "unknown_enum";
        return 0;
    }
}

static void fill_candidate(
    ninlil_model_runtime_store_binding_t *out,
    const ninlil_dsc_binding_t *in)
{
    (void)memset(out, 0, sizeof(*out));
    out->storage_schema = in->storage_schema;
    out->role = (ninlil_role_t)in->role;
    out->environment = (ninlil_environment_t)in->environment;
    (void)memcpy(out->runtime_id.bytes, in->runtime_id, 16u);
    out->limits.max_services = in->max_services;
    out->limits.max_nonterminal_transactions =
        in->max_nonterminal_transactions;
    out->limits.max_targets_per_transaction =
        in->max_targets_per_transaction;
    out->limits.max_logical_payload_bytes = in->max_logical_payload_bytes;
    out->limits.max_durable_outbox_payload_bytes =
        in->max_durable_outbox_payload_bytes;
    out->limits.max_attempts_per_target_per_cycle =
        in->max_attempts_per_target_per_cycle;
    out->limits.max_cancel_attempts_per_transaction =
        in->max_cancel_attempts_per_transaction;
    out->limits.max_evidence_per_target = in->max_evidence_per_target;
    out->limits.max_retained_terminal_transactions =
        in->max_retained_terminal_transactions;
    out->limits.max_nonterminal_deliveries = in->max_nonterminal_deliveries;
    out->limits.max_event_spool_count = in->max_event_spool_count;
    out->limits.max_event_spool_bytes = in->max_event_spool_bytes;
    out->limits.max_result_cache_entries = in->max_result_cache_entries;
    out->limits.max_retained_dispositions = in->max_retained_dispositions;
    out->limits.max_ingress_per_step = in->max_ingress_per_step;
    out->limits.max_callbacks_per_step = in->max_callbacks_per_step;
    out->limits.max_state_transitions_per_step =
        in->max_state_transitions_per_step;
    out->limits.max_bearer_sends_per_step = in->max_bearer_sends_per_step;
    out->limits.max_deferred_tokens = in->max_deferred_tokens;
    out->terminal_retention_ms = in->terminal_retention_ms;
    out->result_cache_retention_ms = in->result_cache_retention_ms;
    out->observation_retention_ms = in->observation_retention_ms;
}

static int install_rows(
    ninlil_scripted_storage_spy_t *spy,
    const ninlil_dsc_row_t *rows,
    size_t row_count)
{
    size_t i;
    for (i = 0u; i < row_count; ++i) {
        if (!ninlil_spy_add_row(spy, rows[i].key, rows[i].key_length,
                rows[i].value_length == 0u ? NULL : rows[i].value,
                rows[i].value_length)) {
            return 0;
        }
    }
    return 1;
}

static int install_alt(
    ninlil_scripted_storage_spy_t *spy,
    const ninlil_dsc_vector_t *vec,
    const char *name)
{
    size_t i;
    for (i = 0u; i < vec->alt_count; ++i) {
        if (vec->alts[i].name != NULL
            && strcmp(vec->alts[i].name, name) == 0) {
            spy->row_count = 0u;
            return install_rows(spy, vec->alts[i].rows, vec->alts[i].row_count);
        }
    }
    return 0;
}

/* Active snapshot rows: alt if switched, else primary. */
static const ninlil_dsc_row_t *active_rows(
    const ninlil_dsc_vector_t *vec,
    const char *active_alt_name,
    size_t *out_count)
{
    size_t i;
    if (active_alt_name != NULL) {
        for (i = 0u; i < vec->alt_count; ++i) {
            if (vec->alts[i].name != NULL
                && strcmp(vec->alts[i].name, active_alt_name) == 0) {
                *out_count = vec->alts[i].row_count;
                return vec->alts[i].rows;
            }
        }
    }
    *out_count = vec->row_count;
    return vec->rows;
}

static int is_harness_op(const char *op)
{
    return strcmp(op, "session_init") == 0
        || strcmp(op, "use_rows") == 0
        || strcmp(op, "handle_drift") == 0;
}

static int is_restart_kind(const char *kind)
{
    return strcmp(kind, "restart_after_abort") == 0
        || strcmp(kind, "restart_after_finalize") == 0
        || strcmp(kind, "restart_changed_snapshot") == 0
        || strcmp(kind, "restart_after_failed") == 0;
}

static int run_vector(const ninlil_dsc_vector_t *vec)
{
    ninlil_scripted_storage_spy_t spy;
    ninlil_domain_scan_session_t session;
    ninlil_domain_scan_workspace_t workspace;
    ninlil_domain_scan_result_t result;
    ninlil_domain_scan_exact_get_result_t exact;
    ninlil_model_runtime_store_binding_t candidate;
    ninlil_storage_handle_t handle;
    ninlil_storage_handle_t original_handle;
    ninlil_storage_handle_t foreign_handle;
    static int foreign_token = 0x5A5A5A5A;
    const ninlil_storage_ops_t *ops;
    ninlil_status_t status = NINLIL_OK;
    size_t i;
    size_t mapped_trace = 0u;
    const char *mapped[NINLIL_DSC_MAX_TRACE];
    const char *last_op;
    const char *active_alt = NULL;
    int session_init_seen = 0;
    int post_restart_begin_seen = 0;
    int post_restart_first_advance_done = 0;
    size_t active_count = 0u;
    const ninlil_dsc_row_t *act_rows = NULL;

    /* same_snapshot_exact_get bridge snapshots */
    uint64_t snap_ok = 0u;
    uint64_t snap_family = 0u;
    uint64_t snap_current = 0u;
    uint32_t snap_iter_next = 0u;
    uint32_t snap_iter_open = 0u;
    uint8_t snap_has_previous = 0u;
    uint32_t snap_prev_len = 0u;
    uint8_t snap_prev[NINLIL_DOMAIN_SCAN_PREVIOUS_KEY_CAPACITY];
    uint32_t snap_get_calls = 0u;
    int exact_get_snap_armed = 0;

    current_id = vec->id;
    ninlil_spy_init(&spy);
    ops = ninlil_spy_ops(&spy);
    handle = ninlil_spy_open_handle(&spy);
    original_handle = handle;
    foreign_handle = (ninlil_storage_handle_t)&foreign_token;
    fill_candidate(&candidate, &vec->candidate);

    REQUIRE(install_rows(&spy, vec->rows, vec->row_count));
    for (i = 0u; i < vec->fault_count; ++i) {
        const ninlil_dsc_fault_t *f = &vec->faults[i];
        ninlil_spy_op_t op = spy_op_from_name(f->op);
        REQUIRE(op < NINLIL_SPY_OP_COUNT);
        REQUIRE(ninlil_spy_add_fault(&spy, op, f->on_call, status_for_fault(f),
            shape_from_name(f->shape), f->key_length, f->value_length));
    }

    ninlil_domain_scan_session_init(&session);
    (void)memset(&workspace, 0, sizeof(workspace));
    (void)memset(&result, 0, sizeof(result));
    (void)memset(&exact, 0, sizeof(exact));
    (void)memset(snap_prev, 0, sizeof(snap_prev));

    for (i = 0u; i < vec->call_count; ++i) {
        const ninlil_dsc_call_t *call = &vec->calls[i];
        uint64_t trace_before = spy.trace_count;
        REQUIRE(call->expected_status != NULL);

        if (strcmp(call->op, "session_init") == 0) {
            /* Legal only after DONE (or fresh IDLE). */
            REQUIRE(session.state == NINLIL_DOMAIN_SCAN_STATE_DONE
                || session.state == NINLIL_DOMAIN_SCAN_STATE_IDLE);
            ninlil_domain_scan_session_init(&session);
            (void)memset(&workspace, 0, sizeof(workspace));
            (void)memset(&result, 0, sizeof(result));
            if (handle == NULL) {
                handle = ninlil_spy_open_handle(&spy);
                original_handle = handle;
            }
            session_init_seen = 1;
            post_restart_begin_seen = 0;
            post_restart_first_advance_done = 0;
            REQUIRE(strcmp(call->expected_status, "VOID") == 0);
            REQUIRE(spy.trace_count == trace_before);
        } else if (strcmp(call->op, "use_rows") == 0) {
            REQUIRE(call->name != NULL);
            REQUIRE(session.state == NINLIL_DOMAIN_SCAN_STATE_IDLE);
            REQUIRE(install_alt(&spy, vec, call->name));
            active_alt = call->name;
            REQUIRE(strcmp(call->expected_status, "VOID") == 0);
            REQUIRE(spy.trace_count == trace_before);
        } else if (strcmp(call->op, "handle_drift") == 0) {
            /* Replace slot with foreign; scanner must close original only. */
            handle = foreign_handle;
            REQUIRE(strcmp(call->expected_status, "VOID") == 0);
            REQUIRE(spy.trace_count == trace_before);
        } else if (strcmp(call->op, "begin_profiled") == 0) {
            status = ninlil_domain_scan_begin_profiled(
                &session, ops, &handle, &workspace, &candidate);
            if (status == NINLIL_OK) {
                original_handle = session.bound_handle_value;
            }
            REQUIRE(status == status_from_name(call->expected_status));
            if (is_restart_kind(vec->kind) && session_init_seen
                && session.state == NINLIL_DOMAIN_SCAN_STATE_OPEN
                && status == NINLIL_OK) {
                /* After a prior session_init this is the post-restart begin. */
                post_restart_begin_seen = 1;
                post_restart_first_advance_done = 0;
            }
        } else if (strcmp(call->op, "advance") == 0) {
            status = ninlil_domain_scan_advance(&session, call->row_budget);
            REQUIRE(status == status_from_name(call->expected_status));
            if (is_restart_kind(vec->kind) && post_restart_begin_seen
                && !post_restart_first_advance_done
                && status == NINLIL_OK) {
                REQUIRE(call->row_budget == 1u);
                /* Counters reset to front-of-snapshot after fresh restart. */
                REQUIRE(session.ok_row_count == 1u);
                REQUIRE(session.has_previous == 1u);
                act_rows = active_rows(vec, active_alt, &active_count);
                REQUIRE(active_count >= 1u);
                REQUIRE(session.previous_key_length == act_rows[0].key_length);
                REQUIRE(memcmp(workspace.previous_key, act_rows[0].key,
                            act_rows[0].key_length)
                    == 0);
                post_restart_first_advance_done = 1;
            }
        } else if (strcmp(call->op, "exact_get") == 0) {
            ninlil_bytes_view_t key;
            key.data = call->key_length == 0u ? NULL : call->key;
            key.length = call->key_length;

            if (strcmp(vec->kind, "same_snapshot_exact_get") == 0
                && !exact_get_snap_armed
                && session.state == NINLIL_DOMAIN_SCAN_STATE_OPEN) {
                snap_ok = session.ok_row_count;
                snap_family = session.family14_row_count;
                snap_current = session.current_domain_key_count;
                snap_iter_next = spy.iter_next_calls;
                snap_iter_open = spy.iter_open_calls;
                snap_has_previous = session.has_previous;
                snap_prev_len = session.previous_key_length;
                (void)memcpy(snap_prev, workspace.previous_key,
                    sizeof(snap_prev));
                snap_get_calls = spy.get_calls;
                exact_get_snap_armed = 1;
            }

            status = ninlil_domain_scan_exact_get(&session, key, &exact);
            REQUIRE(status == status_from_name(call->expected_status));

            if (exact_get_snap_armed
                && strcmp(vec->kind, "same_snapshot_exact_get") == 0
                && status == NINLIL_OK) {
                REQUIRE(session.ok_row_count == snap_ok);
                REQUIRE(session.family14_row_count == snap_family);
                REQUIRE(session.current_domain_key_count == snap_current);
                REQUIRE(spy.iter_next_calls == snap_iter_next);
                REQUIRE(spy.iter_open_calls == snap_iter_open);
                REQUIRE(session.has_previous == snap_has_previous);
                REQUIRE(session.previous_key_length == snap_prev_len);
                REQUIRE(memcmp(workspace.previous_key, snap_prev,
                            sizeof(snap_prev))
                    == 0);
                REQUIRE(spy.get_calls == snap_get_calls + 1u);
                exact_get_snap_armed = 2; /* consumed success snapshot */
            }
        } else if (strcmp(call->op, "note_terminal_corrupt") == 0) {
            status = ninlil_domain_scan_note_terminal_corrupt(&session);
            REQUIRE(status == status_from_name(call->expected_status));
            /* note is Port 0 */
            REQUIRE(spy.trace_count == trace_before);
        } else if (strcmp(call->op, "finalize") == 0) {
            status = ninlil_domain_scan_finalize(&session, &result);
            REQUIRE(status == status_from_name(call->expected_status));
        } else if (strcmp(call->op, "abort") == 0) {
            status = ninlil_domain_scan_abort(&session, &result);
            REQUIRE(status == status_from_name(call->expected_status));
        } else {
            REQUIRE(0); /* unknown call op */
        }

        /* Post-note reject: Port 0 on INVALID_STATE advance/exact_get. */
        if (strcmp(vec->kind, "note_then_reject") == 0
            && (strcmp(call->op, "advance") == 0
                || strcmp(call->op, "exact_get") == 0)
            && strcmp(call->expected_status, "INVALID_STATE") == 0) {
            REQUIRE(status == NINLIL_E_INVALID_STATE);
            REQUIRE(spy.trace_count == trace_before);
        }

        if (is_harness_op(call->op)) {
            REQUIRE(strcmp(call->expected_status, "VOID") == 0);
        }
    }

    REQUIRE(status == status_from_name(vec->expected.final_status));
    REQUIRE(session.state == state_from_name(vec->expected.state_after));

    last_op = vec->calls[vec->call_count - 1u].op;
    if (strcmp(last_op, "finalize") == 0 || strcmp(last_op, "abort") == 0) {
        REQUIRE(result.status == status);
        REQUIRE(result.adopted == vec->expected.adopted);
        REQUIRE(result.recognizable_future_seen
            == vec->expected.recognizable_future_seen);
        REQUIRE(result.family14_row_count == vec->expected.family14_row_count);
        REQUIRE(result.current_domain_key_count
            == vec->expected.current_domain_key_count);
        REQUIRE(result.ok_row_count == vec->expected.ok_row_count);
        REQUIRE(result.profile_exact_active
            == vec->expected.profile_exact_active);
        REQUIRE(result.profile_mismatch == vec->expected.profile_mismatch);
        REQUIRE(result.future_profile_candidate
            == vec->expected.future_profile_candidate);
        REQUIRE(result.profile_get_present_mask
            == vec->expected.profile_get_present_mask);
        REQUIRE(result.family14_iter_seen_mask
            == vec->expected.family14_iter_seen_mask);
        REQUIRE(result.reopen_required == vec->expected.reopen_required);
    }

    REQUIRE(spy.close_calls == vec->expected.close_count);
    if (strcmp(vec->kind, "handle_drift_original") == 0) {
        REQUIRE(spy.close_calls == 1u);
        REQUIRE(ninlil_spy_close_count_for_handle(&spy, original_handle) == 1u);
        REQUIRE(ninlil_spy_close_count_for_handle(&spy, foreign_handle) == 0u);
        REQUIRE(handle == foreign_handle);
    }

    /* Mutation zero is independently asserted on every vector. */
    REQUIRE(spy.mutation_calls == 0u);
    REQUIRE(ninlil_spy_assert_no_mutations(&spy));
    REQUIRE(vec->expected.mutation_calls == 0u);
    REQUIRE(spy.iter_open_calls == vec->expected.iter_open_count);

    /* Full Port-trace equality: map every op; no drop of unknown category. */
    for (i = 0u; i < spy.trace_count; ++i) {
        const char *name = NULL;
        REQUIRE(mapped_trace < NINLIL_DSC_MAX_TRACE);
        REQUIRE(map_spy_op_to_oracle_name(spy.trace[i].op, &name));
        mapped[mapped_trace++] = name;
    }
    REQUIRE(mapped_trace == vec->expected.port_trace_count);
    for (i = 0u; i < mapped_trace; ++i) {
        REQUIRE(strcmp(mapped[i], vec->expected.port_trace[i]) == 0);
    }

    if (vec->expected.has_sticky_primary != 0u
        && (strcmp(last_op, "finalize") == 0
            || strcmp(last_op, "abort") == 0)) {
        REQUIRE(result.status
            == status_from_name(vec->expected.sticky_primary));
    }

    if (strcmp(vec->kind, "same_snapshot_exact_get") == 0) {
        REQUIRE(exact_get_snap_armed == 2);
    }

    if (is_restart_kind(vec->kind)) {
        REQUIRE(post_restart_first_advance_done != 0);
        /* Changed snapshot must complete with new front proven (not final only). */
        if (strcmp(vec->kind, "restart_changed_snapshot") == 0) {
            REQUIRE(status == NINLIL_E_UNSUPPORTED);
            REQUIRE(result.recognizable_future_seen == 1u);
            REQUIRE(result.adopted == 0u);
        }
    }

    if (strcmp(vec->kind, "dsr2_ceiling") == 0
        || strcmp(vec->kind, "dsr2_source") == 0) {
        REQUIRE(NINLIL_DSC_WORKSPACE_CEILING_BYTES == 8192u);
        REQUIRE(sizeof(ninlil_domain_scan_workspace_t)
            <= NINLIL_DSC_WORKSPACE_CEILING_BYTES);
        REQUIRE(NINLIL_DOMAIN_SCANNER_WORKSPACE_CEILING_BYTES
            == NINLIL_DSC_WORKSPACE_CEILING_BYTES);
        REQUIRE(sizeof(workspace.value) == 4096u);
        /* Single value buffer only: no second max-value array in workspace. */
        REQUIRE(sizeof(ninlil_domain_scan_workspace_t)
            < (size_t)8192u + 1u);
    }
    /* dsr2_source is not proved by the success-path clone alone; CTest also
     * runs domain_scan_dsr2_complete_gate (source + VLA). Bridge asserts
     * live sizeof / single buffer / mutation0 composition pieces here. */
    if (strcmp(vec->kind, "mutation_zero") == 0) {
        REQUIRE(spy.mutation_calls == 0u);
        REQUIRE(ninlil_spy_assert_no_mutations(&spy));
    }
    if (strcmp(vec->kind, "close_fence_once") == 0
        || strcmp(vec->kind, "unknown_rollback_fence") == 0
        || strcmp(vec->kind, "rollback_failure_sticky") == 0) {
        REQUIRE(spy.close_calls == 1u);
        REQUIRE(result.reopen_required == 1u);
    }
    if (strcmp(vec->kind, "future_then_note") == 0
        || strcmp(vec->kind, "exhausted_future_then_note") == 0
        || strcmp(vec->kind, "mismatch_then_note") == 0) {
        REQUIRE(status == NINLIL_E_STORAGE_CORRUPT);
        REQUIRE(result.adopted == 0u);
        if (strcmp(vec->kind, "mismatch_then_note") == 0) {
            REQUIRE(result.profile_mismatch == 1u);
        } else {
            REQUIRE(result.recognizable_future_seen == 1u);
        }
    }
    if (strcmp(vec->kind, "note_exhausted") == 0) {
        REQUIRE(status == NINLIL_E_STORAGE_CORRUPT);
        REQUIRE(result.adopted == 0u);
        REQUIRE(result.recognizable_future_seen == 0u);
    }
    return 0;
}

int main(void)
{
    size_t i;
    uint32_t kind_mask = 0u;

    REQUIRE(NINLIL_DSC_VECTOR_COUNT == 22u);
    REQUIRE(NINLIL_DSC_WORKSPACE_CEILING_BYTES == 8192u);
    REQUIRE(sizeof(ninlil_domain_scan_workspace_t)
        <= NINLIL_DOMAIN_SCANNER_WORKSPACE_CEILING_BYTES);

    for (i = 0u; i < NINLIL_DSC_VECTOR_COUNT; ++i) {
        uint32_t bit = kind_bit(ninlil_dsc_vectors[i].kind);
        REQUIRE(bit != 0u); /* unknown kind is a hard failure */
        kind_mask |= bit;
        if (run_vector(&ninlil_dsc_vectors[i]) != 0) {
            (void)fprintf(stderr, "composition bridge failed on %s\n",
                ninlil_dsc_vectors[i].id);
            return 1;
        }
    }
    /* Prove the exact required kind set, not a sample subset. */
    REQUIRE(kind_mask == KIND_BIT_ALL_REQUIRED);
    return 0;
}
