/*
 * D3-S2 production crossrow bridge (append-only sibling oracle):
 * executes the D3-S2 suffix vectors from domain-scan-crossrow-v1 through
 * real production begin_profiled_d3s2 + d3s2_drive + finalize/abort against
 * scripted Storage Port rows, then compares status, phase, count/binding
 * masks, sticky, adopted, D2 counters, mutation_calls=0, and exact Port
 * trace against the independent oracle fixture.
 *
 * Suffix inventory (not D3-S2 complete):
 *   - 6 Mode21..26 empty-carrier/empty-secondary COMPLETE smoke
 *   - Mode25 CUM total=1 + RECENT C1 + true ANCHOR COMPLETE success
 *   - Mode25 RECENT-without-CUM BIND carrier-ABSENT STORAGE_CORRUPT (note)
 *   - Mode26 ES resume=1 + MANAGEMENT RESUME + true ANCHOR COMPLETE success
 *   - Mode26 MANAGEMENT-without-ES BIND carrier-ABSENT STORAGE_CORRUPT (note)
 *   - Mode24 RC reply_count=1 + RR RECEIPT + true DELIVERY COMPLETE success
 *   - Mode24 RR-without-RC BIND carrier-ABSENT STORAGE_CORRUPT (note)
 *   - Mode23 TX STATE + ANCHOR + EVIDENCE slots 0..L equation COMPLETE success
 *   - Mode23 EVIDENCE-without-STATE BIND carrier-ABSENT STORAGE_CORRUPT (note)
 *   - Mode22 RC app=1 + DLV-owned ATTEMPT + true DELIVERY COMPLETE success
 *   - Mode22 ATTEMPT-without-RC BIND carrier-ABSENT STORAGE_CORRUPT (note)
 *   - Mode21 STATE cum=1 + TX ATT + AII + true ANCHOR COMPLETE success
 *   - Mode21 ATT-without-AII (CP PRESENT) BIND INDEX pair-ABSENT CORRUPT
 *   - P0-A Mode25 two-owner SHA RETRY interleave + dual CUM carrier COMPLETE
 *
 * Fixture is generated by tools/domain_scan_crossrow_d3s2_vector_gen.py
 * emit-c-fixture (no production C translation / no manual expected values).
 * Does NOT #include production unit-test .c sources.
 * Does NOT claim full D3-S2 oracle complete.
 * Stage5 D3 remains unbound. D3-S1 94-vector bridge is separate.
 */

#include "domain_store_d3s2.h"
#include "domain_store_scanner.h"
#include "scripted_storage_spy.h"

#include "domain_scan_crossrow_vector_fixture.h"

#include <stdio.h>
#include <string.h>

#define REQUIRE(condition)                                                     \
    do {                                                                       \
        if (!(condition)) {                                                    \
            (void)fprintf(stderr, "%s:%d: %s failed: %s\n", __FILE__,          \
                __LINE__, current_id, #condition);                             \
            return 1;                                                          \
        }                                                                      \
    } while (0)

static const char *current_id = "";

static ninlil_status_t status_from_name(const char *name)
{
    if (strcmp(name, "OK") == 0) {
        return NINLIL_OK;
    }
    if (strcmp(name, "INVALID_ARGUMENT") == 0) {
        return NINLIL_E_INVALID_ARGUMENT;
    }
    if (strcmp(name, "UNSUPPORTED") == 0) {
        return NINLIL_E_UNSUPPORTED;
    }
    if (strcmp(name, "STORAGE") == 0) {
        return NINLIL_E_STORAGE;
    }
    if (strcmp(name, "STORAGE_CORRUPT") == 0) {
        return NINLIL_E_STORAGE_CORRUPT;
    }
    if (strcmp(name, "STORAGE_COMMIT_UNKNOWN") == 0) {
        return NINLIL_E_STORAGE_COMMIT_UNKNOWN;
    }
    if (strcmp(name, "INVALID_STATE") == 0) {
        return NINLIL_E_INVALID_STATE;
    }
    if (strcmp(name, "WOULD_BLOCK") == 0) {
        return NINLIL_E_WOULD_BLOCK;
    }
    if (strcmp(name, "CAPACITY_EXHAUSTED") == 0) {
        return NINLIL_E_CAPACITY_EXHAUSTED;
    }
    return (ninlil_status_t)0xFFFFu;
}

static ninlil_domain_scan_state_t state_from_name(const char *name)
{
    if (strcmp(name, "IDLE") == 0) {
        return NINLIL_DOMAIN_SCAN_STATE_IDLE;
    }
    if (strcmp(name, "OPEN") == 0) {
        return NINLIL_DOMAIN_SCAN_STATE_OPEN;
    }
    if (strcmp(name, "EXHAUSTED") == 0) {
        return NINLIL_DOMAIN_SCAN_STATE_EXHAUSTED;
    }
    if (strcmp(name, "FAILED") == 0) {
        return NINLIL_DOMAIN_SCAN_STATE_FAILED;
    }
    if (strcmp(name, "DONE") == 0) {
        return NINLIL_DOMAIN_SCAN_STATE_DONE;
    }
    return (ninlil_domain_scan_state_t)0xFFu;
}

static ninlil_spy_op_t spy_op_from_name(const char *name)
{
    if (strcmp(name, "begin") == 0) {
        return NINLIL_SPY_OP_BEGIN;
    }
    if (strcmp(name, "get") == 0) {
        return NINLIL_SPY_OP_GET;
    }
    if (strcmp(name, "iter_open") == 0) {
        return NINLIL_SPY_OP_ITER_OPEN;
    }
    if (strcmp(name, "iter_next") == 0) {
        return NINLIL_SPY_OP_ITER_NEXT;
    }
    if (strcmp(name, "rollback") == 0) {
        return NINLIL_SPY_OP_ROLLBACK;
    }
    return NINLIL_SPY_OP_COUNT;
}

static ninlil_spy_shape_t shape_from_name(const char *name)
{
    if (strcmp(name, "bts") == 0) {
        return NINLIL_SPY_SHAPE_BTS_LENGTHS;
    }
    if (strcmp(name, "unknown") == 0) {
        return NINLIL_SPY_SHAPE_NATURAL;
    }
    if (strcmp(name, "natural") == 0) {
        return NINLIL_SPY_SHAPE_NATURAL;
    }
    return NINLIL_SPY_SHAPE_NATURAL;
}

static ninlil_storage_status_t status_for_fault(const ninlil_d3s2_fault_t *f)
{
    if (strcmp(f->shape, "unknown") == 0
        || strcmp(f->status, "UNKNOWN_RAW") == 0) {
        return (ninlil_storage_status_t)99u;
    }
    if (strcmp(f->status, "IO_ERROR") == 0) {
        return NINLIL_STORAGE_IO_ERROR;
    }
    if (strcmp(f->status, "BUSY") == 0) {
        return NINLIL_STORAGE_BUSY;
    }
    if (strcmp(f->status, "CORRUPT") == 0) {
        return NINLIL_STORAGE_CORRUPT;
    }
    if (strcmp(f->status, "UNSUPPORTED_SCHEMA") == 0) {
        return NINLIL_STORAGE_UNSUPPORTED_SCHEMA;
    }
    if (strcmp(f->status, "COMMIT_UNKNOWN") == 0) {
        return NINLIL_STORAGE_COMMIT_UNKNOWN;
    }
    if (strcmp(f->status, "NO_SPACE") == 0) {
        return NINLIL_STORAGE_NO_SPACE;
    }
    return NINLIL_STORAGE_OK;
}

static int map_spy_op_to_oracle_name(ninlil_spy_op_t op, const char **out_name)
{
    switch (op) {
    case NINLIL_SPY_OP_BEGIN:
        *out_name = "begin:READ_ONLY";
        return 1;
    case NINLIL_SPY_OP_GET:
        *out_name = "get";
        return 1;
    case NINLIL_SPY_OP_ITER_OPEN:
        *out_name = "iter_open:prefix0";
        return 1;
    case NINLIL_SPY_OP_ITER_NEXT:
        *out_name = "iter_next";
        return 1;
    case NINLIL_SPY_OP_ITER_CLOSE:
        *out_name = "iter_close";
        return 1;
    case NINLIL_SPY_OP_ROLLBACK:
        *out_name = "rollback";
        return 1;
    case NINLIL_SPY_OP_CLOSE:
        *out_name = "close";
        return 1;
    case NINLIL_SPY_OP_OPEN:
        *out_name = "open";
        return 1;
    case NINLIL_SPY_OP_PUT:
        *out_name = "put";
        return 1;
    case NINLIL_SPY_OP_ERASE:
        *out_name = "erase";
        return 1;
    case NINLIL_SPY_OP_CAPACITY:
        *out_name = "capacity";
        return 1;
    case NINLIL_SPY_OP_COMMIT:
        *out_name = "commit";
        return 1;
    default:
        *out_name = "unknown_enum";
        return 0;
    }
}

/*
 * Count S2 peer/FOCUS/BIND exact_gets from Port-trace: gets after the first
 * iter_open. Baseline profile gate (17 gets before any iter_open) is excluded
 * without magic subtraction from spy totals — the begin/baseline boundary is
 * the first iter_open in the mapped oracle-equivalent trace.
 */
static uint64_t count_peer_gets_from_trace(
    const char *const *mapped, size_t mapped_count)
{
    uint64_t peer = 0u;
    int after_iter_open = 0;
    size_t i;

    for (i = 0u; i < mapped_count; ++i) {
        if (strcmp(mapped[i], "begin:READ_ONLY") == 0) {
            after_iter_open = 0;
        } else if (strcmp(mapped[i], "iter_open:prefix0") == 0) {
            after_iter_open = 1;
        } else if (after_iter_open != 0 && strcmp(mapped[i], "get") == 0) {
            peer += 1u;
        }
    }
    return peer;
}

static void fill_candidate(
    ninlil_model_runtime_store_binding_t *out,
    const ninlil_d3s2_binding_t *in)
{
    (void)memset(out, 0, sizeof(*out));
    out->storage_schema = in->storage_schema;
    out->role = (ninlil_role_t)in->role;
    out->environment = (ninlil_environment_t)in->environment;
    (void)memcpy(out->runtime_id.bytes, in->runtime_id, 16u);
    out->limits.max_services = in->max_services;
    out->limits.max_nonterminal_transactions =
        in->max_nonterminal_transactions;
    out->limits.max_targets_per_transaction =
        in->max_targets_per_transaction;
    out->limits.max_logical_payload_bytes = in->max_logical_payload_bytes;
    out->limits.max_durable_outbox_payload_bytes =
        in->max_durable_outbox_payload_bytes;
    out->limits.max_attempts_per_target_per_cycle =
        in->max_attempts_per_target_per_cycle;
    out->limits.max_cancel_attempts_per_transaction =
        in->max_cancel_attempts_per_transaction;
    out->limits.max_evidence_per_target = in->max_evidence_per_target;
    out->limits.max_retained_terminal_transactions =
        in->max_retained_terminal_transactions;
    out->limits.max_nonterminal_deliveries = in->max_nonterminal_deliveries;
    out->limits.max_event_spool_count = in->max_event_spool_count;
    out->limits.max_event_spool_bytes = in->max_event_spool_bytes;
    out->limits.max_result_cache_entries = in->max_result_cache_entries;
    out->limits.max_retained_dispositions = in->max_retained_dispositions;
    out->limits.max_ingress_per_step = in->max_ingress_per_step;
    out->limits.max_callbacks_per_step = in->max_callbacks_per_step;
    out->limits.max_state_transitions_per_step =
        in->max_state_transitions_per_step;
    out->limits.max_bearer_sends_per_step = in->max_bearer_sends_per_step;
    out->limits.max_deferred_tokens = in->max_deferred_tokens;
    out->terminal_retention_ms = in->terminal_retention_ms;
    out->result_cache_retention_ms = in->result_cache_retention_ms;
    out->observation_retention_ms = in->observation_retention_ms;
}

static int install_rows(
    ninlil_scripted_storage_spy_t *spy,
    const ninlil_d3s2_row_t *rows,
    size_t row_count)
{
    size_t i;
    for (i = 0u; i < row_count; ++i) {
        if (!ninlil_spy_add_row(spy, rows[i].key, rows[i].key_length,
                rows[i].value_length == 0u ? NULL : rows[i].value,
                rows[i].value_length)) {
            return 0;
        }
    }
    return 1;
}

static int run_vector(const ninlil_d3s2_vector_t *vec)
{
    ninlil_scripted_storage_spy_t spy;
    ninlil_domain_scan_session_t session;
    ninlil_domain_scan_workspace_t workspace;
    ninlil_domain_scan_d3s2_context_t d3s2_context;
    ninlil_domain_scan_result_t result;
    ninlil_model_runtime_store_binding_t candidate;
    ninlil_storage_handle_t handle;
    const ninlil_storage_ops_t *ops;
    ninlil_status_t status = NINLIL_OK;
    ninlil_status_t expected_final;
    size_t i;
    size_t mapped_trace = 0u;
    const char *mapped[NINLIL_D3S2_MAX_TRACE];
    const char *last_op;
    uint32_t begin_calls_seen = 0u;
    int expect_complete;
    uint64_t observed_get_total;
    uint64_t observed_peer_gets;
    uint64_t baseline_gets;

    current_id = vec->id;
    expected_final = status_from_name(vec->expected.final_status);
    expect_complete =
        (vec->expected.phase == NINLIL_DOMAIN_SCAN_D3S2_PHASE_COMPLETE);

    ninlil_spy_init(&spy);
    ops = ninlil_spy_ops(&spy);
    handle = ninlil_spy_open_handle(&spy);
    fill_candidate(&candidate, &vec->candidate);

    REQUIRE(install_rows(&spy, vec->rows, vec->row_count));
    for (i = 0u; i < vec->fault_count; ++i) {
        const ninlil_d3s2_fault_t *f = &vec->faults[i];
        ninlil_spy_op_t op = spy_op_from_name(f->op);
        REQUIRE(op < NINLIL_SPY_OP_COUNT);
        REQUIRE(ninlil_spy_add_fault(&spy, op, f->on_call, status_for_fault(f),
            shape_from_name(f->shape), f->key_length, f->value_length));
    }

    ninlil_domain_scan_session_init(&session);
    (void)memset(&workspace, 0, sizeof(workspace));
    (void)memset(&d3s2_context, 0, sizeof(d3s2_context));
    (void)memset(&result, 0, sizeof(result));

    for (i = 0u; i < vec->call_count; ++i) {
        const ninlil_d3s2_call_t *call = &vec->calls[i];
        uint64_t trace_before = spy.trace_count;
        REQUIRE(call->expected_status != NULL);

        if (strcmp(call->op, "begin_profiled_d3s2") == 0) {
            ninlil_domain_scan_d3s2_context_t *ctx_arg = &d3s2_context;
            if (call->context != NULL
                && strcmp(call->context, "null") == 0) {
                ctx_arg = NULL;
            } else if (call->context != NULL
                && strcmp(call->context, "alias_session") == 0) {
                ctx_arg =
                    (ninlil_domain_scan_d3s2_context_t *)(void *)&session;
            }
            status = ninlil_domain_scan_begin_profiled_d3s2(
                &session, ops, &handle, &workspace, &candidate, call->mode,
                ctx_arg);
            REQUIRE(status == status_from_name(call->expected_status));
            if (status == NINLIL_OK) {
                /* bound_d3_context / bound_d3s2_context are a union; kind is
                 * the exclusive discriminator (dual-bound forbidden). */
                REQUIRE(session.bound_d3_kind == NINLIL_DOMAIN_SCAN_D3_KIND_S2);
                REQUIRE(session.bound_d3s2_context == &d3s2_context);
                REQUIRE(d3s2_context.focus_mode == call->mode);
                REQUIRE(d3s2_context.focus_mode == vec->mode);
                begin_calls_seen += 1u;
            } else {
                REQUIRE(spy.trace_count == trace_before);
            }
        } else if (strcmp(call->op, "d3s2_drive") == 0) {
            status = ninlil_domain_scan_d3s2_drive(&session, call->row_budget);
            REQUIRE(status == status_from_name(call->expected_status));
        } else if (strcmp(call->op, "finalize") == 0) {
            status = ninlil_domain_scan_finalize(&session, &result);
            REQUIRE(status == status_from_name(call->expected_status));
        } else if (strcmp(call->op, "abort") == 0) {
            status = ninlil_domain_scan_abort(&session, &result);
            REQUIRE(status == status_from_name(call->expected_status));
        } else {
            REQUIRE(0);
        }
    }

    REQUIRE(begin_calls_seen == 1u);
    REQUIRE(status == expected_final);
    REQUIRE(session.state == state_from_name(vec->expected.state_after));

    last_op = vec->calls[vec->call_count - 1u].op;
    if (strcmp(last_op, "finalize") == 0 || strcmp(last_op, "abort") == 0) {
        REQUIRE(result.status == status);
        REQUIRE(result.adopted == vec->expected.adopted);
        REQUIRE(result.recognizable_future_seen
            == vec->expected.recognizable_future_seen);
        REQUIRE(result.family14_row_count == vec->expected.family14_row_count);
        REQUIRE(result.current_domain_key_count
            == vec->expected.current_domain_key_count);
        REQUIRE(result.ok_row_count == vec->expected.ok_row_count);
        REQUIRE(result.profile_exact_active
            == vec->expected.profile_exact_active);
        REQUIRE(result.profile_mismatch == vec->expected.profile_mismatch);
        REQUIRE(result.future_profile_candidate
            == vec->expected.future_profile_candidate);
        REQUIRE(result.profile_get_present_mask
            == vec->expected.profile_get_present_mask);
        REQUIRE(result.family14_iter_seen_mask
            == vec->expected.family14_iter_seen_mask);
        REQUIRE(result.reopen_required == vec->expected.reopen_required);
    }

    /* Phase / masks / sticky retained on context after finalize/abort. */
    REQUIRE(d3s2_context.phase == vec->expected.phase);
    REQUIRE(d3s2_context.count_complete_mask
        == vec->expected.count_complete_mask);
    REQUIRE(d3s2_context.binding_complete_mask
        == vec->expected.binding_complete_mask);
    REQUIRE(d3s2_context.flags == vec->expected.flags);
    REQUIRE(d3s2_context.focus_mode == vec->mode);
    REQUIRE((d3s2_context.flags & NINLIL_DOMAIN_SCAN_D3S2_FLAG_BASELINE_DONE)
        != 0u);

    if (expect_complete) {
        REQUIRE(d3s2_context.phase == NINLIL_DOMAIN_SCAN_D3S2_PHASE_COMPLETE);
        REQUIRE(
            (d3s2_context.flags & NINLIL_DOMAIN_SCAN_D3S2_FLAG_COMPLETE_READY)
            != 0u);
        REQUIRE(d3s2_context.binding_complete_mask
            == ninlil_domain_scan_d3s2_required_binding_mask(vec->mode));
        REQUIRE(session.has_sticky_primary == 0u);
        REQUIRE(vec->expected.has_sticky_primary == 0u);
        REQUIRE(vec->expected.adopted == 1u);
    } else {
        REQUIRE(d3s2_context.phase == NINLIL_DOMAIN_SCAN_D3S2_PHASE_FAILED);
        REQUIRE(
            (d3s2_context.flags & NINLIL_DOMAIN_SCAN_D3S2_FLAG_COMPLETE_READY)
            == 0u);
        REQUIRE(session.has_sticky_primary != 0u);
        REQUIRE(vec->expected.has_sticky_primary != 0u);
        REQUIRE(session.sticky_primary
            == status_from_name(vec->expected.sticky_primary));
        REQUIRE(vec->expected.adopted == 0u);
    }

    REQUIRE(spy.close_calls == vec->expected.close_count);
    REQUIRE(spy.mutation_calls == 0u);
    REQUIRE(ninlil_spy_assert_no_mutations(&spy));
    REQUIRE(vec->expected.mutation_calls == 0u);
    REQUIRE(spy.iter_open_calls == vec->expected.iter_open_count);
    REQUIRE(spy.begin_calls == 1u);

    /* Full Port-trace equality (independent oracle; not dumped from prod). */
    for (i = 0u; i < spy.trace_count; ++i) {
        const char *name = NULL;
        REQUIRE(mapped_trace < NINLIL_D3S2_MAX_TRACE);
        REQUIRE(map_spy_op_to_oracle_name(spy.trace[i].op, &name));
        mapped[mapped_trace++] = name;
    }
    if (mapped_trace != vec->expected.port_trace_count) {
        (void)fprintf(stderr,
            "%s: port_trace count got %zu want %zu\n", current_id,
            mapped_trace, vec->expected.port_trace_count);
        for (i = 0u; i < mapped_trace && i < 64u; ++i) {
            (void)fprintf(stderr, "  got[%zu]=%s\n", i, mapped[i]);
        }
        for (i = 0u; i < vec->expected.port_trace_count && i < 64u; ++i) {
            (void)fprintf(stderr, "  want[%zu]=%s\n", i,
                vec->expected.port_trace[i]);
        }
        return 1;
    }
    for (i = 0u; i < mapped_trace; ++i) {
        if (strcmp(mapped[i], vec->expected.port_trace[i]) != 0) {
            (void)fprintf(stderr,
                "%s: port_trace[%zu] got=%s want=%s\n", current_id, i,
                mapped[i], vec->expected.port_trace[i]);
            return 1;
        }
    }

    /* Exact get counts from production spy + port-trace derivation.
     * total Port gets == spy.get_calls; peer gets = gets after first
     * iter_open (baseline profile 17 excluded via begin/baseline boundary). */
    observed_get_total = 0u;
    baseline_gets = 0u;
    {
        int after_iter_open = 0;
        for (i = 0u; i < mapped_trace; ++i) {
            if (strcmp(mapped[i], "get") == 0) {
                observed_get_total += 1u;
                if (after_iter_open == 0) {
                    baseline_gets += 1u;
                }
            } else if (strcmp(mapped[i], "iter_open:prefix0") == 0) {
                after_iter_open = 1;
            } else if (strcmp(mapped[i], "begin:READ_ONLY") == 0) {
                after_iter_open = 0;
            }
        }
    }
    REQUIRE(spy.get_calls == (uint32_t)observed_get_total);
    observed_peer_gets = count_peer_gets_from_trace(mapped, mapped_trace);
    REQUIRE(observed_peer_gets + baseline_gets == observed_get_total);
    REQUIRE(baseline_gets == 17u);
    REQUIRE(observed_peer_gets == vec->expected.d3_peer_get_count);
    /* Production spy total minus rigorously derived baseline equals peer. */
    REQUIRE((uint64_t)spy.get_calls - baseline_gets
        == vec->expected.d3_peer_get_count);

    return 0;
}

int main(void)
{
    size_t i;
    size_t smoke_n = 0u;
    size_t mode25_n = 0u;
    size_t mode26_n = 0u;
    size_t mode24_n = 0u;
    size_t mode23_n = 0u;
    size_t mode22_n = 0u;
    size_t mode21_n = 0u;
    size_t p0a_n = 0u;

    /* Both pins live in the shared append-only fixture. */
    REQUIRE(NINLIL_D3S1_VECTOR_COUNT == 94u);
    REQUIRE(NINLIL_D3S2_VECTOR_COUNT == 19u);
    REQUIRE(NINLIL_D3S1_WORKSPACE_CEILING_BYTES == 8192u);
    REQUIRE(sizeof(ninlil_domain_scan_workspace_t)
        <= NINLIL_DOMAIN_SCANNER_WORKSPACE_CEILING_BYTES);
    REQUIRE(sizeof(ninlil_domain_scan_d3s2_context_t)
        == NINLIL_DOMAIN_SCAN_D3S2_CONTEXT_SIZE_BYTES);
    REQUIRE(_Alignof(ninlil_domain_scan_d3s2_context_t) == 1);

    for (i = 0u; i < NINLIL_D3S2_VECTOR_COUNT; ++i) {
        REQUIRE(ninlil_d3s2_vectors[i].id != NULL);
        REQUIRE(ninlil_d3s2_vectors[i].kind != NULL);
        REQUIRE(ninlil_d3s2_vectors[i].kind[0] != '\0');
        REQUIRE(ninlil_d3s2_vectors[i].mode >= 21u
            && ninlil_d3s2_vectors[i].mode <= 26u);

        if (i < 6u) {
            /* First six remain Mode21..26 empty-carrier smoke, one mode each. */
            REQUIRE(ninlil_d3s2_vectors[i].mode == (uint8_t)(21u + i));
            smoke_n += 1u;
        } else if (i < 8u) {
            REQUIRE(ninlil_d3s2_vectors[i].mode == 25u);
            mode25_n += 1u;
        } else if (i < 10u) {
            REQUIRE(ninlil_d3s2_vectors[i].mode == 26u);
            mode26_n += 1u;
        } else if (i < 12u) {
            REQUIRE(ninlil_d3s2_vectors[i].mode == 24u);
            mode24_n += 1u;
        } else if (i < 14u) {
            REQUIRE(ninlil_d3s2_vectors[i].mode == 23u);
            mode23_n += 1u;
        } else if (i < 16u) {
            REQUIRE(ninlil_d3s2_vectors[i].mode == 22u);
            mode22_n += 1u;
        } else if (i < 18u) {
            REQUIRE(ninlil_d3s2_vectors[i].mode == 21u);
            mode21_n += 1u;
        } else {
            /* P0-A: Mode25 multi-owner SHA interleave + dual carrier. */
            REQUIRE(ninlil_d3s2_vectors[i].mode == 25u);
            REQUIRE(strcmp(ninlil_d3s2_vectors[i].id,
                        "D3S2_M25_TWO_OWNER_SHA_INTERLEAVE_DUAL_CARRIER_OK")
                == 0);
            REQUIRE(strcmp(ninlil_d3s2_vectors[i].kind,
                        "mode25_two_owner_sha_interleave_dual_carrier_ok")
                == 0);
            p0a_n += 1u;
        }

        if (run_vector(&ninlil_d3s2_vectors[i]) != 0) {
            (void)fprintf(stderr,
                "d3s2 crossrow bridge failed on %s kind=%s mode=%u\n",
                ninlil_d3s2_vectors[i].id, ninlil_d3s2_vectors[i].kind,
                (unsigned)ninlil_d3s2_vectors[i].mode);
            return 1;
        }
    }
    REQUIRE(smoke_n == 6u);
    REQUIRE(mode25_n == 2u);
    REQUIRE(mode26_n == 2u);
    REQUIRE(mode24_n == 2u);
    REQUIRE(mode23_n == 2u);
    REQUIRE(mode22_n == 2u);
    REQUIRE(mode21_n == 2u);
    REQUIRE(p0a_n == 1u);
    return 0;
}
