/*
 * D3-S2 P2-A DSD1 multi-session composition production bridge
 * (docs/17 §18.13.16).
 *
 * Executes the independent sibling oracle
 *   spec/vectors/domain-scan-dsd1-composition-v1.json
 * through real production private APIs:
 *   begin_profiled_d3s1 / advance / finalize   (modes 11/14/17/19)
 *   begin_profiled_d3s2 / d3s2_drive / finalize (modes 22/23/24)
 *
 * Same D1-valid fixture rows for every session; each session is a fresh
 * scanner session + independent baseline + single READ_ONLY txn + DONE
 * cleanup before the next. Dual-bound S1+S2 is never installed. Mode 28
 * is absent. mutation_calls=0. Does not claim D3-S2 overall complete,
 * Stage 5, D4, public Runtime, ESP-IDF, or hardware.
 *
 * Fixture generated by tools/domain_scan_dsd1_composition_vector_gen.py
 * emit-c-fixture (no production C translation).
 */

#include "domain_store_d3s1.h"
#include "domain_store_d3s2.h"
#include "domain_store_scanner.h"
#include "scripted_storage_spy.h"

#include "domain_scan_dsd1_composition_vector_fixture.h"

#include <stdio.h>
#include <string.h>

#define REQUIRE(condition)                                                     \
    do {                                                                       \
        if (!(condition)) {                                                    \
            (void)fprintf(stderr, "%s:%d: %s failed: %s\n", __FILE__,          \
                __LINE__, current_id, #condition);                             \
            return 1;                                                          \
        }                                                                      \
    } while (0)

static const char *current_id = "";

static ninlil_status_t status_from_name(const char *name)
{
    if (strcmp(name, "OK") == 0) {
        return NINLIL_OK;
    }
    if (strcmp(name, "INVALID_ARGUMENT") == 0) {
        return NINLIL_E_INVALID_ARGUMENT;
    }
    if (strcmp(name, "UNSUPPORTED") == 0) {
        return NINLIL_E_UNSUPPORTED;
    }
    if (strcmp(name, "STORAGE") == 0) {
        return NINLIL_E_STORAGE;
    }
    if (strcmp(name, "STORAGE_CORRUPT") == 0) {
        return NINLIL_E_STORAGE_CORRUPT;
    }
    if (strcmp(name, "STORAGE_COMMIT_UNKNOWN") == 0) {
        return NINLIL_E_STORAGE_COMMIT_UNKNOWN;
    }
    if (strcmp(name, "INVALID_STATE") == 0) {
        return NINLIL_E_INVALID_STATE;
    }
    if (strcmp(name, "WOULD_BLOCK") == 0) {
        return NINLIL_E_WOULD_BLOCK;
    }
    if (strcmp(name, "CAPACITY_EXHAUSTED") == 0) {
        return NINLIL_E_CAPACITY_EXHAUSTED;
    }
    return (ninlil_status_t)0xFFFFu;
}

static ninlil_domain_scan_state_t state_from_name(const char *name)
{
    if (strcmp(name, "IDLE") == 0) {
        return NINLIL_DOMAIN_SCAN_STATE_IDLE;
    }
    if (strcmp(name, "OPEN") == 0) {
        return NINLIL_DOMAIN_SCAN_STATE_OPEN;
    }
    if (strcmp(name, "EXHAUSTED") == 0) {
        return NINLIL_DOMAIN_SCAN_STATE_EXHAUSTED;
    }
    if (strcmp(name, "FAILED") == 0) {
        return NINLIL_DOMAIN_SCAN_STATE_FAILED;
    }
    if (strcmp(name, "DONE") == 0) {
        return NINLIL_DOMAIN_SCAN_STATE_DONE;
    }
    return (ninlil_domain_scan_state_t)0xFFu;
}

static int map_spy_op_to_oracle_name(ninlil_spy_op_t op, const char **out_name)
{
    switch (op) {
    case NINLIL_SPY_OP_BEGIN:
        *out_name = "begin:READ_ONLY";
        return 1;
    case NINLIL_SPY_OP_GET:
        *out_name = "get";
        return 1;
    case NINLIL_SPY_OP_ITER_OPEN:
        *out_name = "iter_open:prefix0";
        return 1;
    case NINLIL_SPY_OP_ITER_NEXT:
        *out_name = "iter_next";
        return 1;
    case NINLIL_SPY_OP_ITER_CLOSE:
        *out_name = "iter_close";
        return 1;
    case NINLIL_SPY_OP_ROLLBACK:
        *out_name = "rollback";
        return 1;
    case NINLIL_SPY_OP_CLOSE:
        *out_name = "close";
        return 1;
    default:
        *out_name = "unknown_enum";
        return 0;
    }
}

static uint64_t count_peer_gets_from_trace(
    const char *const *mapped, size_t mapped_count)
{
    uint64_t peer = 0u;
    int after_iter_open = 0;
    size_t i;

    for (i = 0u; i < mapped_count; ++i) {
        if (strcmp(mapped[i], "begin:READ_ONLY") == 0) {
            after_iter_open = 0;
        } else if (strcmp(mapped[i], "iter_open:prefix0") == 0) {
            after_iter_open = 1;
        } else if (after_iter_open != 0 && strcmp(mapped[i], "get") == 0) {
            peer += 1u;
        }
    }
    return peer;
}

static void fill_candidate(
    ninlil_model_runtime_store_binding_t *out, const ninlil_dsd1_binding_t *in)
{
    (void)memset(out, 0, sizeof(*out));
    out->storage_schema = in->storage_schema;
    out->role = (ninlil_role_t)in->role;
    out->environment = (ninlil_environment_t)in->environment;
    (void)memcpy(out->runtime_id.bytes, in->runtime_id, 16u);
    out->limits.max_services = in->max_services;
    out->limits.max_nonterminal_transactions =
        in->max_nonterminal_transactions;
    out->limits.max_targets_per_transaction =
        in->max_targets_per_transaction;
    out->limits.max_logical_payload_bytes = in->max_logical_payload_bytes;
    out->limits.max_durable_outbox_payload_bytes =
        in->max_durable_outbox_payload_bytes;
    out->limits.max_attempts_per_target_per_cycle =
        in->max_attempts_per_target_per_cycle;
    out->limits.max_cancel_attempts_per_transaction =
        in->max_cancel_attempts_per_transaction;
    out->limits.max_evidence_per_target = in->max_evidence_per_target;
    out->limits.max_retained_terminal_transactions =
        in->max_retained_terminal_transactions;
    out->limits.max_nonterminal_deliveries = in->max_nonterminal_deliveries;
    out->limits.max_event_spool_count = in->max_event_spool_count;
    out->limits.max_event_spool_bytes = in->max_event_spool_bytes;
    out->limits.max_result_cache_entries = in->max_result_cache_entries;
    out->limits.max_retained_dispositions = in->max_retained_dispositions;
    out->limits.max_ingress_per_step = in->max_ingress_per_step;
    out->limits.max_callbacks_per_step = in->max_callbacks_per_step;
    out->limits.max_state_transitions_per_step =
        in->max_state_transitions_per_step;
    out->limits.max_bearer_sends_per_step = in->max_bearer_sends_per_step;
    out->limits.max_deferred_tokens = in->max_deferred_tokens;
    out->terminal_retention_ms = in->terminal_retention_ms;
    out->result_cache_retention_ms = in->result_cache_retention_ms;
    out->observation_retention_ms = in->observation_retention_ms;
}

static int install_rows(
    ninlil_scripted_storage_spy_t *spy,
    const ninlil_dsd1_row_t *rows,
    size_t row_count)
{
    size_t i;
    for (i = 0u; i < row_count; ++i) {
        if (!ninlil_spy_add_row(spy, rows[i].key, rows[i].key_length,
                rows[i].value_length == 0u ? NULL : rows[i].value,
                rows[i].value_length)) {
            return 0;
        }
    }
    return 1;
}

static int run_session(
    const ninlil_dsd1_vector_t *vec, const ninlil_dsd1_session_t *sess)
{
    ninlil_scripted_storage_spy_t spy;
    ninlil_domain_scan_session_t session;
    ninlil_domain_scan_workspace_t workspace;
    ninlil_domain_scan_d3s1_context_t d3s1_context;
    ninlil_domain_scan_d3s2_context_t d3s2_context;
    ninlil_domain_scan_result_t result;
    ninlil_model_runtime_store_binding_t candidate;
    ninlil_storage_handle_t handle;
    const ninlil_storage_ops_t *ops;
    ninlil_status_t status = NINLIL_OK;
    ninlil_status_t expected_final;
    size_t i;
    size_t mapped_trace = 0u;
    const char *mapped[NINLIL_DSD1_MAX_TRACE];
    uint64_t observed_peer_gets;
    uint64_t observed_get_total;
    uint64_t baseline_gets;
    int is_s1;
    int is_s2;
    uint32_t begin_calls_seen = 0u;

    current_id = sess->id;
    is_s1 = (strcmp(sess->family, "s1") == 0);
    is_s2 = (strcmp(sess->family, "s2") == 0);
    REQUIRE(is_s1 || is_s2);
    REQUIRE(!(is_s1 && is_s2));
    REQUIRE(sess->mode != 28u);
    if (is_s1) {
        REQUIRE(sess->mode >= 1u && sess->mode <= 20u);
    } else {
        REQUIRE(sess->mode >= 21u && sess->mode <= 26u);
        REQUIRE(sess->mode != 28u);
    }

    expected_final = status_from_name(sess->expected.final_status);
    ninlil_spy_init(&spy);
    ops = ninlil_spy_ops(&spy);
    handle = ninlil_spy_open_handle(&spy);
    fill_candidate(&candidate, &vec->candidate);
    REQUIRE(install_rows(&spy, vec->rows, vec->row_count));

    ninlil_domain_scan_session_init(&session);
    (void)memset(&workspace, 0, sizeof(workspace));
    (void)memset(&d3s1_context, 0, sizeof(d3s1_context));
    (void)memset(&d3s2_context, 0, sizeof(d3s2_context));
    (void)memset(&result, 0, sizeof(result));

    for (i = 0u; i < sess->call_count; ++i) {
        const ninlil_dsd1_call_t *call = &sess->calls[i];
        uint64_t trace_before = spy.trace_count;
        REQUIRE(call->expected_status != NULL);

        if (strcmp(call->op, "begin_profiled_d3s1") == 0) {
            REQUIRE(is_s1);
            /* Fresh session: exclusive kind NONE before begin (dual-bound ban). */
            REQUIRE(session.bound_d3_kind == NINLIL_DOMAIN_SCAN_D3_KIND_NONE);
            status = ninlil_domain_scan_begin_profiled_d3s1(
                &session, ops, &handle, &workspace, &candidate, call->mode,
                &d3s1_context);
            REQUIRE(status == status_from_name(call->expected_status));
            if (status == NINLIL_OK) {
                /* kind is the exclusive S1/S2 discriminator (union storage). */
                REQUIRE(session.bound_d3_kind == NINLIL_DOMAIN_SCAN_D3_KIND_S1);
                REQUIRE(session.bound_d3_context == &d3s1_context);
                REQUIRE(d3s1_context.mode == call->mode);
                REQUIRE(d3s1_context.mode == sess->mode);
                begin_calls_seen += 1u;
            } else {
                REQUIRE(spy.trace_count == trace_before);
            }
        } else if (strcmp(call->op, "begin_profiled_d3s2") == 0) {
            REQUIRE(is_s2);
            REQUIRE(session.bound_d3_kind == NINLIL_DOMAIN_SCAN_D3_KIND_NONE);
            status = ninlil_domain_scan_begin_profiled_d3s2(
                &session, ops, &handle, &workspace, &candidate, call->mode,
                &d3s2_context);
            REQUIRE(status == status_from_name(call->expected_status));
            if (status == NINLIL_OK) {
                REQUIRE(session.bound_d3_kind == NINLIL_DOMAIN_SCAN_D3_KIND_S2);
                REQUIRE(session.bound_d3s2_context == &d3s2_context);
                REQUIRE(d3s2_context.focus_mode == call->mode);
                REQUIRE(d3s2_context.focus_mode == sess->mode);
                begin_calls_seen += 1u;
            } else {
                REQUIRE(spy.trace_count == trace_before);
            }
        } else if (strcmp(call->op, "advance") == 0) {
            REQUIRE(is_s1);
            status = ninlil_domain_scan_advance(&session, call->row_budget);
            REQUIRE(status == status_from_name(call->expected_status));
        } else if (strcmp(call->op, "d3s2_drive") == 0) {
            REQUIRE(is_s2);
            status = ninlil_domain_scan_d3s2_drive(&session, call->row_budget);
            REQUIRE(status == status_from_name(call->expected_status));
        } else if (strcmp(call->op, "finalize") == 0) {
            status = ninlil_domain_scan_finalize(&session, &result);
            REQUIRE(status == status_from_name(call->expected_status));
        } else if (strcmp(call->op, "abort") == 0) {
            status = ninlil_domain_scan_abort(&session, &result);
            REQUIRE(status == status_from_name(call->expected_status));
        } else {
            REQUIRE(0);
        }
    }

    REQUIRE(begin_calls_seen == 1u);
    REQUIRE(status == expected_final);
    REQUIRE(session.state == state_from_name(sess->expected.state_after));
    REQUIRE(result.status == status);
    REQUIRE(result.adopted == sess->expected.adopted);
    REQUIRE(result.recognizable_future_seen
        == sess->expected.recognizable_future_seen);
    REQUIRE(result.family14_row_count == sess->expected.family14_row_count);
    REQUIRE(result.current_domain_key_count
        == sess->expected.current_domain_key_count);
    REQUIRE(result.ok_row_count == sess->expected.ok_row_count);
    REQUIRE(result.profile_exact_active == sess->expected.profile_exact_active);
    REQUIRE(result.profile_mismatch == sess->expected.profile_mismatch);
    REQUIRE(result.future_profile_candidate
        == sess->expected.future_profile_candidate);
    REQUIRE(result.profile_get_present_mask
        == sess->expected.profile_get_present_mask);
    REQUIRE(result.family14_iter_seen_mask
        == sess->expected.family14_iter_seen_mask);
    REQUIRE(result.reopen_required == sess->expected.reopen_required);

    if (is_s1) {
        /* S1 COMPLETE: exclusive S1 kind; never S2. */
        REQUIRE(session.bound_d3_kind == NINLIL_DOMAIN_SCAN_D3_KIND_S1);
        REQUIRE(session.has_sticky_primary == 0u);
    } else {
        REQUIRE(session.bound_d3_kind == NINLIL_DOMAIN_SCAN_D3_KIND_S2);
        REQUIRE(d3s2_context.phase == sess->expected.phase);
        REQUIRE(d3s2_context.count_complete_mask
            == sess->expected.count_complete_mask);
        REQUIRE(d3s2_context.binding_complete_mask
            == sess->expected.binding_complete_mask);
        REQUIRE(d3s2_context.flags == sess->expected.flags);
        REQUIRE(d3s2_context.focus_mode == sess->mode);
        REQUIRE(d3s2_context.phase == NINLIL_DOMAIN_SCAN_D3S2_PHASE_COMPLETE);
        REQUIRE((d3s2_context.flags & NINLIL_DOMAIN_SCAN_D3S2_FLAG_COMPLETE_READY)
            != 0u);
        REQUIRE(session.has_sticky_primary == 0u);
    }

    REQUIRE(spy.mutation_calls == 0u);
    REQUIRE(ninlil_spy_assert_no_mutations(&spy));
    REQUIRE(sess->expected.mutation_calls == 0u);
    REQUIRE(spy.iter_open_calls == sess->expected.iter_open_count);
    REQUIRE(spy.begin_calls == 1u);

    for (i = 0u; i < spy.trace_count; ++i) {
        const char *name = NULL;
        REQUIRE(mapped_trace < NINLIL_DSD1_MAX_TRACE);
        REQUIRE(map_spy_op_to_oracle_name(spy.trace[i].op, &name));
        mapped[mapped_trace++] = name;
    }
    if (mapped_trace != sess->expected.port_trace_count) {
        (void)fprintf(stderr,
            "%s: port_trace count got %zu want %zu\n", current_id, mapped_trace,
            sess->expected.port_trace_count);
        return 1;
    }
    for (i = 0u; i < mapped_trace; ++i) {
        if (strcmp(mapped[i], sess->expected.port_trace[i]) != 0) {
            (void)fprintf(stderr, "%s: port_trace[%zu] got=%s want=%s\n",
                current_id, i, mapped[i], sess->expected.port_trace[i]);
            return 1;
        }
    }

    /* Single-txn pin. */
    {
        size_t begins = 0u;
        for (i = 0u; i < mapped_trace; ++i) {
            if (strcmp(mapped[i], "begin:READ_ONLY") == 0) {
                begins += 1u;
            }
        }
        REQUIRE(begins == 1u);
    }

    observed_get_total = 0u;
    baseline_gets = 0u;
    {
        int after_iter_open = 0;
        for (i = 0u; i < mapped_trace; ++i) {
            if (strcmp(mapped[i], "get") == 0) {
                observed_get_total += 1u;
                if (after_iter_open == 0) {
                    baseline_gets += 1u;
                }
            } else if (strcmp(mapped[i], "iter_open:prefix0") == 0) {
                after_iter_open = 1;
            } else if (strcmp(mapped[i], "begin:READ_ONLY") == 0) {
                after_iter_open = 0;
            }
        }
    }
    REQUIRE(spy.get_calls == (uint32_t)observed_get_total);
    observed_peer_gets = count_peer_gets_from_trace(mapped, mapped_trace);
    REQUIRE(observed_peer_gets + baseline_gets == observed_get_total);
    REQUIRE(baseline_gets == 17u);
    REQUIRE(observed_peer_gets == sess->expected.d3_peer_get_count);

    return 0;
}

static int run_vector(const ninlil_dsd1_vector_t *vec)
{
    size_t si;
    uint8_t seen_modes[32];
    size_t seen_n = 0u;

    current_id = vec->id;
    REQUIRE(strcmp(vec->kind, "dsd1_multi_session_orchestration") == 0);
    REQUIRE(vec->session_count == NINLIL_DSD1_SESSION_COUNT);
    REQUIRE(vec->row_count == 26u);

    for (si = 0u; si < vec->session_count; ++si) {
        const ninlil_dsd1_session_t *sess = &vec->sessions[si];
        size_t j;

        /* Each session is one mode; product is seven sessions, not one. */
        for (j = 0u; j < seen_n; ++j) {
            REQUIRE(seen_modes[j] != sess->mode);
        }
        REQUIRE(seen_n < sizeof(seen_modes));
        seen_modes[seen_n++] = sess->mode;

        if (run_session(vec, sess) != 0) {
            return 1;
        }
    }

    /* Closed DSD1 session product order pin. */
    REQUIRE(vec->sessions[0].mode == 11u
        && strcmp(vec->sessions[0].family, "s1") == 0);
    REQUIRE(vec->sessions[1].mode == 14u
        && strcmp(vec->sessions[1].family, "s1") == 0);
    REQUIRE(vec->sessions[2].mode == 17u
        && strcmp(vec->sessions[2].family, "s1") == 0);
    REQUIRE(vec->sessions[3].mode == 19u
        && strcmp(vec->sessions[3].family, "s1") == 0);
    REQUIRE(vec->sessions[4].mode == 22u
        && strcmp(vec->sessions[4].family, "s2") == 0);
    REQUIRE(vec->sessions[5].mode == 23u
        && strcmp(vec->sessions[5].family, "s2") == 0);
    REQUIRE(vec->sessions[6].mode == 24u
        && strcmp(vec->sessions[6].family, "s2") == 0);
    return 0;
}

int main(void)
{
    size_t i;

    REQUIRE(NINLIL_DSD1_VECTOR_COUNT == 1u);
    REQUIRE(NINLIL_DSD1_SESSION_COUNT == 7u);
    REQUIRE(sizeof(ninlil_domain_scan_workspace_t)
        <= NINLIL_DOMAIN_SCANNER_WORKSPACE_CEILING_BYTES);
    REQUIRE(sizeof(ninlil_domain_scan_d3s1_context_t)
        == NINLIL_DOMAIN_SCAN_D3S1_CONTEXT_SIZE_BYTES);
    REQUIRE(sizeof(ninlil_domain_scan_d3s2_context_t)
        == NINLIL_DOMAIN_SCAN_D3S2_CONTEXT_SIZE_BYTES);
    REQUIRE(_Alignof(ninlil_domain_scan_d3s1_context_t) == 1);
    REQUIRE(_Alignof(ninlil_domain_scan_d3s2_context_t) == 1);

    for (i = 0u; i < NINLIL_DSD1_VECTOR_COUNT; ++i) {
        if (run_vector(&ninlil_dsd1_vectors[i]) != 0) {
            return 1;
        }
    }

    (void)printf(
        "domain_store_scanner_dsd1_composition_oracle_bridge: "
        "1 vector / 7 sessions (S1 11/14/17/19 + S2 22/23/24) ok\n");
    return 0;
}
