/*
 * Production C decoder bridge for control-frame-v1.json.
 *
 * Fixture header is generated by tools/control_frame_vector_gen.py
 * emit-c-fixture: golden frames + *applied* negative mutation bytes and
 * expected_result. This test loops every case through production
 * ninlil_model_control_frame_decode and requires exact expected_result.
 *
 * Independent Python check alone is not sufficient: both sides share the
 * same materialised fixture so recipe/JSON drift cannot green independently.
 */

#include "control_frame_codec.h"
#include "control_frame_vector_fixture.h"

#include <stdio.h>
#include <string.h>

#define REQUIRE(condition)                                                     \
    do {                                                                       \
        if (!(condition)) {                                                    \
            (void)fprintf(stderr, "%s:%d: case %s failed: %s\n", __FILE__,   \
                __LINE__, current_id, #condition);                             \
            return 1;                                                          \
        }                                                                      \
    } while (0)

static const char *current_id = "";

static int run_all_cases(void)
{
    size_t i;
    size_t mutation_count = 0u;
    size_t golden_count = 0u;

    REQUIRE(NINLIL_CFV_CASE_COUNT > 0u);

    for (i = 0u; i < NINLIL_CFV_CASE_COUNT; ++i) {
        const ninlil_cfv_case_t *c = &ninlil_cfv_cases[i];
        ninlil_bytes_view_t encoded;
        ninlil_model_control_frame_view_t view;
        ninlil_model_control_frame_result_t result =
            NINLIL_MODEL_CONTROL_FRAME_RESULT_NEED_MORE;
        ninlil_status_t st;

        current_id = c->id;
        REQUIRE(c->id != NULL);
        REQUIRE(c->kind != NULL);
        REQUIRE(c->bytes != NULL || c->length == 0u);
        REQUIRE(c->length <= NINLIL_CFV_MAX_FRAME_BYTES);

        if (strcmp(c->kind, "mutation") == 0) {
            mutation_count += 1u;
        } else if (strcmp(c->kind, "golden") == 0) {
            golden_count += 1u;
        } else {
            REQUIRE(0);
        }

        (void)memset(&view, 0, sizeof(view));
        encoded.data = c->bytes;
        encoded.length = (uint32_t)c->length;
        st = ninlil_model_control_frame_decode(encoded, &view, &result);
        REQUIRE(st == NINLIL_OK);
        REQUIRE(result == c->expected_result);

        if (result == NINLIL_MODEL_CONTROL_FRAME_RESULT_OK) {
            REQUIRE(view.version == NINLIL_MODEL_CONTROL_FRAME_VERSION);
            REQUIRE(ninlil_model_control_frame_type_is_known(view.type));
        }
    }

    /* Catalog pins: 6 goldens with frames (empty,ping,pong,reset,max,mut_base)
     * + 7 mutations. mut_base is golden kind. */
    REQUIRE(mutation_count == 7u);
    REQUIRE(golden_count >= 5u);
    REQUIRE(mutation_count + golden_count == NINLIL_CFV_CASE_COUNT);
    return 0;
}

int main(void)
{
    if (run_all_cases() != 0) {
        return 1;
    }
    (void)printf(
        "control_frame_vector_oracle_bridge OK (%zu cases)\n",
        (size_t)NINLIL_CFV_CASE_COUNT);
    return 0;
}
