/*
 * Production C bridge for ncl1-u4-v1.json codec cases.
 *
 * Fixture is generated by tools/ncl1_u4_vector_gen.py emit-c-fixture with
 * materialized payload bytes + expected_decode (and bootstrap/ack/reserved
 * flags where applicable). Every codec case runs through production
 * ninlil_ncl1_decode. Independent Python check alone is insufficient.
 *
 * Does not claim U4 session/LC complete, HIL, assignment, or series complete.
 */

#include "ncl1_codec.h"
#include "ncl1_u4_vector_fixture.h"

#include <stdio.h>
#include <string.h>

#define REQUIRE(condition)                                                     \
    do {                                                                       \
        if (!(condition)) {                                                    \
            (void)fprintf(stderr, "%s:%d: case %s failed: %s\n", __FILE__,     \
                __LINE__, current_id, #condition);                             \
            return 1;                                                          \
        }                                                                      \
    } while (0)

static const char *current_id = "";

static int run_all_codec_cases(void)
{
    size_t i;
    size_t saw_bad_magic = 0u;
    size_t saw_reserved_order = 0u;
    size_t saw_type_bind = 0u;
    size_t golden = 0u;
    size_t neg = 0u;

    REQUIRE(NINLIL_NCL1_U4_REQUIRED_ID_COUNT == 46u);
    REQUIRE(NINLIL_NCL1_U4_VECTOR_COUNT == 47u);
    REQUIRE(NINLIL_NCL1_U4_CODEC_CASE_COUNT > 0u);
    REQUIRE(
        sizeof(NINLIL_NCL1_U4_REQUIRED_IDS)
            / sizeof(NINLIL_NCL1_U4_REQUIRED_IDS[0])
        == 46u);

    for (i = 0u; i < (size_t)NINLIL_NCL1_U4_CODEC_CASE_COUNT; ++i) {
        const ninlil_ncl1_u4_codec_case_t *c = &ninlil_ncl1_u4_codec_cases[i];
        ninlil_ncl1_message_t msg;
        ninlil_ncl1_status_t st;

        current_id = c->id;
        REQUIRE(c->id != NULL);
        REQUIRE(c->kind != NULL);
        REQUIRE(c->bytes != NULL);
        REQUIRE(c->length <= (size_t)NINLIL_NCL1_U4_MAX_PAYLOAD_BYTES);

        if (strcmp(c->kind, "golden") == 0) {
            golden += 1u;
        } else {
            neg += 1u;
        }

        (void)memset(&msg, 0, sizeof(msg));
        st = ninlil_ncl1_decode(c->bytes, c->length, c->ncg1_type, &msg);
        REQUIRE(st == (ninlil_ncl1_status_t)c->expected_decode);

        if (st == NINLIL_NCL1_OK && c->bootstrap_valid >= 0) {
            int bv = ninlil_ncl1_is_valid_hello_bootstrap(&msg);
            REQUIRE(bv == c->bootstrap_valid);
        }
        if (st == NINLIL_NCL1_OK && c->structurally_valid_ack >= 0) {
            int av = ninlil_ncl1_is_structurally_valid_hello_ack(&msg);
            REQUIRE(av == c->structurally_valid_ack);
        }
        if (st == NINLIL_NCL1_OK && c->reserved_ok >= 0) {
            ninlil_ncl1_status_t rs = ninlil_ncl1_check_reserved(&msg);
            if (c->reserved_ok == 0) {
                REQUIRE(rs == NINLIL_NCL1_REJECT_RESERVED);
            } else {
                REQUIRE(rs == NINLIL_NCL1_OK);
            }
        }

        if (strstr(c->id, "U4-N-BAD-MAGIC") != NULL) {
            saw_bad_magic = 1u;
        }
        if (strstr(c->id, "U4-N-RESERVED-ORDER") != NULL) {
            saw_reserved_order = 1u;
        }
        if (strstr(c->id, "TYPE-BIND") != NULL) {
            saw_type_bind = 1u;
        }
    }

    REQUIRE(saw_bad_magic == 1u);
    REQUIRE(saw_reserved_order == 1u);
    REQUIRE(saw_type_bind == 1u);
    REQUIRE(golden >= 5u);
    REQUIRE(neg >= 5u);
    REQUIRE(golden + neg == (size_t)NINLIL_NCL1_U4_CODEC_CASE_COUNT);
    return 0;
}

static int test_required_id_catalog(void)
{
    size_t i;
    int saw_hello_ok = 0;
    int saw_dup = 0;
    int saw_active_cookie = 0;

    for (i = 0u; i < 46u; ++i) {
        REQUIRE(NINLIL_NCL1_U4_REQUIRED_IDS[i] != NULL);
        REQUIRE(NINLIL_NCL1_U4_REQUIRED_IDS[i][0] == 'U');
        if (strcmp(NINLIL_NCL1_U4_REQUIRED_IDS[i], "U4-G-HELLO-OK") == 0) {
            saw_hello_ok = 1;
        }
        if (strcmp(NINLIL_NCL1_U4_REQUIRED_IDS[i], "U4-G-DUP-HELLO-RECEIVED")
            == 0) {
            saw_dup = 1;
        }
        if (strcmp(
                NINLIL_NCL1_U4_REQUIRED_IDS[i], "U4-N-HELLO-ACTIVE-COOKIE-REJECT")
            == 0) {
            saw_active_cookie = 1;
        }
    }
    REQUIRE(saw_hello_ok == 1);
    REQUIRE(saw_dup == 1);
    REQUIRE(saw_active_cookie == 1);
    return 0;
}

int main(void)
{
    if (test_required_id_catalog() != 0) {
        return 1;
    }
    if (run_all_codec_cases() != 0) {
        return 1;
    }
    (void)printf(
        "ncl1_vector_oracle_bridge OK (codec_cases=%u required_ids=46 vectors=47)\n",
        (unsigned)NINLIL_NCL1_U4_CODEC_CASE_COUNT);
    return 0;
}
