/* SPDX-License-Identifier: Apache-2.0 */
/* Private PA-S1a build policy; it does not enable an Attachment protocol. */
#ifndef NINLIL_PA_S1_EDHOC_CONFIG_H
#define NINLIL_PA_S1_EDHOC_CONFIG_H

#define CONFIG_LIBEDHOC_ENABLE 1
#define CONFIG_LIBEDHOC_KEY_ID_LEN 4
#define CONFIG_LIBEDHOC_MAX_NR_OF_CIPHER_SUITES 3
#define CONFIG_LIBEDHOC_MAX_LEN_OF_CONN_ID 7
#define CONFIG_LIBEDHOC_MAX_LEN_OF_ECC_KEY 48
#define CONFIG_LIBEDHOC_MAX_LEN_OF_MAC 48
#define CONFIG_LIBEDHOC_MAX_NR_OF_EAD_TOKENS 3
#define CONFIG_LIBEDHOC_MAX_LEN_OF_CRED_KEY_ID 1
#define CONFIG_LIBEDHOC_MAX_LEN_OF_HASH_ALG 1
#define CONFIG_LIBEDHOC_MAX_NR_OF_CERTS_IN_X509_CHAIN 2
#define CONFIG_LIBEDHOC_LOG_LEVEL 0
#define CONFIG_LIBEDHOC_MEM_BACKEND 2

#endif
