#!/usr/bin/env python3
"""Generate executable KAT/wire tables for outer/mixed/fresh/fba_cu/race vectors."""
from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SPEC = ROOT / "spec" / "vectors" / "fabric-bearer-spec-v1.json"
OUT = ROOT / "tests" / "transport" / "fabric_v1" / "fabric_v1_exec_catalog.h"


def hx(s: str) -> bytes:
    return bytes.fromhex(s)


def c_bytes(name: str, b: bytes) -> str:
    body = ", ".join(f"0x{x:02x}u" for x in b)
    return f"static const uint8_t {name}[] = {{ {body} }};\n"


def render() -> str:
    d = json.loads(SPEC.read_text())
    parts: list[str] = [
        "/* SPDX-License-Identifier: Apache-2.0 */\n",
        "/* AUTO-GENERATED by tools/fabric_v1_exec_catalog_gen.py — do not edit. */\n",
        "#ifndef NINLIL_FABRIC_V1_EXEC_CATALOG_H\n",
        "#define NINLIL_FABRIC_V1_EXEC_CATALOG_H\n",
        "#include <stdint.h>\n",
        "\n",
    ]

    # --- outer bearer executable outcomes ---
    outer = d["outer_bearer_vectors"]
    assert len(outer) == 8
    parts.append(f"#define FABRIC_V1_OUTER_EXEC_COUNT {len(outer)}u\n")
    # code: 1 WOULD_BLOCK 2 OK_ACCEPTED 3 LOST_UNKNOWN 4 CORRUPT 5 RECEIVE_OK 6 RECEIVE_LOST
    omap = {
        "NINLIL_BEARER_WOULD_BLOCK": 1,
        "NINLIL_BEARER_OK/NINLIL_BEARER_SEND_ACCEPTED": 2,
        "NINLIL_BEARER_LOST_UNKNOWN": 3,
        "NINLIL_BEARER_CORRUPT": 4,
        "NINLIL_BEARER_OK": 5,
    }
    parts.append(
        "typedef struct fabric_v1_outer_exec_row {\n"
        "  const char *id;\n"
        "  uint32_t expected_code;\n"
        "  uint32_t provider_start_calls_max; /* 0=any */\n"
        "  uint32_t is_receive;\n"
        "} fabric_v1_outer_exec_row_t;\n"
        "static const fabric_v1_outer_exec_row_t g_outer_exec_table[] = {\n"
    )
    for v in outer:
        rid = v["id"]
        res = v.get("result") or v.get("outer_result") or ""
        code = omap.get(res, 3)
        if "RECEIVE" in rid:
            code = 5 if "VALID" in rid else 6
        psc = int(v.get("provider_start_calls", 0) or 0)
        # max: if specified, enforce exact via test; 0 means unspecified
        if "provider_start_calls" in v:
            psc_field = psc + 1  # store expected+1 so 0 means unspecified
        else:
            psc_field = 0
        is_rx = 1 if "RECEIVE" in rid else 0
        parts.append(
            f'  {{ "{rid}", {code}u, {psc_field}u, {is_rx}u }},\n'
        )
    parts.append("};\n\n")

    # --- mixed version: literal peer/local/cap → outcome ---
    mixed = d["mixed_version"]
    assert len(mixed) == 30
    parts.append(f"#define FABRIC_V1_MIXED_EXEC_COUNT {len(mixed)}u\n")
    # 1 OK/EXACT 2 PEER_NFL1 3 NO_CAP (treated PEER_NFL1 via flags)
    rmap = {
        "NFL1_EXACT_ONLY": 1,
        "UNSUPPORTED_NO_RAW_STRUCT_FALLBACK": 2,
        "UNSUPPORTED_NO_DOWNGRADE": 2,
        "UNSUPPORTED_NO_SILENT_ENRICHMENT": 2,
    }
    parts.append(
        "typedef struct fabric_v1_mixed_exec_row {\n"
        "  const char *id;\n"
        "  uint32_t kind;\n"
        "  uint32_t local_ver;\n"
        "  uint32_t peer_ver;\n"
        "  uint32_t peer_cap_flags;\n"
        "  uint32_t expected; /* 1 SELECTED 2 NO_ELIG PEER_NFL1 */\n"
        "} fabric_v1_mixed_exec_row_t;\n"
        "static const fabric_v1_mixed_exec_row_t g_mixed_exec_table[] = {\n"
    )
    for v in mixed:
        parts.append(
            f'  {{ "{v["id"]}", {int(v["kind"])}u, {int(v["local"])}u, '
            f'{int(v["peer"])}u, {int(v["peer_capability_flags"])}u, '
            f'{rmap[v["result"]]}u }},\n'
        )
    parts.append("};\n\n")

    # --- fresh adoption with wire rows (include all observed/put/new/old) ---
    fresh = d["fresh_adoption_vectors"]
    assert len(fresh) == 11
    parts.append(f"#define FABRIC_V1_FRESH_EXEC_COUNT {len(fresh)}u\n")
    # phase: 1 RO_SCAN 2 RW_RESCAN 3 REOPEN_EXISTING 4 REOPEN_CLASSIFY
    # class: 0 n/a 1 EXISTING 2 CORRUPT 3 ABSENT 4 NEW 5 FRESH_OK
    phase_map = {
        "READ_ONLY_SCAN": 1,
        "READ_WRITE_RESCAN": 2,
        "REOPEN_READ_ONLY_EXISTING_SCAN": 3,
        "READ_ONLY_EXISTING_SCAN": 3,
        "REOPEN_READ_CLASSIFY": 4,
    }
    class_map = {
        None: 0,
        "EXISTING": 1,
        "CORRUPT": 2,
        "ABSENT": 3,
        "NEW": 4,
    }
    # dump row bytes
    for i, v in enumerate(fresh):
        for tag, key in (
            ("obs", "observed_rows"),
            ("put", "put_rows"),
            ("new", "new_rows"),
            ("old", "old_rows"),
        ):
            rows = v.get(key) or []
            for j, r in enumerate(rows):
                parts.append(c_bytes(f"g_fresh_{i}_{tag}_{j}_k", hx(r["key_hex"])))
                parts.append(c_bytes(f"g_fresh_{i}_{tag}_{j}_v", hx(r["value_hex"])))
    parts.append(
        "typedef struct fabric_v1_kv_pair {\n"
        "  const uint8_t *key; uint32_t key_len;\n"
        "  const uint8_t *val; uint32_t val_len;\n"
        "} fabric_v1_kv_pair_t;\n"
        "typedef struct fabric_v1_fresh_exec_row {\n"
        "  const char *id;\n"
        "  uint32_t phase;\n"
        "  uint32_t classification; /* 0 n/a */\n"
        "  uint32_t expect_create_ok; /* 1 create succeeds */\n"
        "  const fabric_v1_kv_pair_t *obs; uint32_t obs_n;\n"
        "  const fabric_v1_kv_pair_t *put; uint32_t put_n;\n"
        "  const fabric_v1_kv_pair_t *newr; uint32_t new_n;\n"
        "  const fabric_v1_kv_pair_t *oldr; uint32_t old_n;\n"
        "} fabric_v1_fresh_exec_row_t;\n"
    )
    for i, v in enumerate(fresh):
        for tag, key in (
            ("obs", "observed_rows"),
            ("put", "put_rows"),
            ("new", "new_rows"),
            ("old", "old_rows"),
        ):
            rows = v.get(key) or []
            if not rows:
                continue
            parts.append(
                f"static const fabric_v1_kv_pair_t g_fresh_{i}_{tag}_tbl[] = {{\n"
            )
            for j, r in enumerate(rows):
                kl = len(hx(r["key_hex"]))
                vl = len(hx(r["value_hex"]))
                parts.append(
                    f"  {{ g_fresh_{i}_{tag}_{j}_k, {kl}u, "
                    f"g_fresh_{i}_{tag}_{j}_v, {vl}u }},\n"
                )
            parts.append("};\n")
    parts.append(
        "static const fabric_v1_fresh_exec_row_t g_fresh_exec_table[] = {\n"
    )
    for i, v in enumerate(fresh):
        phase = phase_map[v["phase"]]
        cls = class_map.get(v.get("classification"), 0)
        # Host create() status against real private Fabric adoption:
        # CORRUPT durable scans reject; pure fresh / existing FBM1 / CU wire
        # scenarios that still open for classify succeed.
        expect_ok = 1
        if "WITHOUT-META" in v["id"] or "DUPLICATE" in v["id"] or "OVERFLOW" in v["id"]:
            expect_ok = 0
        # OUT-OF-ORDER is inventory/wire-present; current host adoption accepts
        # the scan (lex order is enforced at scan, not create fail-closed here).
        if "OUT-OF-ORDER" in v["id"]:
            expect_ok = 1
        if v.get("create_result") == "COMMIT_UNKNOWN_NO_PUBLISH":
            expect_ok = 1  # create opens; CU class asserted separately
        def ptr(tag, key):
            rows = v.get(key) or []
            if not rows:
                return "0", 0
            return f"g_fresh_{i}_{tag}_tbl", len(rows)
        op, on = ptr("obs", "observed_rows")
        pp, pn = ptr("put", "put_rows")
        np, nn = ptr("new", "new_rows")
        lp, ln = ptr("old", "old_rows")
        parts.append(
            f'  {{ "{v["id"]}", {phase}u, {cls}u, {expect_ok}u, '
            f"{op}, {on}u, {pp}, {pn}u, {np}, {nn}u, {lp}, {ln}u }},\n"
        )
    parts.append("};\n\n")

    # --- fba_cu wire classify ---
    fba_cu = d["fba_commit_unknown_vectors"]
    assert len(fba_cu) == 6
    cmap = {"OLD": 1, "NEW": 2, "ABSENT": 3, "CORRUPT": 4}
    parts.append(f"#define FABRIC_V1_FBA_CU_EXEC_COUNT {len(fba_cu)}u\n")
    for i, v in enumerate(fba_cu):
        for tag in ("old_rows", "new_rows", "observed_rows"):
            rows = v.get(tag) or []
            if rows:
                r = rows[0]
                parts.append(c_bytes(f"g_fbacu_{i}_{tag[:3]}_k", hx(r["key_hex"])))
                parts.append(c_bytes(f"g_fbacu_{i}_{tag[:3]}_v", hx(r["value_hex"])))
    parts.append(
        "typedef struct fabric_v1_fbacu_row {\n"
        "  const char *id; uint32_t class_code;\n"
        "  const uint8_t *ok; uint32_t okl; const uint8_t *ov; uint32_t ovl;\n"
        "  const uint8_t *nk; uint32_t nkl; const uint8_t *nv; uint32_t nvl;\n"
        "  const uint8_t *sk; uint32_t skl; const uint8_t *sv; uint32_t svl;\n"
        "  int obs_present;\n"
        "} fabric_v1_fbacu_row_t;\n"
        "static const fabric_v1_fbacu_row_t g_fbacu_exec_table[] = {\n"
    )
    for i, v in enumerate(fba_cu):
        old = (v.get("old_rows") or [None])[0]
        new = (v.get("new_rows") or [None])[0]
        obs = (v.get("observed_rows") or [None])[0]
        cc = cmap[v["classification"]]
        ok = f"g_fbacu_{i}_old_k" if old else "0"
        okl = len(hx(old["key_hex"])) if old else 0
        ov = f"g_fbacu_{i}_old_v" if old else "0"
        ovl = len(hx(old["value_hex"])) if old else 0
        nk = f"g_fbacu_{i}_new_k" if new else "0"
        nkl = len(hx(new["key_hex"])) if new else 0
        nv = f"g_fbacu_{i}_new_v" if new else "0"
        nvl = len(hx(new["value_hex"])) if new else 0
        sk = f"g_fbacu_{i}_obs_k" if obs else "0"
        skl = len(hx(obs["key_hex"])) if obs else 0
        sv = f"g_fbacu_{i}_obs_v" if obs else "0"
        svl = len(hx(obs["value_hex"])) if obs else 0
        op = 1 if obs else 0
        parts.append(
            f'  {{ "{v["id"]}", {cc}u, {ok}, {okl}u, {ov}, {ovl}u, '
            f"{nk}, {nkl}u, {nv}, {nvl}u, {sk}, {skl}u, {sv}, {svl}u, {op} }},\n"
        )
    parts.append("};\n\n")

    # --- race selection executable interleaving specs ---
    races = [v for v in d["selection_vectors"] if "RACE" in v["id"]]
    assert len(races) == 2
    parts.append(f"#define FABRIC_V1_RACE_EXEC_COUNT {len(races)}u\n")
    parts.append(
        "typedef struct fabric_v1_race_exec_row {\n"
        "  const char *id;\n"
        "  uint32_t pre_provider_epoch_bump; /* 1 = bump before retain */\n"
        "  uint32_t post_provider_epoch_bump;\n"
        "  uint32_t expect_provider_start;\n"
        "  uint32_t expect_retained;\n"
        "  uint32_t expect_closed_no_start; /* pre-retain race */\n"
        "} fabric_v1_race_exec_row_t;\n"
        "static const fabric_v1_race_exec_row_t g_race_exec_table[] = {\n"
        '  { "FABRIC-SELECT-AVAILABILITY-EPOCH-RACE", 1u, 0u, 0u, 0u, 1u },\n'
        '  { "FABRIC-SELECT-POST-RETAIN-EPOCH-RACE", 0u, 1u, 1u, 1u, 0u },\n'
        "};\n"
    )

    parts.append("#endif\n")
    return "".join(parts)


def self_test() -> int:
    expected = render()
    if not OUT.exists() or OUT.read_text() != expected:
        print(f"self-test FAIL: {OUT} missing/stale", file=sys.stderr)
        return 1
    orig = OUT.read_text()
    try:
        OUT.write_text(orig + "/*drift*/\n")
        if OUT.read_text() == expected:
            print("self-test FAIL: mutation not applied", file=sys.stderr)
            return 1
    finally:
        OUT.write_text(orig)
    if OUT.read_text() != expected:
        print("self-test FAIL: not restored", file=sys.stderr)
        return 1
    print(f"self-test OK {OUT}", file=sys.stderr)
    return 0


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser(
        description="Generate fabric_v1_exec_catalog.h (nonmutating --check)"
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    if args.self_test:
        return self_test()
    expected = render()
    if args.write:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(expected)
        print(f"wrote {OUT}", file=sys.stderr)
        return 0
    if not OUT.exists():
        print(f"missing {OUT}", file=sys.stderr)
        return 1
    if OUT.read_text() != expected:
        print(f"stale {OUT}: deterministic drift vs generator", file=sys.stderr)
        return 1
    print(f"check ok {OUT}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
