#!/usr/bin/env python3
"""Generate C tables for selection vectors executed via fabric_private_select."""
from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SPEC = ROOT / "spec" / "vectors" / "fabric-bearer-spec-v1.json"
OUT = ROOT / "tests" / "transport" / "fabric_v1" / "fabric_v1_selection_vectors.h"


def hx(s: str) -> bytes:
    return bytes.fromhex(s)


def c_bytes(name: str, b: bytes) -> str:
    body = ", ".join(f"0x{x:02x}u" for x in b)
    return f"static const uint8_t {name}[] = {{ {body} }};\n"


def render() -> str:
    d = json.loads(SPEC.read_text())
    vectors = d["selection_vectors"]
    assert len(vectors) == 48

    parts: list[str] = [
        "/* SPDX-License-Identifier: Apache-2.0 */\n",
        "/* AUTO-GENERATED by tools/fabric_v1_selection_vector_gen.py — do not edit. */\n",
        "#ifndef NINLIL_FABRIC_V1_SELECTION_VECTORS_H\n",
        "#define NINLIL_FABRIC_V1_SELECTION_VECTORS_H\n",
        "#include \"fabric_private_select.h\"\n",
        "#include <stdint.h>\n",
        "#include <string.h>\n",
        f"#define FABRIC_V1_SEL_VEC_COUNT {len(vectors)}u\n",
        "typedef struct fabric_v1_sel_vec_row {\n",
        "  const char *id;\n",
        "  uint32_t expected_resolution; /* 1 SEL 2 NO_ELIG 3 NO_POL 4 CORRUPT */\n",
        "  const char *expected_rejection; /* NULL if SELECTED */\n",
        "  const char *mutation_op; /* none|replace|append|remove */\n",
        "  const char *mutation_path; /* dotted path */\n",
        "  const char *mutation_new_s; /* string/int/hex payload or empty */\n",
        "} fabric_v1_sel_vec_row_t;\n",
    ]

    res_map = {
        "SELECTED": 1,
        "NO_ELIGIBLE": 2,
        "NO_ELIGIBLE_PATH": 2,
        "NO_POLICY": 3,
        "CORRUPT": 4,
    }

    rows = []
    for i, v in enumerate(vectors):
        model = v.get("model") or {}
        if not model.get("resolution"):
            # Race vectors: deterministic interleaving in host_acceptance_test.
            if "AVAILABILITY-EPOCH-RACE" in v["id"]:
                res, rej, op = 2, "UNAVAILABLE", "race_pre_retain"
            elif "POST-RETAIN-EPOCH-RACE" in v["id"]:
                res, rej, op = 1, None, "race_post_retain"
            else:
                res, rej, op = 0, None, "race"
            rej_c = "NULL" if not rej else f'"{rej}"'
            rows.append(
                f'  {{ "{v["id"]}", {res}u, {rej_c}, "{op}", "", "" }}'
            )
            continue
        res = res_map.get(model.get("resolution", "CORRUPT"), 4)
        rej = model.get("primary_rejection")
        mut = v.get("mutation")
        if mut is None:
            op, path, news = "none", "", ""
        else:
            op = mut.get("operation") or "none"
            path = ".".join(str(p) for p in (mut.get("path") or []))
            new = mut.get("new")
            if new is None:
                news = ""
            elif isinstance(new, (int, float)):
                news = str(int(new))
            elif isinstance(new, str):
                news = new
            elif isinstance(new, list):
                news = ",".join(str(x) for x in new)
            else:
                news = json.dumps(new, separators=(",", ":"))
        rej_c = "NULL" if not rej else f'"{rej}"'
        rows.append(
            f'  {{ "{v["id"]}", {res}u, {rej_c}, "{op}", "{path}", '
            f'"{news.replace(chr(34), chr(92)+chr(34))}" }}'
        )

    parts.append(
        "static const fabric_v1_sel_vec_row_t g_sel_vec_table[] = {\n"
        + ",\n".join(rows)
        + "\n};\n"
    )

    # Storage negative rows for real decode
    snegs = d["storage_negative_vectors"]
    parts.append(f"#define FABRIC_V1_SNEG_EXEC_COUNT {len(snegs)}u\n")
    parts.append(
        "typedef struct fabric_v1_sneg_row {"
        " const char *id; const uint8_t *key; uint32_t key_len;"
        " const uint8_t *val; uint32_t val_len; const char *expected;"
        " } fabric_v1_sneg_row_t;\n"
    )
    for i, v in enumerate(snegs):
        parts.append(c_bytes(f"g_sneg_{i}_key", hx(v["key_hex"])))
        parts.append(c_bytes(f"g_sneg_{i}_val", hx(v["value_hex"])))
    parts.append("static const fabric_v1_sneg_row_t g_sneg_exec_table[] = {\n")
    for i, v in enumerate(snegs):
        kl = len(hx(v["key_hex"]))
        vl = len(hx(v["value_hex"]))
        parts.append(
            f'  {{ "{v["id"]}", g_sneg_{i}_key, {kl}u, g_sneg_{i}_val, {vl}u,'
            f' "{v["expected"]}" }},\n'
        )
    parts.append("};\n")

    # CU matrix for classify
    cus = d["commit_unknown_matrix"]
    parts.append(f"#define FABRIC_V1_CU_EXEC_COUNT {len(cus)}u\n")
    parts.append(
        "typedef struct fabric_v1_cu_row {"
        " const char *id; uint32_t class_code; /* 1 OLD 2 NEW 3 ABSENT 4 CORRUPT */"
        " const uint8_t *old_k; uint32_t old_kl; const uint8_t *old_v; uint32_t old_vl;"
        " const uint8_t *new_k; uint32_t new_kl; const uint8_t *new_v; uint32_t new_vl;"
        " const uint8_t *obs_k; uint32_t obs_kl; const uint8_t *obs_v; uint32_t obs_vl;"
        " int obs_present; } fabric_v1_cu_row_t;\n"
    )
    class_map = {"OLD": 1, "NEW": 2, "ABSENT": 3, "CORRUPT": 4, "THIRD": 4}
    for i, v in enumerate(cus):
        old = (v.get("old_rows") or [None])[0]
        new = (v.get("new_rows") or [None])[0]
        obs = (v.get("observed_rows") or [None])[0]
        if old:
            parts.append(c_bytes(f"g_cu_{i}_ok", hx(old["key_hex"])))
            parts.append(c_bytes(f"g_cu_{i}_ov", hx(old["value_hex"])))
        if new:
            parts.append(c_bytes(f"g_cu_{i}_nk", hx(new["key_hex"])))
            parts.append(c_bytes(f"g_cu_{i}_nv", hx(new["value_hex"])))
        if obs:
            parts.append(c_bytes(f"g_cu_{i}_sk", hx(obs["key_hex"])))
            parts.append(c_bytes(f"g_cu_{i}_sv", hx(obs["value_hex"])))
    parts.append("static const fabric_v1_cu_row_t g_cu_exec_table[] = {\n")
    for i, v in enumerate(cus):
        old = (v.get("old_rows") or [None])[0]
        new = (v.get("new_rows") or [None])[0]
        obs = (v.get("observed_rows") or [None])[0]
        cc = class_map.get(v.get("classification", "CORRUPT"), 4)
        ok = f"g_cu_{i}_ok" if old else "0"
        okl = len(hx(old["key_hex"])) if old else 0
        ov = f"g_cu_{i}_ov" if old else "0"
        ovl = len(hx(old["value_hex"])) if old else 0
        nk = f"g_cu_{i}_nk" if new else "0"
        nkl = len(hx(new["key_hex"])) if new else 0
        nv = f"g_cu_{i}_nv" if new else "0"
        nvl = len(hx(new["value_hex"])) if new else 0
        sk = f"g_cu_{i}_sk" if obs else "0"
        skl = len(hx(obs["key_hex"])) if obs else 0
        sv = f"g_cu_{i}_sv" if obs else "0"
        svl = len(hx(obs["value_hex"])) if obs else 0
        op = 1 if obs else 0
        parts.append(
            f'  {{ "{v["id"]}", {cc}u, {ok}, {okl}u, {ov}, {ovl}u, '
            f"{nk}, {nkl}u, {nv}, {nvl}u, {sk}, {skl}u, {sv}, {svl}u, {op} }},\n"
        )
    parts.append("};\n")

    # FBA state transitions: decode new state from value
    fbas = d["fba_state_transition_vectors"]
    parts.append(f"#define FABRIC_V1_FBA_EXEC_COUNT {len(fbas)}u\n")
    parts.append(
        "typedef struct fabric_v1_fba_row {"
        " const char *id; const uint8_t *new_val; uint32_t new_vl;"
        " uint32_t expected_state; } fabric_v1_fba_row_t;\n"
    )
    # map cause to approximate new state from value payload offset 40 (state u32 BE)
    for i, v in enumerate(fbas):
        new_rows = v.get("new_rows") or []
        if new_rows:
            parts.append(c_bytes(f"g_fba_{i}_nv", hx(new_rows[0]["value_hex"])))
    parts.append("static const fabric_v1_fba_row_t g_fba_exec_table[] = {\n")
    for i, v in enumerate(fbas):
        new_rows = v.get("new_rows") or []
        if not new_rows:
            continue
        val = hx(new_rows[0]["value_hex"])
        # envelope 24 then state at payload+40
        state = 0
        if len(val) >= 24 + 44:
            off = 24 + 40
            state = int.from_bytes(val[off : off + 4], "big")
        parts.append(
            f'  {{ "{v["id"]}", g_fba_{i}_nv, {len(val)}u, {state}u }},\n'
        )
    parts.append("};\n")

    # Executable baseline snapshot for real ninlil_fabric_private_select.
    base = next(v for v in vectors if v["id"] == "FABRIC-SELECT-ACTUAL-JOIN-BASELINE")
    inp = base["inputs"]
    q = inp["query"]
    pol = inp["policies"][0]
    reg = inp["registry"][0]
    auth = inp["authorities"][0]

    def c_bool(v: object) -> str:
        return "1u" if v else "0u"

    def c_hex_arr(hex_s: str) -> str:
        b = hx(hex_s)
        return ", ".join(f"0x{x:02x}u" for x in b)

    parts.append(
        "\n/* Baseline from FABRIC-SELECT-ACTUAL-JOIN-BASELINE JSON inputs. */\n"
        "static void fabric_v1_sel_vec_baseline("
        "ninlil_fabric_private_select_snapshot_t *s)\n"
        "{\n"
        "    ninlil_fabric_private_select_policy_t *p;\n"
        "    ninlil_fabric_private_select_registry_row_t *r;\n"
        "    ninlil_fabric_private_select_authority_row_t *a;\n"
        "    ninlil_fabric_private_memzero(s, sizeof(*s));\n"
        f"    s->outer_available = {c_bool(inp['meta'].get('outer_available', True))};\n"
        f"    (void)memcpy(s->query.service_identity_digest, "
        f"(const uint8_t[]){{{c_hex_arr(q['service_identity_digest_hex'])}}}, 32u);\n"
        f"    s->query.family = {int(q['family'])}u;\n"
        f"    s->query.direction = {int(q['direction'])}u;\n"
        f"    s->query.traffic_class = {int(q['traffic_class'])}u;\n"
        f"    (void)memcpy(s->query.source_runtime_id, "
        f"(const uint8_t[]){{{c_hex_arr(q['source_runtime_id_hex'])}}}, 16u);\n"
        f"    (void)memcpy(s->query.target_runtime_id, "
        f"(const uint8_t[]){{{c_hex_arr(q['target_runtime_id_hex'])}}}, 16u);\n"
        f"    (void)memcpy(s->query.target_application_id, "
        f"(const uint8_t[]){{{c_hex_arr(q['target_application_id_hex'])}}}, 16u);\n"
        f"    s->query.packet_bytes = {int(q['packet_bytes'])}u;\n"
        f"    s->query.transfer_bytes = {int(q['transfer_bytes'])}u;\n"
        f"    s->query.now_ms = {int(q['now_ms'])}ull;\n"
        f"    s->query.deadline_ms = {int(q['deadline_ms'])}ull;\n"
        f"    (void)memcpy(s->query.deadline_clock_epoch_id, "
        f"(const uint8_t[]){{{c_hex_arr(q['deadline_clock_epoch_id_hex'])}}}, 16u);\n"
        f"    (void)memcpy(s->query.admission_clock_epoch_id, "
        f"(const uint8_t[]){{{c_hex_arr(q['admission_clock_epoch_id_hex'])}}}, 16u);\n"
        f"    (void)memcpy(s->query.availability_clock_epoch_id, "
        f"(const uint8_t[]){{{c_hex_arr(q['availability_clock_epoch_id_hex'])}}}, 16u);\n"
        f"    (void)memcpy(s->query.attestation_clock_epoch_id, "
        f"(const uint8_t[]){{{c_hex_arr(q['attestation_clock_epoch_id_hex'])}}}, 16u);\n"
        f"    (void)memcpy(s->query.authority_clock_epoch_id, "
        f"(const uint8_t[]){{{c_hex_arr(q['authority_clock_epoch_id_hex'])}}}, 16u);\n"
        f"    s->query.required_capability_flags = {int(q['required_capability_flags'])}u;\n"
        f"    s->query.required_security_flags = {int(q['required_security_flags'])}u;\n"
        f"    s->query.requires_sleep_compatible = {c_bool(q.get('requires_sleep_compatible'))};\n"
        f"    s->query.requires_custody = {c_bool(q.get('requires_custody'))};\n"
        f"    s->query.requires_evidence = {c_bool(q.get('requires_evidence'))};\n"
        f"    (void)memcpy(s->query.authenticated_peer_runtime_id, "
        f"(const uint8_t[]){{{c_hex_arr(q['authenticated_peer_runtime_id_hex'])}}}, 16u);\n"
        f"    (void)memcpy(s->query.attachment_authority_id, "
        f"(const uint8_t[]){{{c_hex_arr(q['attachment_authority_id_hex'])}}}, 16u);\n"
        f"    (void)memcpy(s->query.attachment_binding_digest, "
        f"(const uint8_t[]){{{c_hex_arr(q['attachment_binding_digest_hex'])}}}, 32u);\n"
        f"    s->query.rf_permit_valid = {c_bool(q.get('rf_permit_valid'))};\n"
        f"    s->query.rf_mapping_accepted = {c_bool(q.get('rf_mapping_accepted'))};\n"
        "\n"
        "    s->policy_count = 1u;\n"
        "    p = &s->policies[0];\n"
        f"    (void)memcpy(p->policy_id, "
        f"(const uint8_t[]){{{c_hex_arr(pol['policy_id_hex'])}}}, 16u);\n"
        f"    p->revision = {int(pol['revision'])}ull;\n"
        f"    (void)memcpy(p->canonical_digest, "
        f"(const uint8_t[]){{{c_hex_arr(pol['canonical_digest_hex'])}}}, 32u);\n"
        f"    (void)memcpy(p->service_identity_digest, "
        f"(const uint8_t[]){{{c_hex_arr(pol['service_identity_digest_hex'])}}}, 32u);\n"
        f"    p->family = {int(pol['family'])}u;\n"
        f"    p->direction = {int(pol['direction'])}u;\n"
        f"    p->traffic_class = {int(pol['traffic_class'])}u;\n"
        f"    p->scope_selector = "
        f"{2 if pol.get('scope_selector') == 'TARGET_RUNTIME' else 1}u;\n"
        f"    p->required_capability_flags = {int(pol['required_capability_flags'])}u;\n"
        f"    p->required_security_flags = {int(pol['required_security_flags'])}u;\n"
        f"    p->maximum_latency_class = {int(pol['maximum_latency_class'])}u;\n"
        f"    p->maximum_cost_class = {int(pol['maximum_cost_class'])}u;\n"
        f"    p->minimum_packet_bytes = {int(pol['minimum_packet_bytes'])}u;\n"
        f"    p->authority_mode = "
        f"{1 if pol.get('authority_mode') == 'BOUND_REQUIRED' else 0}u;\n"
        f"    p->deadline_guard_ms = {int(pol['deadline_guard_ms'])}ull;\n"
        f"    p->candidate_count = {len(pol['candidates'])}u;\n"
    )
    for ci, cand in enumerate(pol["candidates"]):
        parts.append(
            f"    (void)memcpy(p->candidates[{ci}].instance_id, "
            f"(const uint8_t[]){{{c_hex_arr(cand['instance_id_hex'])}}}, 16u);\n"
            f"    p->candidates[{ci}].rank = {int(cand['rank'])}u;\n"
            f"    p->candidates[{ci}].reservation_units = "
            f"{int(cand['reservation_units'])}u;\n"
        )
    chain = pol.get("revision_chain") or list(range(1, int(pol["revision"]) + 1))
    parts.append(f"    p->revision_chain_len = {len(chain)}u;\n")
    for ci, rev in enumerate(chain):
        parts.append(f"    p->revision_chain[{ci}] = {int(rev)}u;\n")

    parts.append(
        "\n"
        "    s->registry_count = 1u;\n"
        "    r = &s->registry[0];\n"
        f"    (void)memcpy(r->instance_id, "
        f"(const uint8_t[]){{{c_hex_arr(reg['instance_id_hex'])}}}, 16u);\n"
        f"    r->link_kind = {2 if reg.get('link_kind') == 'WIFI' else 4}u;\n"
        f"    r->direction_mask = {int(reg['direction_mask'])}u;\n"
        f"    r->capability_flags = {int(reg['capability_flags'])}u;\n"
        f"    r->security_capability_flags = {int(reg['security_capability_flags'])}u;\n"
        f"    r->maximum_packet_bytes = {int(reg['maximum_packet_bytes'])}u;\n"
        f"    r->maximum_transfer_bytes = {int(reg['maximum_transfer_bytes'])}u;\n"
        f"    r->latency_class = {int(reg['latency_class'])}u;\n"
        f"    r->cost_class = {int(reg['cost_class'])}u;\n"
        f"    r->reservation_capacity = {int(reg['reservation_capacity'])}u;\n"
        f"    r->lifecycle = {1 if reg.get('lifecycle') == 'ACTIVE' else 2}u;\n"
        f"    r->peer_nfl1_version = {int(reg['peer_nfl1_version'])}u;\n"
        f"    r->peer_fabric_capability_flags = "
        f"{int(reg['peer_fabric_capability_flags'])}u;\n"
        f"    (void)memcpy(r->authenticated_peer_runtime_id, "
        f"(const uint8_t[]){{{c_hex_arr(reg['authenticated_peer_runtime_id_hex'])}}}, 16u);\n"
        f"    (void)memcpy(r->attachment_authority_id, "
        f"(const uint8_t[]){{{c_hex_arr(reg['attachment_authority_id_hex'])}}}, 16u);\n"
        f"    (void)memcpy(r->attachment_binding_digest, "
        f"(const uint8_t[]){{{c_hex_arr(reg['attachment_binding_digest_hex'])}}}, 32u);\n"
        f"    (void)memcpy(r->attestation_clock_epoch_id, "
        f"(const uint8_t[]){{{c_hex_arr(reg['attestation_clock_epoch_id_hex'])}}}, 16u);\n"
        f"    r->attestation_expires_at_ms = {int(reg['attestation_expires_at_ms'])}ull;\n"
        f"    (void)memcpy(r->availability_clock_epoch_id, "
        f"(const uint8_t[]){{{c_hex_arr(reg['availability_clock_epoch_id_hex'])}}}, 16u);\n"
        f"    r->availability_state = {int(reg['availability_state'])}u;\n"
        f"    r->availability_expires_at_ms = "
        f"{int(reg['availability_expires_at_ms'])}ull;\n"
        "    r->rf_mapping_approved = 1u;\n"
        "\n"
        "    s->authority_count = 1u;\n"
        "    a = &s->authorities[0];\n"
        f"    (void)memcpy(a->service_identity_digest, "
        f"(const uint8_t[]){{{c_hex_arr(auth['service_identity_digest_hex'])}}}, 32u);\n"
        f"    a->family = {int(auth['family'])}u;\n"
        f"    a->direction = {int(auth['direction'])}u;\n"
        f"    a->traffic_class = {int(auth['traffic_class'])}u;\n"
        f"    a->scope_selector = "
        f"{2 if auth.get('scope_selector') == 'TARGET_RUNTIME' else 1}u;\n"
        f"    (void)memcpy(a->endpoint_runtime_id, "
        f"(const uint8_t[]){{{c_hex_arr(auth['endpoint_runtime_id_hex'])}}}, 16u);\n"
        f"    (void)memcpy(a->target_runtime_id, "
        f"(const uint8_t[]){{{c_hex_arr(auth['target_runtime_id_hex'])}}}, 16u);\n"
        f"    (void)memcpy(a->target_application_id, "
        f"(const uint8_t[]){{{c_hex_arr(auth['target_application_id_hex'])}}}, 16u);\n"
        f"    (void)memcpy(a->policy_id, "
        f"(const uint8_t[]){{{c_hex_arr(auth['policy_id_hex'])}}}, 16u);\n"
        f"    a->policy_revision = {int(auth['policy_revision'])}ull;\n"
        f"    (void)memcpy(a->policy_digest, "
        f"(const uint8_t[]){{{c_hex_arr(auth['policy_digest_hex'])}}}, 32u);\n"
        f"    a->authority_state = "
        f"{1 if auth.get('authority_state') == 'BOUND' else 0}u;\n"
        f"    (void)memcpy(a->authority_clock_epoch_id, "
        f"(const uint8_t[]){{{c_hex_arr(auth['authority_clock_epoch_id_hex'])}}}, 16u);\n"
        f"    a->lease_expires_at_ms = {int(auth['lease_expires_at_ms'])}ull;\n"
        "    s->active_attempt_count = 0u;\n"
        "}\n"
    )

    parts.append("#endif\n")
    return "".join(parts)


def self_test() -> int:
    """Compare-only --check plus mutation must fail without leaving drift."""
    expected = render()
    if not OUT.exists():
        print(f"self-test FAIL: missing {OUT}", file=sys.stderr)
        return 1
    before = OUT.read_bytes()
    if before != expected.encode("utf-8") and before.decode("utf-8") != expected:
        # Normalize: render returns str; file may match as text.
        if OUT.read_text() != expected:
            print(f"self-test FAIL: {OUT} already stale", file=sys.stderr)
            return 1
    # Mutation rejection: temporarily corrupt file content, --check must fail.
    orig = OUT.read_text()
    try:
        OUT.write_text(orig + "/*drift-self-test*/\n")
        if OUT.read_text() == expected:
            print("self-test FAIL: mutation did not change file", file=sys.stderr)
            return 1
        mut_actual = OUT.read_text()
        if mut_actual == expected:
            print("self-test FAIL: mutated equals expected", file=sys.stderr)
            return 1
        # Inline compare-only contract of --check
        if mut_actual == expected:
            print("self-test FAIL: --check would accept drift", file=sys.stderr)
            return 1
    finally:
        OUT.write_text(orig)
    if OUT.read_text() != expected:
        print("self-test FAIL: restoration drift", file=sys.stderr)
        return 1
    print(f"self-test OK {OUT}", file=sys.stderr)
    return 0


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser(
        description="Generate fabric_v1_selection_vectors.h (nonmutating --check)"
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="Write generated header")
    mode.add_argument(
        "--check",
        action="store_true",
        help="Reject deterministic drift without mutating the tree",
    )
    mode.add_argument(
        "--self-test",
        action="store_true",
        help="Mutation self-test: --check rejects drift; restores file",
    )
    args = parser.parse_args()
    if args.self_test:
        return self_test()
    expected = render()
    if args.write:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(expected)
        print(f"wrote {OUT}", file=sys.stderr)
        return 0
    # --check: compare-only, no write
    if not OUT.exists():
        print(f"missing {OUT}", file=sys.stderr)
        return 1
    actual = OUT.read_text()
    if actual != expected:
        print(f"stale {OUT}: deterministic drift vs generator", file=sys.stderr)
        return 1
    print(f"check ok {OUT}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
