#!/usr/bin/env python3
"""Produce independent re-audit evidence for ADR-0018 wifi-bearer-spec-v1.

Does not claim SPEC_ACCEPTED. Captures gate self-test stdout literally so work-note
coverage numbers cannot drift ahead of measured donor/exhaustive counts.
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
VECTOR = ROOT / "spec/vectors/wifi-bearer-spec-v1.json"
OUT = ROOT / "docs/work/2026-07-29-wifi-bearer-spec-evidence.json"
COVERAGE_FRAGMENT = ROOT / "docs/work/2026-07-29-wifi-bearer-spec-coverage.fragment.md"
WORK_NOTE = ROOT / "docs/work/2026-07-29-wifi-real-path-authority-candidate.md"
REVIEWS_README = ROOT / "docs/reviews/README.md"


def load_gate():
    path = ROOT / "tools/wifi_bearer_spec_gate.py"
    spec = importlib.util.spec_from_file_location("wifi_gate_evidence", path)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


def run(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT)


def parse_int(pattern: str, text: str, label: str) -> int:
    match = re.search(pattern, text)
    if not match:
        raise SystemExit(f"missing {label} in gate output:\n{text[-500:]}")
    return int(match.group(1))


def parse_py_self_test(stdout: str) -> dict[str, Any]:
    # wifi bearer Python gate self-test: OK ids=79 donor_rejects=79 extra_mutations=12
    donor = parse_int(r"donor_rejects=(\d+)", stdout, "python donor_rejects")
    ids = parse_int(r"self-test: OK ids=(\d+)", stdout, "python ids")
    objects = parse_int(r"object_paths=(\d+)", stdout, "python object_paths")
    ints = parse_int(r"integer_leaves=(\d+)", stdout, "python integer_leaves")
    strs = parse_int(r"string_leaves=(\d+)", stdout, "python string_leaves")
    digs = parse_int(r"digest_leaves=(\d+)", stdout, "python digest_leaves")
    scalars = parse_int(
        r"exhaustive scalar-value: OK leaves=(\d+) accepted=0",
        stdout,
        "python scalar leaves",
    )
    if "bool_accepted=0" not in stdout or "unknown_accepted=0" not in stdout:
        raise SystemExit("python exhaustive structure missing accepted=0 markers")
    if "digest_flip_accepted=0" not in stdout:
        raise SystemExit("python digest flip accepted marker missing")
    return {
        "ids": ids,
        "donor_rejects": donor,
        "donor_policy": "one donor body per victim id (not full cross-product)",
        "object_paths": objects,
        "integer_leaves": ints,
        "string_leaves": strs,
        "digest_leaves": digs,
        "scalar_leaves": scalars,
        "stdout_tail": "\n".join(stdout.strip().splitlines()[-4:]),
    }


def parse_node_self_test(stdout: str) -> dict[str, Any]:
    donor = parse_int(r"donor_rejects=(\d+)", stdout, "node donor_rejects")
    ids = parse_int(r"self-test: OK ids=(\d+)", stdout, "node ids")
    objects = parse_int(r"object_paths=(\d+)", stdout, "node object_paths")
    ints = parse_int(r"integer_leaves=(\d+)", stdout, "node integer_leaves")
    strs = parse_int(r"string_leaves=(\d+)", stdout, "node string_leaves")
    digs = parse_int(r"digest_leaves=(\d+)", stdout, "node digest_leaves")
    scalars = parse_int(
        r"exhaustive scalar-value: OK leaves=(\d+) accepted=0",
        stdout,
        "node scalar leaves",
    )
    if "bool_accepted=0" not in stdout or "unknown_accepted=0" not in stdout:
        raise SystemExit("node exhaustive structure missing accepted=0 markers")
    return {
        "ids": ids,
        "donor_rejects": donor,
        "donor_policy": "one donor body per victim id (not full cross-product)",
        "object_paths": objects,
        "integer_leaves": ints,
        "string_leaves": strs,
        "digest_leaves": digs,
        "scalar_leaves": scalars,
        "stdout_tail": "\n".join(stdout.strip().splitlines()[-4:]),
    }


def parse_c_test(stdout: str) -> dict[str, Any]:
    # wifi_bearer_spec_vector_test: PASS executed_ids=79 donor_rejects=6162
    # also: wifi_bearer_spec donor_self_test rejects=6162
    executed = parse_int(r"executed_ids=(\d+)", stdout, "c executed_ids")
    donor = parse_int(r"donor_rejects=(\d+)", stdout, "c donor_rejects")
    return {
        "executed_ids": executed,
        "donor_rejects": donor,
        "donor_policy": "full cross-product victim×donor with donor!=victim (79×78)",
        "stdout_tail": stdout.strip().splitlines()[-2:],
    }


def render_coverage_fragment(coverage: dict[str, Any], vector_sha: str) -> str:
    py = coverage["python"]
    node = coverage["node"]
    c11 = coverage.get("c11")
    lines = [
        "<!-- AUTO-GENERATED by tools/wifi_bearer_spec_audit_evidence.py; do not hand-edit. -->",
        "```text",
        f"vector sha256={vector_sha}",
        f"status=PROPOSED_CANDIDATE_NOT_SPEC_ACCEPTED ids={py['ids']}",
        "",
        "Donor coverage (measured from gate self-test stdout):",
        f"  Python: donor_rejects={py['donor_rejects']}  policy={py['donor_policy']}",
        f"  Node:   donor_rejects={node['donor_rejects']}  policy={node['donor_policy']}",
    ]
    if c11 is not None:
        lines.append(
            f"  C11:    donor_rejects={c11['donor_rejects']}  "
            f"policy={c11['donor_policy']}"
        )
        lines.append(
            f"  note: 79×78={c11['donor_rejects']} is C11 full cross-product only; "
            "Py/Node self-tests do not claim 6162."
        )
    else:
        lines.append(
            "  C11:    (binary not run in this evidence pass; expected 79×78=6162 when run)"
        )
    lines.extend(
        [
            "",
            "Exhaustive false-green surface (Py+Node self-test stdout; accepted=0):",
            f"  object_paths={py['object_paths']} unknown_key accepted=0",
            f"  integer_leaves={py['integer_leaves']} bool_as_int accepted=0 int_as_str accepted=0",
            f"  string_leaves={py['string_leaves']} str_as_int accepted=0",
            f"  digest_leaves={py['digest_leaves']} digest_flip accepted=0",
            f"  scalar_leaves={py['scalar_leaves']} type-preserving value campaign accepted=0",
            f"  document model SHA pin: {vector_sha}",
            "  DESCRIPTIVE_SCALAR_ALLOWLIST empty",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def verify_docs_against_coverage(coverage: dict[str, Any]) -> list[str]:
    """Fail closed on exaggerated donor/leaf claims in work note / reviews README."""
    errors: list[str] = []
    work = WORK_NOTE.read_text(encoding="utf-8") if WORK_NOTE.is_file() else ""
    reviews = REVIEWS_README.read_text(encoding="utf-8") if REVIEWS_README.is_file() else ""
    py_donor = coverage["python"]["donor_rejects"]
    node_donor = coverage["node"]["donor_rejects"]
    ints = coverage["python"]["integer_leaves"]
    c_donor = coverage.get("c11", {}).get("donor_rejects")

    # Forbidden: claim Py/Node do full 79×78 / 6162 donor matrix.
    bad_patterns = [
        (
            r"Python\+Node.*79\s*[×x*]\s*78",
            "work note claims Python+Node full 79×78 donor matrix",
        ),
        (
            r"donor 79\s*[×x*]\s*78 reject Python\+Node",
            "work note table claims Py+Node 79×78 donor",
        ),
        (
            r"generator/Python/Node donor 79\s*[×x*]\s*78",
            "reviews README claims Py/Node 79×78 donor",
        ),
        (
            r"ids=79\s+donor=79\s*[×x*]\s*78\s*=\s*6162",
            "work note local proof attributes 6162 to generic donor without C-only label",
        ),
        (
            r"\*\*359\*\* integer leaves",
            "work note still claims integer leaves=359 (stale)",
        ),
        (
            r"integer leaves359",
            "work note still claims integer leaves359 (stale)",
        ),
    ]
    for pattern, message in bad_patterns:
        if re.search(pattern, work, re.I) or re.search(pattern, reviews, re.I):
            errors.append(message)

    # Required accurate statements.
    required_work = [
        f"donor_rejects={py_donor}",
        f"integer_leaves={ints}",
        "one donor body per victim",
        "C11 full cross-product",
    ]
    if c_donor is not None:
        required_work.append(f"donor_rejects={c_donor}")
        required_work.append("79×78")
    for needle in required_work:
        if needle not in work:
            errors.append(f"work note missing required coverage phrase: {needle!r}")

    if f"donor_rejects={py_donor}" not in work or f"donor_rejects={node_donor}" not in work:
        # single phrase may cover both if equal
        if f"Python/Node donor_rejects={py_donor}" not in work and (
            f"Python: donor_rejects={py_donor}" not in work
        ):
            errors.append("work note must state Python donor_rejects measured value")

    return errors


def main() -> int:
    gate = load_gate()
    document = gate.load_json_strict(VECTOR)
    vector_sha = hashlib.sha256(VECTOR.read_bytes()).hexdigest()

    executed = gate.validate(document)
    objects = len(gate.iter_object_paths(document))
    ints = len(gate.iter_integer_leaf_paths(document))
    strs = len(gate.iter_string_leaf_paths(document))
    digs = len(gate.iter_digest_leaf_paths(document))
    scalars = len(gate.iter_scalar_leaves(document))

    py_check = run([sys.executable, str(ROOT / "tools/wifi_bearer_spec_gate.py"), "--check"])
    node_check = run(["node", str(ROOT / "tools/wifi_bearer_spec_gate.mjs"), "--check"])
    gen_check = run(
        [sys.executable, str(ROOT / "tools/wifi_bearer_spec_vector_gen.py"), "--check"]
    )
    py_self = run(
        [sys.executable, str(ROOT / "tools/wifi_bearer_spec_gate.py"), "--self-test"]
    )
    node_self = run(["node", str(ROOT / "tools/wifi_bearer_spec_gate.mjs"), "--self-test"])

    if py_self.returncode != 0:
        raise SystemExit(f"python self-test failed:\n{py_self.stderr}\n{py_self.stdout}")
    if node_self.returncode != 0:
        raise SystemExit(f"node self-test failed:\n{node_self.stderr}\n{node_self.stdout}")

    py_cov = parse_py_self_test(py_self.stdout)
    node_cov = parse_node_self_test(node_self.stdout)

    # Cross-check inventory from document walk vs self-test stdout.
    if py_cov["object_paths"] != objects or node_cov["object_paths"] != objects:
        raise SystemExit("object_paths mismatch between walk and self-test stdout")
    if py_cov["integer_leaves"] != ints or node_cov["integer_leaves"] != ints:
        raise SystemExit("integer_leaves mismatch between walk and self-test stdout")
    if py_cov["string_leaves"] != strs or node_cov["string_leaves"] != strs:
        raise SystemExit("string_leaves mismatch between walk and self-test stdout")
    if py_cov["digest_leaves"] != digs or node_cov["digest_leaves"] != digs:
        raise SystemExit("digest_leaves mismatch between walk and self-test stdout")
    if py_cov["scalar_leaves"] != scalars or node_cov["scalar_leaves"] != scalars:
        raise SystemExit("scalar_leaves mismatch between walk and self-test stdout")
    if py_cov["donor_rejects"] != node_cov["donor_rejects"]:
        raise SystemExit("python/node donor_rejects parity mismatch")

    c11_cov: dict[str, Any] | None = None
    c_bin = ROOT / "build-wifi-normal/ninlil_wifi_bearer_spec_vector_test"
    if c_bin.is_file():
        c_run = run([str(c_bin)])
        if c_run.returncode != 0:
            raise SystemExit(f"c11 test failed:\n{c_run.stderr}\n{c_run.stdout}")
        c11_cov = parse_c_test(c_run.stdout + c_run.stderr)
        expected_full = py_cov["ids"] * (py_cov["ids"] - 1)
        if c11_cov["donor_rejects"] != expected_full:
            raise SystemExit(
                f"c11 donor_rejects={c11_cov['donor_rejects']} "
                f"want ids*(ids-1)={expected_full}"
            )

    coverage = {
        "python": py_cov,
        "node": node_cov,
        "c11": c11_cov,
        "inventory": {
            "object_paths": objects,
            "integer_leaves": ints,
            "string_leaves": strs,
            "digest_leaves": digs,
            "scalar_leaves": scalars,
            "acceptance_ids": executed,
        },
    }

    fragment = render_coverage_fragment(coverage, vector_sha)
    COVERAGE_FRAGMENT.write_text(fragment, encoding="utf-8")

    # Auto-refresh work-note coverage block when markers present.
    if WORK_NOTE.is_file():
        work_text = WORK_NOTE.read_text(encoding="utf-8")
        begin = "<!-- coverage:begin -->"
        end = "<!-- coverage:end -->"
        if begin in work_text and end in work_text:
            pre, rest = work_text.split(begin, 1)
            _, post = rest.split(end, 1)
            # fragment already ends with newline; keep markers on own lines
            refreshed = (
                pre
                + begin
                + "\n"
                + fragment.rstrip()
                + "\n"
                + end
                + post
            )
            if refreshed != work_text:
                WORK_NOTE.write_text(refreshed, encoding="utf-8")
                print(f"refreshed coverage block in {WORK_NOTE}")

    doc_errors = verify_docs_against_coverage(coverage)
    if doc_errors:
        raise SystemExit(
            "docs coverage gate failed:\n- " + "\n- ".join(doc_errors) + "\n"
            f"refresh work note from {COVERAGE_FRAGMENT}"
        )

    evidence = {
        "status": document.get("status"),
        "schema": document.get("schema"),
        "adr": document.get("adr"),
        "vector_path": "spec/vectors/wifi-bearer-spec-v1.json",
        "vector_sha256_hex": vector_sha,
        "acceptance_id_count": document.get("acceptance_id_count"),
        "executed_ids": executed,
        "object_path_count": objects,
        "integer_leaf_count": ints,
        "string_leaf_count": strs,
        "digest_leaf_count": digs,
        "scalar_leaf_count": scalars,
        "vector_document_model_sha256_hex": vector_sha,
        "coverage": coverage,
        "coverage_fragment_path": str(COVERAGE_FRAGMENT.relative_to(ROOT)),
        "exhaustive": {
            "unknown_key_accepted": 0,
            "bool_as_int_accepted": 0,
            "int_as_str_accepted": 0,
            "str_as_int_accepted": 0,
            "digest_flip_accepted": 0,
            "scalar_value_campaign_accepted": 0,
            "scalar_value_campaign_leaves": scalars,
            "descriptive_scalar_allowlist_size": 0,
        },
        "machine_vector_false_green_surface": {
            "recursive_unknown_key": f"closed 0/{objects} accepted (Py+Node exhaustive)",
            "bool_as_int": f"closed 0/{ints} accepted (Py+Node exhaustive)",
            "int_as_str_str_as_int": "closed 0 via type inventory path-set pins",
            "digest_preimage": f"closed 0/{digs} digest-flip accepted (Py+Node exhaustive)",
            "scalar_value_campaign": (
                f"closed 0/{scalars} type-preserving accepted "
                "(canonical document model SHA)"
            ),
            "donor_python": (
                f"donor_rejects={py_cov['donor_rejects']} "
                f"({py_cov['donor_policy']})"
            ),
            "donor_node": (
                f"donor_rejects={node_cov['donor_rejects']} "
                f"({node_cov['donor_policy']})"
            ),
            "donor_c11": (
                None
                if c11_cov is None
                else (
                    f"donor_rejects={c11_cov['donor_rejects']} "
                    f"({c11_cov['donor_policy']})"
                )
            ),
            "c11": "semantic ID contracts + KAT + inventory macros + document SHA pin",
        },
        "gates": {
            "python_check_exit": py_check.returncode,
            "node_check_exit": node_check.returncode,
            "generator_check_exit": gen_check.returncode,
            "python_self_test_exit": py_self.returncode,
            "node_self_test_exit": node_self.returncode,
            "python_check_stdout": py_check.stdout.strip(),
            "node_check_stdout": node_check.stdout.strip(),
            "generator_check_stdout": gen_check.stdout.strip(),
            "python_self_test_stdout_tail": py_cov["stdout_tail"],
            "node_self_test_stdout_tail": node_cov["stdout_tail"],
        },
        "claims": {
            "SPEC_ACCEPTED": False,
            "P0_closure_GO": False,
            "independent_review_GO": False,
            "implementation": False,
            "RELEASE_SUPPORTED": False,
        },
        "still_blocking_full_adr_spec_accepted": [
            "ADR-0018 SPEC_ACCEPTED gate items 2–8 beyond real-path machine vectors "
            "(TLS cert/NRV1/NCM1/NWS1/… KAT corpus, S1–S6 sync, independent security review)",
            "No POSIX TCP/TLS host implementation (private/feature-gated, default OFF)",
            "No ESP STA/driver/HIL path",
            "No CLOSURE_ROOTS_V1 final-ELF / target archive fingerprints",
        ],
    }
    OUT.write_text(json.dumps(evidence, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(evidence, indent=2, sort_keys=True))
    print(f"wrote {OUT}")
    print(f"wrote {COVERAGE_FRAGMENT}")
    if (
        py_check.returncode
        or node_check.returncode
        or gen_check.returncode
        or py_self.returncode
        or node_self.returncode
    ):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
