# Exact PA-S1a third-party translation-unit allow-list. Private and uninstalled.
set(NINLIL_PA_S1_EDHOC_RELATIVE_SOURCES
    third_party/production_attachment_edhoc/libedhoc/edhoc.c
    third_party/production_attachment_edhoc/libedhoc/edhoc_message_1.c
    third_party/production_attachment_edhoc/libedhoc/edhoc_message_2.c
    third_party/production_attachment_edhoc/libedhoc/edhoc_message_3.c
    third_party/production_attachment_edhoc/libedhoc/edhoc_message_4.c
    third_party/production_attachment_edhoc/libedhoc/edhoc_message_error.c
    third_party/production_attachment_edhoc/libedhoc/edhoc_exporter.c
    third_party/production_attachment_edhoc/libedhoc/edhoc_common.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_bstr_type_decode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_bstr_type_encode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_connection_identifier_decode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_connection_identifier_encode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_ead_decode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_ead_encode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_enc_structure_decode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_enc_structure_encode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_id_cred_x_decode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_id_cred_x_encode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_info_decode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_info_encode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_int_type_decode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_int_type_encode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_message_1_decode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_message_1_encode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_message_2_decode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_message_2_encode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_message_3_decode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_message_3_encode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_message_4_decode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_message_4_encode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_message_error_decode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_message_error_encode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_plaintext_2_decode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_plaintext_2_encode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_plaintext_3_decode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_plaintext_3_encode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_plaintext_4_decode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_plaintext_4_encode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_sig_structure_decode.c
    third_party/production_attachment_edhoc/libedhoc/backend_cbor_sig_structure_encode.c
    third_party/production_attachment_edhoc/zcbor/zcbor_common.c
    third_party/production_attachment_edhoc/zcbor/zcbor_decode.c
    third_party/production_attachment_edhoc/zcbor/zcbor_encode.c)
